composer.json

The intl extension is used and should be included in the composer.json file.

Add intl extension to composer.json

---

packages/Webkul/User/src/Http/Controllers/UserController.php

This PR fixes firing the wrong event after storing a new user.

Fix firing the wrong event after storing user

---

packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
packages/Webkul/Sales/src/Config/system.php
packages/Webkul/Sales/src/Providers/SalesServiceProvider.php
packages/Webkul/Sales/src/Repositories/OrderRepository.php
packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
packages/Webkul/Shop/src/Resources/views/checkout/success.blade.php

Bagisto currently exposes actual orders table ID column to the client and there is no option to configure a custom order number for a specific store.
This is a neccessary feature since many inventory/backend systems require order numbers in a certain format. This is feature is available in WooCommerce and Magento to name a few.
Current change adds an option to configure a custom order number in the backend that consists of 
- a prefix,
- order number that contains the order id and has user-set length
- a suffix. 
If none of the options are set, then the number is set as previously.  
The order number is then visible in admin order index, order single-template view and for customer in success page and order history.

added configurable order numbers

---

packages/Webkul/Product/src/Type/AbstractType.php

**BUGS:**
After updating to latest master with build containing multiple product types the command php artisan bagisto:generate product n was not working.

Generate product command bug fix

---

packages/Webkul/Shop/src/Resources/views/emails/customer/registration.blade.php

[Bug Fixed: #1613  ]
1 - The new customer registration email now loads up with custom logo set in default channel.

issue #1613 fixed

---

README.md

Rename WAMP to WampServer to match with official | Fix typo for XAMPP

Rename WAMP to WampServer to match with official | Fix typo for XAMPP

---

packages/Webkul/Shop/src/Resources/views/products/view.blade.php

The following view render event was declared twice, both before and after the product description:
`{!! view_render_event('bagisto.shop.products.view.description.before', ['product' => $product]) !!}`
I fixed the second instance to be bagisto.shop.products.view.description.**after**

Fixed duplicate view_render_event for product descriptions

---

packages/Webkul/Product/src/CacheFilters/Large.php
packages/Webkul/Product/src/CacheFilters/Medium.php
packages/Webkul/Product/src/CacheFilters/Small.php
packages/Webkul/Shop/src/Resources/assets/sass/app.scss

Fixing image scaling according to the issue #979 
- resizing images inside Small/Medium/Large.php considering the aspect ratio and adding whitespace to it, so that the images have the same size and the thumbnails on the product detail page don't get distorted
- making a couple scss changes, because it's not a good idea to provide a fixed width and height for images. The images will get distorted if we do that

#979 fix image scaling issues

---

packages/Webkul/Admin/src/Config/menu.php
packages/Webkul/Core/src/Models/Channel.php

**BUG Fixes**
- Fixed issue #1710 
**Channel** model in **core** package's fillable property had **_logo_** and **_favicon_** column names missing.

Added logo, favicon in fillable of channel model

---

packages/Webkul/Core/src/Tree.php

Feature #1707 
Allow a new key in menu.php in order to configure parameters of routes. The new key `params` is optional

add option to allow params in menu.php

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php

In our application we want to register specific additional accordions in the edit form that should _always_ be displayed, indepenent of the product type. In order to achieve this we propose to do this two more events in the edit form to hook into.

introduce two view_render_event hooks in product edit form

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/payment.blade.php

Moved payment type title inside of radio button label. This is a minor usability improvement, and also important for web accessibility.

Minor usability/accessability fix for payment type labels

---

packages/Webkul/API/Http/Resources/Catalog/Product.php
packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
packages/Webkul/Discount/src/Helpers/Catalog/Apply.php
packages/Webkul/Discount/src/Helpers/Catalog/ConvertXToProductId.php
packages/Webkul/Product/src/Helpers/ProductType.php
packages/Webkul/Product/src/Http/Controllers/ProductController.php
packages/Webkul/Product/src/Listeners/ProductFlat.php
packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php

Aiming to be more flexible with product types, e.g. creating a configurable product with visual variants, I replaced hard coded checks whether product types are "configurable" with check whether product types can have variants.
Therefor, I added a property "hasVariants" to AbstractType and Configurable, and added two helper functions to check for it.

introduce ProductType Helper

---

.gitignore
packages/Webkul/Ui/src/Resources/assets/js/directives/slugify.vue

improve the sluggify javascript snipppet a little bit so that multiple dashes (----) gets translated into a single dash.
In german products its common to use titles like "Foo - Bar" which would translate into "foo---bar" without this patch. ("foo-bar" is desired)

improve sluggable logic

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/views/settings/development/dashboard.blade.php

Removed remnants of laravel-web-console from development view and language files:
- removed route to webconsole from blade
- removed translations for webconsole
This PR is an addition to #1791 and #1819.

Removed remnants of laravel-web-console

---

packages/Webkul/Sales/src/Repositories/DownloadableLinkPurchasedRepository.php

Dear Bagisto team,
In our shop, we created a custom downloadable product type, that exists next to the Bagisto downloadable product type and thus, has a different product_type key. Therefor, our downloadable links are not saved at the moment, when the product is purchased. 
That is why we unclenched the condition a bit, to be able to use the function with our custom downloadable type.
If you would accept this small adaptation, it would be very much appreciated.

slackened condition to save downloadable purchase link

---

composer.json
packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
packages/Webkul/Shop/src/Http/routes.php

Replaced wildcard route for products and categories with fallback route (old route 'shop.productOrCategory.index' caused API routes to not be callable).

Make API routes accessable 

---

packages/Webkul/Product/src/Helpers/ProductType.php

When applying a catalog rule, an exception occurs, warning that array_push needs to be given an array.
To reproduce the exception: 
- create a new catalog rule
- click "Apply"
Screenshot: 
I initialised the array.

Bugfix: Exception while applying catalog rule

---

app/Console/Commands/install.php

**Added a `bagisto:install` command:**
- According to this [docs](https://devdocs.bagisto.com/index.html#installation), users need to do 6 steps.
- This process is time-consuming and not user-friendly.
- The user needs to look at the documentation for every step.
- Sometimes user misspells any command.
- All 6 steps are combined into just one command called `bagisto:install`
- Step 1. Check for `.env` file, if not exists then this command will create it from `.env.example`.
- After creating `.env` it will ask for `DB_DATABASE`, `DB_USERNAME` and `DB_PASSWORD`
- Step 2. running `php artisan migrate`
- Step 3. running `php artisan db:seed`
- Step 4. running `php artisan vendor:publish --all`
- Step 5. running `php artisan storage:link`
- Step 6. running `composer dump-autoload`
**Just One …

Added `php artisan bagisto:install` command

---

packages/Webkul/Core/src/Database/Migrations/2020_01_02_201029_add_api_token_columns.php
packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
packages/Webkul/Customer/src/Models/Customer.php
packages/Webkul/User/src/Database/Seeders/AdminsTableSeeder.php
packages/Webkul/User/src/Http/Controllers/UserController.php
packages/Webkul/User/src/Models/Admin.php

In order to use authenticated API routes (that are protected by `auth:api` or `auth:admin-api` guard) we need to have the api_token columns in the corresponding tables.

add missing api_token columns to database (table customers and admins)

---

app/Console/Commands/GenerateProducts.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Listeners/Order.php
packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php
packages/Webkul/Attribute/src/Http/Controllers/AttributeFamilyController.php
packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
packages/Webkul/Core/src/Http/Controllers/CurrencyController.php
packages/Webkul/Core/src/Http/Controllers/ExchangeRateController.php
packages/Webkul/Core/src/Http/Controllers/SubscriptionController.php
packages/Webkul/Customer/src/Http/Controllers/ForgotPasswordController.php
packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
packages/Webkul/Inventory/src/Http/Controllers/InventorySourceController.php
packages/Webkul/Product/src/Http/Controllers/ProductController.php
packages/Webkul/Product/src/Http/Controllers/ReviewController.php
packages/Webkul/Shop/src/Http/Controllers/CartController.php
packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php
packages/Webkul/Tax/src/Http/Controllers/TaxRateController.php

**As-is**
There are several try-catch-sections inside bagisto. Very often the thrown exception is not handled at all or just as a flash-message for the user.
**Suggestion**
Add the `report()` helper-function of laravel to all try-catch-sections (see https://laravel.com/docs/6.x/errors#report-method for details). This function creates an entry in laravel's error log (default: `storage/logs/laravel.log`) but does not render an error page for the user. In addition, the exception is shown in the debug bar.

Add logging for catched exceptions

---

packages/Webkul/API/Http/Controllers/Shop/CartController.php

If a customer wants to buy a single product directly, the CartController add() method fires an event. The same event has to be fired at api request. In this case it's store() method.

Fire event if customer wants to "buy now"

---

packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Checkout/src/Models/CartAddress.php
packages/Webkul/Customer/src/Database/Migrations/2020_02_25_181902_propagate_company_name.php
packages/Webkul/Sales/src/Models/OrderAddress.php

Currently, when doing the checkout in a b2b shop (business to business) the information about the company_name and vat_id of the buyer gets lost during the checkout process. We need to propagate the company_name and vat_id from address through cart to order addresses. I just forgot this in the initial feature request i made a month ago. This PR fixes this.

company_name and vat_id address->cart->order (addresses) fixes

---

app/Console/Commands/GenerateProducts.php
packages/Webkul/Product/src/Helpers/GenerateProduct.php

to fix brand linking issue after checkout of generated product.
Currently, when generating products via `artisan bagisto:generate products 666` the generated products can not be bought because there is no brand associated with it. This PR fixes this issue.
It also introduces a fancy progress bar like:

generate a dummy brand in GenerateProducts.php

---

packages/Webkul/Ui/src/Resources/assets/js/directives/slugify-target.vue

Replace diacritics (ó, ł, ź, ă,ş,ţ etc) with their "normal" form (o, l, z, a,s,t)
**BUGS:**
Slugify-target directives actually remove diacritics in my language, added normalize causes replace this letters for friendly RFC 1738 letters.

Replace diacritics

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

Reverts bagisto/bagisto#2603
Dear @jitendra-webkul and @rahulshukla-webkul 
please revert the changes in ProductDataGrid. 
The changes are only searching for products of one single locale, it is not possible anymore to administrate products of all locales.
Also, the selected channel is not used in the query anymore, i.e. I neither can filter for products of a specified channel, nor can I administrate products of all channels together.
And at last, I have to state the worse readability of the constructor.

Revert "Development"

---

packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
packages/Webkul/Tax/src/Providers/TaxServiceProvider.php

This PR aims the possibility to flash more than one message in the admin panel. For now, only one message per request is shown, the last flashed message, to be clear.
Example scenario:
By using an event listener, it is possible to manipulate form data in the admin panel. For instance, to add a custom field to the channel's editing form and to store the data in a custom database table.
If for that custom data the validation fails, the listener may throw a flash message to inform the admin about. The rest of the process should not be touched or interrupted. That means, the original bagisto channel data should be processed and stored as usual. 
And after that, a success message might be thrown, that overwrites any other message thrown by the listener before.
With this small PR, it is …

bugfix: show multiple flash messages in admin panel

---

packages/Webkul/Core/src/Database/Factories/LocaleFactory.php

The LocaleFactory uses a random locale code to generate a new Locale. If some Locales have been seeded yet, the factory uses to flicker. For instance, there already is a locale for English, and the factory's random local code is "en", then an integrity constraint exception for duplicated locale code is thrown.
This PR lets the LocaleFactory return an existing Locale with the randomly generated locale code. If no Locale having that code exists yet, it creates a new one.

prevent locale factory from flickering

---

packages/Webkul/Tax/src/Helpers/Tax.php
tests/unit/Tax/Helpers/TaxCest.php

**BUG**
We found a bug in how tax amounts are displayed.
Lets suppose we have a simple product.
It's price is 1.50€ and tax_rate is 19%.
What I see in cart is this:
```
Tax 19%       0.28€
Grand Total   1.79€
```
Calculation of grand_total is correct but, the displayed tax_amount is wrongly rounded.
This is fixed by moving rounding position.

Fix tax rate rounding

---

packages/Webkul/Core/src/Database/Factories/LocaleFactory.php

In PR #2753 I aimed to prevent the LocaleFactory from flickering. 
Unfortunately, that was not successful. That is why I offer this new PR to be sure, that factory will not flicker anymore at any time: Using a Do-While, the factory is forced to find a new locale code, which is not used yet.

fix still flickering locale factory

---

packages/Webkul/Core/src/Core.php

**Problem**
At the moment there is no option to actually set the current channel of the application. The channel is determined during the first call of `core()->getCurrentChannel()` and saved until the request is finished. Since the current channel is determined by the current domain it is really hard to create api-endpoints which the capability to e.g. create a cart in a different channel.
**Suggestion**
Add a new function in `\Webkul\Core\Core` to set the current channel at any time like this:
```
$channel = \Webkul\Core\Models\Channel::query()->find(5);
core()->setCurrentChannel($channel);
```
Please have a look at the changes which offer a solution to this problem.

add option to set current channel

---

packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/signup/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/index.blade.php

Hello Guys
To allow better customizations, for example, a package to create a new customer or shipping attribute, and to be able to inject this new attribute input in the forms I created a new view_render_event after every customer form input or profile attribute.
Also, I fixed the names of the Velocity profile edit view that were wrong.
For last I added some events in the order view page (storefront and admin), I want to be able to inject some payment information on this page from my new payment module.
Cheers

Added new view_render_event events

---

packages/Webkul/Sales/src/Database/Factories/OrderItemFactory.php

This PR offers the possibility to the OrderItemFactory to use an existing product as order item, passed by product ID, rather than creating a new product.

add option to OrderItemFactory to use existing product

---

packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
packages/Webkul/Admin/src/DataGrids/OrderRefundDataGrid.php
packages/Webkul/Admin/src/DataGrids/OrderShipmentsDataGrid.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Checkout/src/Database/Factories/CartAddressFactory.php
packages/Webkul/Checkout/src/Models/Cart.php
packages/Webkul/Checkout/src/Models/CartAddress.php
packages/Webkul/Checkout/src/Models/CartShippingRate.php
packages/Webkul/Core/src/Database/Migrations/2020_04_16_185147_add_table_addresses.php
packages/Webkul/Core/src/Models/Address.php
packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php
packages/Webkul/Customer/src/Models/CustomerAddress.php
packages/Webkul/Sales/src/Database/Factories/OrderAddressFactory.php
packages/Webkul/Sales/src/Models/Invoice.php
packages/Webkul/Sales/src/Models/Order.php
packages/Webkul/Sales/src/Models/OrderAddress.php
packages/Webkul/Sales/src/Models/Shipment.php
packages/Webkul/Shipping/src/Carriers/FlatRate.php
packages/Webkul/Shipping/src/Carriers/Free.php
tests/functional/Checkout/Order/OrderCest.php
tests/unit/Core/AddressCest.php

Please have a look at #2902 first in order to understand the problem.
I've decided to use global scopes and inheritance for addresses. This pr introduces:
* a new table called `addresses` which saves all types of addresses (`address_type` is used to mark the different types)
* a migration which migrates the old address-data to the new table
* global scopes in `CartAddress`, `OrderAddress` and `CustomerAddress` in order to handle all address types with the same table
* changes at several places which do not access db-data via models (e.g. data-grids)
* some fixes in typos of e.g. type hints
* a few tests to ensure all relations to addresses work proper
It is not intended to use the new Model `Address` directly. Like before the 3 special address-models can be used to work with addresses. …

Unified addresses (#2902)

---

packages/Webkul/Admin/src/Resources/views/tax/tax-categories/create.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/edit.blade.php
packages/Webkul/Tax/src/Database/Factories/TaxCategoryFactory.php
packages/Webkul/Tax/src/Database/Migrations/2020_04_16_130351_remove_channel_from_tax_category.php
packages/Webkul/Tax/src/Http/Controllers/TaxCategoryController.php
packages/Webkul/Tax/src/Models/TaxCategory.php
public/mix-manifest.json

The present PR removes the channel from the tax category.
**Fixed Bug:**
When creating or editing a tax category, selecting a channel is required. This is unnecessary, because: 
1. The tax category is assigned to a product, and the product is assigned to a channel. Thus, the tax category is only available to the product if bought in that channel.
2. When editing a product, it is not checked which tax category can be selected for the current product channel. 
My conclusion is hence, that assigning a channel to a tax category does not have any consequences on the one hand, and is not necessary on the other hand.

Bugfix: Channel assigned to tax category

---

packages/Webkul/BookingProduct/src/Providers/EventServiceProvider.php

The present PR checks if a view for the booking product details template exists for the current theme, and lets it being injected only then. 
Background:
With Booking Products, you provide an awesome and very powerful feature. Using our self-made theme, we did not adapt the views for it yet. The template is injected into the product details view, regardless if a view exists or not. That is why we have some templating issues now.

Booking Products: Inject template only if exists

---

packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Product/src/Type/Grouped.php

**BUGS:**
There is no space between the wording for configurable/grouped products.
**Expected:** "As low as $100"
**Actual:** "As low as$100"

Added missing space for configurable/grouped product price.

---

packages/Webkul/CartRule/src/Helpers/CartRule.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Tax/src/Helpers/Tax.php
tests/unit/CartRule/CartRuleCest.php
tests/unit/Tax/Helpers/TaxCest.php

- fixed a bug in discount calculation for percentage bases coupons
- removed type hint of \Webkul\Checkout\Models\Cart in Helpers/Tax.php as we use this funktion in various places with different objects
- fix some rounding issues for tax and discount calculation (cart items will always have 4 digits, cart totals will have only 2 digits)
- also added test scenario in CartRuleCest to check this
**Edit:**
There is a bug in CartRule.php validateCouponCode()
- If you have two or more coupons with the _same coupon code_, function validateCouponCode() will possible fail in checking cart rules
- this bug is fixed too

various fixes for cart rules and taxes

---

packages/Webkul/Checkout/src/Cart.php

**BUGS:**
Error when adding product to cart: "Undefined property: class@anonymous::$state"

Fixed undefined $state variable when using State based tax rates.

---

packages/Webkul/Product/src/Helpers/Toolbar.php
packages/Webkul/Product/src/Repositories/ProductRepository.php

**BUGS:**
Exception gets thrown when order is not specified in product sorting, or if the given order is invalid (not 'asc' or 'desc')

Products: Fix for missing or invalid sort direction

---

packages/Webkul/Product/src/Type/Bundle.php

**BUGS:**
Bundle items were not being ordered by their sort_order when added to the cart.

Ordering bundle items in cart by sort_order rather than id

---

packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/sales/address.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/review.blade.php

As mentioned in https://github.com/bagisto/bagisto/issues/2415, addresses company name should be shown in orders summary.
With this PR this is done for admin frontend and bliss theme.
@jitendra-webkul please have a look at it.
Thank you

add field company_name to bliss views

---

packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
packages/Webkul/Admin/src/Http/routes.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
tests/_support/FunctionalTester.php
tests/functional/CartRule/CartRuleCopyCest.php
tests/functional/CartRule/CartRuleCreateCest.php

In our Marketplace we use a lot of cart rules and coupons. In order to make it easier for the administrators to manage them, we introduced a "copy cart rule" feature. One could think to adapt this for other models scattered thorough bagisto, this is just a start. What is your opinion?

introduce the ability to copy a cart rule

---

packages/Webkul/Product/src/Repositories/SearchRepository.php
packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php

In some cases, our customers call the search without any query parameter (even without `?term=`). This heads into an exception since `term` is required for search. 
This fix adds the empty string as the default value so if the search is called without `?term=` is handled like `?term=` is given.

bugfix: add default value for search term

---

app/Console/Kernel.php
packages/Webkul/BookingProduct/src/Database/Factories/BookingProductEventTicketFactory.php
packages/Webkul/BookingProduct/src/Database/Factories/BookingProductFactory.php
packages/Webkul/BookingProduct/src/Providers/BookingProductServiceProvider.php
packages/Webkul/Core/src/Console/Commands/BookingCron.php
packages/Webkul/Core/src/Providers/CoreServiceProvider.php
tests/_support/Helper/DataMocker.php
tests/unit.suite.yml
tests/unit/Core/Commands/BookingCronCest.php

The present PR introduces a cronjob that automatically deactivates expired Booking Events.
It just turns off the status of the product. The product itself still is visible individually and keeps all other configuration.
With status turned off, the product cannot be added to the cart anymore.
**Bonus**: I added a DataMocker coded by @bosix to the unit testing suite, to make faking data in tests easier.
We now just have to type e.g. `$I->fake()->uuid`.

Automatically deactivate expired event products

---

packages/Webkul/Ui/src/Resources/assets/js/components/date.vue
packages/Webkul/Ui/src/Resources/assets/js/components/datetime.vue

Bagisto is using https://flatpickr.js.org as date and datetime picker. Unfortunately this (wonderful!) plugin still has this bug:
https://github.com/flatpickr/flatpickr/pull/2092
which is not merged there yet and which makes it therefore unable to clear already typed datetime fields. This PR adds a small trash icon right to the pickers to make it able to clear the value inside like this:

add a 'clear' button beneath date and datetime pickers

---

packages/Webkul/API/Http/Controllers/Shop/CartController.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Shop/src/Http/Controllers/CartController.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php

Whenever a product cannot be added to cart, an exception is thrown. 
This PR offers logging with context, when that exception occurs, making it possible to retrieve and repair the faulty product.
Provoking an exception is not that easy at that point. In order to test my changes, you could 
- create a new downloadable product
- in Product/Type/Downloadable.php, copy line 165 and paste it two lines above, i.e. to the very beginning of function `prepareForCart()`
- try to add the Downloadable to cart
- wait for the message: "Downloadable links are missing for this product."
- browse storage/logs/laravel.log, at the end of the file there should be the same message again, along with the product and cart data
```
[2020-06-09 11:40:36] local.ERROR: Downloadable links are missing for this …
```

Add logging to exception thrown in cart

---

packages/Webkul/API/Http/Resources/Sales/Order.php
packages/Webkul/Sales/src/Models/OrderItem.php

in API Resource\Sales\Order.php and src\Models\OrderItem.php
this is a suggestion to expose some data about downloadable links. We need this data for some custom adjustments to our shop system. Thanks a lot !

feature: expose downloadable links 

---

packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/index.blade.php

1. When filtering on mobile, if you choose a filter combination that does not match any products the filters completely disappear, forcing you to use the back button to correct it. issue #3311  solved
2. When adding a new address for the customer, the validation on the city field is not allowing a hyphen. issue #3381 solved

fixed issue #3381 and #3311 

---

packages/Webkul/Product/src/Helpers/BundleOption.php
packages/Webkul/Product/src/Type/Bundle.php

**BUGS:**
Bundle inventory is never properly display in the front end. For either the bundle as a whole, or the individual bundle items.
**SOLUTIONS**:
1. Implemented haveSufficientQuantity() in the Type\Bundle class in order to determine if a bundle as a whole should be considered in stock.
2. Added in_stock and inventory properties to the bundle option product data so that inventory checks on individual products in the bundle can be performed on the front end. NOTE: I dod not have time to implement #2 into the front end, but at least the data is available now.

Added support for checking bundle inventory, and bundle product inventory.

---

packages/Webkul/CartRule/src/Helpers/CartRule.php
packages/Webkul/CartRule/src/Models/CartRule.php

There were 2 performance killers appearing when having a lot of cart-rules. In our live-system creating an order takes up to 50secs because `Helpers/CartRule` was not optimized for large numbers of cart-rules present in the database (>3000 entries). 
**Issues:**
* for each cart-rule the cart is fetched from the database
* for each cart-rule relations are fetched one by one
**Solution**
* the cart is only grabbed from the database at the very beginning since it cannot change during the cart-rule check process
* relations needed to check the cart-rule are loaded in before (eager loading) so that only 1 query is executed instead of 1 for each cart-rule
After these changes order creation is up to 10 times faster.

Improve performance when checking cart-rules

---

packages/Webkul/Product/src/Type/Bundle.php

**ENHANCEMENT:**
If a bundle has a $0 item, do not display the price in cart.

Hide $0 bundle option price in cart

---

packages/Webkul/BookingProduct/src/Type/Booking.php

If we pass additional data to a cart item, it's getting overwritten by this line. For example, if I want to use the API /api/checkout/cart/add/[some_product_id] and give it additional data it wont be saved. 
We have to array_merge the product_id, quantity and booking with the additional data that we passed to the item.

Booking Product Bug: Additional data wont be saved

---

packages/Webkul/Shop/src/Resources/views/products/index.blade.php

When filtering on mobile, if you choose a filter combination that does not match any products the filters completely disappear, forcing you to use the back button to correct it.
fixed issue #3311 in default theme

fixed issue #3311 in default theme

---

packages/Webkul/Admin/src/Listeners/Order.php

**BUGS:**
Issue Link: https://github.com/bagisto/bagisto/issues/3520
Admin will get email in their default email.

Admin should get mail according to admin's default locale issue fixed #3520

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3533
If limit is set to 0 then the default value will set i.e. **9**.
If options are **0,5,10,15,0** then on zero it will show products according to default limit.

Fixed products per page configuration is not working properly #3533

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3562
On adding DB Prefixes, the error will be shown. This is because when we use raw queries Laravel will not detect DB prefixes. So need to concatenate with environment variable i.e. '**env()**' or '**DB::getTablePrefix()**'.

DB Prefix Issue Fix #3562

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

As per the API Documentation, two cases needed i.e. url_key and name.
Previously on searching by url_key and name gives all results. (Issue Fixed)

Two Cases Added For API

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

I have fixed a small bug in the ProductDataGrid: If you have chosen no filter for channel and locale, the DataGrid did not show all products, but used fallbacks like "en" for the locale and "default" for the channel. 
You now should see all products for real in the DataGrid, as long as there is a name saved for the ProdutFlat for the specific locale/channel combination.

ProductDataGrid: Really show all products if it is wished

---

.env.example

As in the `services.php` google client's environment key is different as compared to the keys in `.env` file. So renamed that.

Some Changes In ENV

---

packages/Webkul/Core/src/Console/Commands/Install.php

Fixed a typo in functions => checkForEnvFile() : changed "aready" to "already".

Fixed a typo in checkForEnvFile()

---

config/repository.php
packages/Webkul/Core/src/Repositories/ChannelRepository.php
packages/Webkul/Core/src/Repositories/CoreConfigRepository.php
packages/Webkul/Core/src/Repositories/CountryRepository.php
packages/Webkul/Core/src/Repositories/CountryStateRepository.php
packages/Webkul/Core/src/Repositories/CurrencyRepository.php
packages/Webkul/Core/src/Repositories/ExchangeRateRepository.php
packages/Webkul/Core/src/Repositories/LocaleRepository.php
packages/Webkul/Core/src/Repositories/SliderRepository.php
packages/Webkul/Core/src/Repositories/SubscribersListRepository.php
packages/Webkul/Velocity/src/Repositories/CategoryRepository.php
packages/Webkul/Velocity/src/Repositories/ContentRepository.php
packages/Webkul/Velocity/src/Repositories/ContentTranslationRepository.php
packages/Webkul/Velocity/src/Repositories/OrderBrandsRepository.php
packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php
packages/Webkul/Velocity/src/Repositories/ReviewRepository.php

For some requests in Bagisto there are a lot of SQL queries being sent to the attached SQL server multiple times. 
Luckily, the prettus Repository Pattern that is being used in Bagisto thorough almost the whole application is being able to add a simple cache to leverage this problem. This PR adds the `CacheableInterface` to some of the major Repositories that Bagisto have implemented in order to reduce the amount of duplicated SQL queries sent to the server.

introduce CachableInterface for some Repositories (prettus)

---

packages/Webkul/Core/src/Console/Commands/Install.php

This PR fixes the cli installation on Plesk servers together with the following `.bashrc` file when running **bagisto:install**
```bash
alias php='/opt/plesk/php/7.4/bin/php'
alias composer='/opt/plesk/php/7.4/bin/php /usr/lib/plesk-9.0/composer.phar'
```
@jitendra-webkul  i will add the documentation for this on the devdocs.

Fixes for plesk cli install

---

config/products.php
packages/Webkul/Core/src/Helpers/Laravel5Helper.php
packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Downloadable.php
packages/Webkul/Product/src/Type/Simple.php
packages/Webkul/Product/src/Type/Virtual.php

With this PR you can, for example, set a product attribute to determine if a product is saleable or add your whatever-fancy-custom-logic to determine it.
Note: if your project already uses custom product types you need to adjust them to obey the new global rules !

ability to globally set a callable for isSaleable

---

packages/Webkul/Shop/src/Resources/assets/js/components/image-slider.vue

This PR is regarding issue #3987 and PR #3994
**BUG:**
>The issue was Appending the slider_path with the URL instead of redirecting it. 
>It was a minor mistake from my side and solved it.
Sorry for the inconvenience.

Fixed issue in image slider path

---

.github/workflows/ci.yml

Composer 2.0 has parallel downloads, so this package i.e. `hirak/prestissimo` not needed anymore.

Test Case Update

---

composer.json
composer.lock
config/app.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4212
**CHANGES:**
1. Removed `barryvdh/laravel-debugbar` from provider and composer's `dont-discover` key. Because this dependency is in the `require-dev` which means if someone is installing `composer install --no-dev` which automatically not discover the package. If someone is installing `composer install` then it is needed which automatically discovered and not needed in the provider.
2. `fzaninotto/faker` is used in the project which means it is a required dependency. So, moved to `require`,
Reference: https://github.com/laravel/framework/issues/14130#issuecomment-290883546

Fixed error uninstall developer dependencies going into production mode #4212

---

packages/Webkul/Core/src/Http/Controllers/ChannelController.php

When creating or updating channel in administration, validation will silently fail if you don't select Logo and Favicon image.
Both fields should have **nullable** validation rule too!

While creating/updating Channel, make logo an favicon nullable

---

packages/Webkul/Customer/src/Rules/VatIdRule.php

Currently when trying to save any european address with an empty VAT ID an exception is thrown because the VatValidator's [validate() method](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Customer/src/Rules/VatValidator.php#L53) requires a string argument, in the given case it is NULL though, leading to a php exception

Make VatIdRule accept empty strings as VAT id

---

app/Providers/AuthServiceProvider.php

While i am checking the error log, there is some minor error which is hitting silently.
On checking, came to know that this policy file is just for explanation and in Laravel 7.0 its also commented.
Ref: https://github.com/laravel/laravel/blob/672f626da1788a46bf6bc830d15725ee3ae668d8/app/Providers/AuthServiceProvider.php#L16
So, i just commented the line.

Minor Error Log Fixed

---

packages/Webkul/SocialLogin/src/Repositories/CustomerSocialAccountRepository.php

**BUGS:**
The returned email from Facebook is sometimes `null`. Bagisto tries to match the returned email from Facebook against the database, which would allow logins to accounts that have a `null` email which may not belong to the Facebook user trying to login, and therefore such user accounts might be breached.
This commit checks for `null` emails first, and returns a `null` customer instead of the first customer with a `null` email.

Fix security risk for null emails

---

packages/Webkul/Ui/src/DataGrid/DataGrid.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

Link 'models' itemsPerPage property with datagrid
I think this how it is supposed to work but the datagrid always defaults to 10 row. 
This simple change allows for models to have custom limits per page. E.g 
```php
<?php
namespace App\Webkul\Admin\DataGrids;
class ProductDataGrid extends \Webkul\Admin\DataGrids\ProductDataGrid
{
protected $itemsPerPage = 100;
}
```
In my service provider 
```php
$this->app->bind(
\Webkul\Admin\DataGrids\ProductDataGrid::class,
\App\Webkul\Admin\DataGrids\ProductDataGrid::class
);
```

Fix limit per page for datagrid

---

packages/Webkul/Admin/src/Listeners/Order.php

Starting from Laravel 5.2, as stated in documentation (https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0): 
> **Caching And Env**
> If you are using the config:cache command during deployment, you must make sure that you are only calling the env function from within your configuration files, and not from anywhere else in your application.
>
> If you are calling env from within your application, it is strongly recommended you add proper configuration values to your configuration files and call env from that location instead, allowing you to convert your env calls to config calls.
**BUG**
Fixing exception when NewAdminNotification is sent:
> Argument 1 passed to Webkul\Core\Eloquent\TranslatableModel::getTranslationByLocaleKey() must be of the type string, null given, called in …

Fixing wrong locale in Admin notifications

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

The PR implements the async await for default and velocity themes checkout pages to depress the chances of JS Callback hell problem.
Ref: https://blog.avenuecode.com/callback-hell-promises-and-async/await

Asynchronous callbacks for checkout page.

---

packages/Webkul/Marketing/src/Providers/MarketingServiceProvider.php

Removed resources path from the marketing service provider because there is no resources path. Due to which `php artisan view:cache` won't work.

Resources Path Removed From Marketing Provider

---

packages/Webkul/Ui/src/DataGrid/DataGrid.php

- When you are working on the `localhost` in data grids, it might be working. But when you try to use via IP or some other host it won't work because of checking the URL from `.env`.
- If `.env` not updated, then an exception will be occurred on all data grids with `massdelete`, `massupdate`, `delete`, `edit`, etc. methods.
- Added `url('\')` method for checking the case, so that it won't rely on `.env`.
PR Link: https://github.com/bagisto/bagisto/pull/4464

Dynamic url for route checking added for datagrids

---

packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php

When adding actions to a dataGrid the `condition` key can be specified. It can hold a function which currently doesn't receive any parameters.
When we pass the record here we allow developers to decide whether or not to show a action on a per-row (per-record) basis, so showing an action for some items, hiding it for others.

Allow to disable actions on a per-row (per-record) basis

---

packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Simple.php

When I tried to create a new product type then two properties i.e. `$skipAttributes` and `$additionalViews` also needed after extending with the `AbstractType` class which throws error.
- When creating new product types just need to extend the class and everything will be working fine.

Two properties moved to abstract class

---

packages/Webkul/API/Http/Resources/Catalog/Product.php
packages/Webkul/Customer/src/Helpers/Wishlist.php
packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

Link: https://github.com/bagisto/bagisto/issues/4597
As for the wishlist, `product_id` is needed while adding but for removing the `wishlist_id` is needed. So just enhanced the method as well. Which will give the wishlist object which can be used further for removing.

Fixed add a product to wishlist twice issue #4597

---

composer.json

Version 6.0.0 of the ar-php library fixed the issue of ignoring the punctuation marks when coming in the Arabic context for more robust segmentation using the "arIdentify" method. This will resolve the issue reported here by Fahad Khan:
https://github.com/bagisto/bagisto/pull/4462#issuecomment-765555768

Use the latest version of ar-php library

---

packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
packages/Webkul/Paypal/src/Payment/Paypal.php

**BUGS:**
PayPal SmartButton don't work if the Billing Adress phone have a non-number character. Also if some "value" of type currency have more than two decimal places. Bagisto just shows "error: expected an order id to be passed" alert.

FIX: currencies "value"s and "phone" fields formated for API

---

packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php

Link: https://github.com/bagisto/bagisto/issues/4727

Fixed error `addToCartHtml` which is not defined on the compare page #4727

---

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php

In the dashboard, top-selling products are shown from the order item's table. But when a product is deleted then this will cause an exception as no image is found on the associated product because the product instance is not available.
Added static no image placeholder.

Some Exception Handled On Dashboard Page

---

packages/Webkul/Core/src/Traits/Sanitizer.php
packages/Webkul/Product/src/Repositories/SearchRepository.php
packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php

SVG Sanitizer Enhanced - SA3

---

composer.json
composer.lock

- `bagisto/bagisto-package-generator` is a development dependency so removing it from the main require key because of this creating problem when updating the Bagisto version in Bagisto Standard.
- `fzaninotto/faker` is abandoned so replacing with `fakerphp/faker`.
- `phpunit/php-token-stream` is abandoned so  updating `phpunit/phpunit` to 9.5.0.
- `paypal/http` is also abondoned but this is depend on the dependencies. If latest version of sdk is released this warning will automatically remove.

Abandoned package and dependency updated

---

storage/app/public/.gitignore

Just notices that the public folder is missing which creating the problem with storage linking. Because the linking path is not proper.

Added Missing Public Folder

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/review.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-invoice.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-refund.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel-admin.blade.php
packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/review.blade.php

This pull requests fixes #4804 
- Added missing city field to order templates.
- Added missing city field to **Velocity** checkout order summary.
- Added missing city field to **Shop** checkout order summary.
- Create a new order
- Verify that your city is being displayed in the order summary.
- Verify that your city is being displayed in the order confirmation mail.

fixed #4804

---

packages/Webkul/Product/src/Repositories/ProductImageRepository.php
packages/Webkul/Product/src/Type/Configurable.php

Link: https://github.com/bagisto/bagisto/issues/4901
- Generated required fields that are needed by variants in the backend.
- There is some bug in master, when trying to create a variant on the edit page then an exception occurs and this is coming from the upload image method. To overcome this I just enhanced the `ProductImageRepository` class.
- Generate configurable products with variants.
- Then try to save the variant without doing anything.

Configurable product required filled generated and image repository enhanced #4901

---

packages/Webkul/Product/src/Models/ProductAttributeValue.php

Link: https://github.com/bagisto/bagisto/issues/4985
- When calling the relationship, this proxy class is not found in the model, which caused the error, which means it never used in a project.
https://github.com/bagisto/bagisto/blob/8858ed64ffdb07c70652549a8b467b57cf5757eb/packages/Webkul/Product/src/Models/ProductAttributeValue.php#L7
- So rather creating a migration, i choosed to remove the method.

Removed Channel Relationship From The ProductAttributeValues Model #4985

---

packages/Webkul/Core/src/Console/Commands/Install.php

- Removed installer folder when GUI installation completed.
- Just make a fresh install and check whether the installer directory was deleted or not.

Removed installer folder when GUI installation completed

---

packages/Webkul/Sales/src/Models/ShipmentItem.php

Link: https://github.com/bagisto/bagisto/issues/4993
- `parent_id` is not available in the table, so removed relationship as it hasn't been used.

Removed Child Relationship For Shipment Item #4993

---

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php

Link: https://github.com/bagisto/bagisto/issues/5088
- Removed the invoice button when the payment method is PayPal Standard.
- Not added case in the `canInvoice` method because the request is also coming from the IPN also which will result in false.
- So added case in the view page and create method. If somehow it is forced from the Postman will result in 500 in production.
- Place an order from the PayPal standard option and check for the invoice button on the index page. It should not be available.

Removed the invoice button when the payment method is PayPal Standard #5088

---

packages/Webkul/Sales/src/Generators/Sequencer.php

It was adding the 0s till the order_number_length and adding the (lastId+1). For example if order_number_length is set to 5 and my last id it 101, then next order increment id will be "00000102".
I have done the fix to generate order increment id like "00102".
By setting the order number length in config and then placing any order. After that see the order_increment_id.

Correct use of Order number length setting.

---

packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue

#5123, #5118
Removed non-compliant condition in orders initialization because that property is not in the order response
Just enter the orders section in the administrative panel.

Removed non-compliant condition in orders initialization

---

tests/unit/Tax/Helpers/TaxCest.php

- The very small difference was ignored in the test case.
- Still, the test case will fail, if the source is too long.

Very Small Difference Avoided In Test Case

---

packages/Webkul/API/Http/Controllers/Shop/OrderController.php
packages/Webkul/API/Http/routes.php
packages/Webkul/Shop/src/Resources/lang/en/app.php

Link: https://github.com/bagisto/bagisto/issues/5178
- Added API for a customer.
- Hit this `POST api/order/{id}/cancel?token=true`.

Cancel order API for customer implemented #5178

---

packages/Webkul/Product/src/Http/Controllers/ProductController.php

Fixes #5191 
When a checkbox attribute is not required, all checkboxes can successfully be unchecked.
Tested changes locally on my machine.

Allow unchecking all checkboxes in an attribute

---

packages/Webkul/Checkout/src/Http/Middleware/CartMerger.php

Link: https://github.com/bagisto/bagisto/issues/5179
- Currently, instead of merging I just removed the current buy now cart because on merging some issues happen on the live instances. Need to check this.
- Add two-three items to the cart.
- Then buy now any product.
- Then navigate away from the checkout.
- Old cart items should be there.

Fixed cart items which get increased when navigating away from the buy now functionality #5179

---

packages/Webkul/Product/src/Models/ProductBundleOptionProduct.php

Changed class name in bundle option relationship. Because There is no ProductBundleProductProxy class. It is related to ProductBundleOptionProxy class.
There is no issue open related to this at the time of pull request.
There was a mistake referencing class name in the relationship method of bundle_option.

Fixed class name

---

packages/Webkul/Shipping/src/Carriers/AbstractShipping.php

Hi, config key of description in abstract shipping method has a typo so when you want to get description with getter method, it returns null.

typo fixed

---

packages/Webkul/Admin/src/Http/Controllers/ExportController.php

On the catalogue products page if you try to download the list of csv or xls an error is generated because no properties are declared in the constructor.
I fixed the problem by adding the solver App::make

Fix download catalog/products

---

packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php

Link: https://github.com/bagisto/bagisto/issues/5501
- Maybe for other countries states can use space alphabets and numbers (rarely). I am not sure but I just reverted to the previous one.

Address State Fixed #5501

---

tests/unit/Category/CategoryCest.php

#5534
Fixes CategoryCest unit test relying on en app_locale

fix CategoryCest unit test relying on app_locale=en

---

packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php

Data grid price filter when using sum wasn't working with where clause.
So, updated the price data type with having clause.
This way it's working fine for both prices whether it's the sum of the price or the simple price.

data grid sum Priceissue

---

packages/Webkul/Core/src/Core.php

The chart on admin dashboard is not displayed properly when viewing data long period such as 1 year and short period such as in month
Choose long time period in admin dashboard. Eg: 2021-06-01 to 2022-02-24
Choose short time period in admin dashboard. Eg: 2022-02-01 to 2022-02-24

The chart on admin dashboard is not displayed properly

---

packages/Webkul/Product/src/Http/Controllers/ProductController.php
packages/Webkul/Product/src/Http/Controllers/ReviewController.php
packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
packages/Webkul/Shop/src/Http/Controllers/ProductController.php
packages/Webkul/Velocity/src/Helpers/Helper.php

Refactoring of some conditions to improve readability. 
In `! $data['massaction-type'] == 'update' ` , the ! operator is applied first, leading to `$data['massaction-type']` to become a boolean (most probably true), then 'update' is also type-juggled into a boolean (true, this time) and finally, both are compared. In fact, when $data['massaction-type'] = 'update' the condition fails, while when $data['massaction-type'] == '' (empty string), it works.  
In `! count($filterAttributes) > 0`, when count() is positive (array filled), it is turned into a false boolean, then a 0, which makes the condition fail. This is replaced with a call to `empty()` 
In `! strpos($priceHTML, 'sticker sale') > 0` when 'sticker sale' is found in the $priceHTML variable, strpos() returns a postive value …

refactored conditions with simpler terms

---

packages/Webkul/Product/src/Type/AbstractType.php

resolves #6501
#6501
Uses rounding precision of 4 to store cart item prices.
This prevents rounding errors after applying taxes.
- Create a product with the price 30.2550 € (excluding VAT)
- set tax rate to 19%
- add product to cart
- cart item displays 36.00 € not 36.01 € (as before the patch)

Uses rounding precision of 4 to store cart item prices

---

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php

https://github.com/bagisto/bagisto/issues/6514, https://github.com/bagisto/bagisto/issues/6509
While searching the product from category edit page it is redirecting it to list page.
so admin user not able to search product here.
Search product from category edit page it will redirect to category list page instead of showing result.

Redirection issue during product search from category edit page.

---

app/Http/Kernel.php

Added `HandleCors` to  global middleware stack.
this will fix the CORS error when sending requests to Bagisto Web API routes and make use of `config/cors.php` file.

Added `HandleCors` to  global middleware stack.

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php

#6556
Numeric validation added at the time of creating or updating cart rule for uses_per_coupon & uses_per_customer fields.

Cart rule numeric validation for uses_per_coupon & uses_per_customer.

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist.blade.php

#6441
There was an issue if we copy a already generated link then some extra string get add up with this so it always says page not found if somebody trying to access it.

Wish-list sharing link issue resolved #6441

---

packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php

I just fixed the issue, when the admin wanted to set the usage limit NOT per customer.
- Create cart rule with coupon, do not set usage per customer and try to apply cart rule on checkout

Fixed issue with coupon usage limit

---

packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php

Error: admin.js:2 ReferenceError: showModal is not defined
fix add Group in Edit family - it was missing $root

Fix ShowModal Call

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

#6770 
As per pointed issue, Inactive & Out of Stock products also showing in search products while creating group & bundle products,  Now After fixed this issue, Out of stock & Inactive products will not searched while creating group & bundle products.
1. Log in as an admin.
2. Click on products inside the catalog tab.
3. Create a bundle product.
4. Try to add any inactive or out-of-stock product to bundle items.
5. You will not see inactive & out of stock products in searched listing

Issue #6770 Fixed

---

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php

The tables on order view page in admin are not responsive and therefore do not visible correctly on mobiles. 
Try opening some order on mobiles in admin panel and tab on Invoices (for example) tab.
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/194717858-d533a767-2262-45a7-bdf3-9504e584d05f.png) | ![image](https://user-images.githubusercontent.com/4408379/194717880-53ec6f19-2ca6-4f3f-8203-78584598e804.png) |

Make tables responsive on view order page

---

packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/subscribers/edit.blade.php

All other similar admin edit pages have a mandatory space around its content.
Try to open a page with editing any newsletter subscriber:
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/195079765-91eef774-a7e1-434d-acf3-9b83667b311d.png) | ![image](https://user-images.githubusercontent.com/4408379/195079829-aa2ddba3-5a05-4337-b7d7-0700efbca646.png) |

Add missing space around content on subscriber page

---

packages/Webkul/Admin/src/Http/Controllers/DashboardController.php

#7103 
In this PR, I eager loaded some relations for better performance, and in a production server, we can reduce from 110 queries in the dashboard to 30!

Performance - Dashboard Controller

---

packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue

#7449
->By default, the placeholder value should be selected for the filter dropdown.

issue fixed #7449

---

packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php

#7426 
-> We can use (-) icon in Coupon Code Column instead of blank column.
-> for this changes in cartrule data grid file check condition for coupon code value.
-> find screen shot here  https://prnt.sc/QTU_rSKDe99Y

issue #7426 fixed

---

packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php

#8683 
For fixing #8683  Set existing default_address bit on update address, (prevent to set default address 0) 
Customer must be logged in.
Customer should have at least one added address and set it as default.
Go to 'Shop' and login as User
Edit the default address and save it inside the Accounts/Addresses

Fixed #8683

---

packages/Webkul/Admin/src/Mail/Order/CreatedNotification.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/bn/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/emails/orders/created.blade.php

#8696 
- Upon placing an order, both the customer and admin receive confirmation email.
- The placeholder ":customer_name" has been replaced with ":admin_name" and updated in all languages.
- Navigate to the admin panel, then access the "Configuration" section, proceed to "Emails Settings," and configure the "Admin Email" and "Admin Name." 
- After completing this step, place an order and receive emails accordingly at both the customer's and admin's email addresses.

Fixed 8696

---

packages/Webkul/Sales/src/Generators/Sequencer.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php

#8700 
Changes were made to the sequencer. Now, if the length, prefix, and suffix are set from the admin panel, they will be added; otherwise, the order ID is displayed normally. Additionally, the order ID is correctly displayed on the order view page, with the prefix, suffix, and length applied.
1. Navigate to 'Admin > Configuration > Sales > Order Settings.' and adjust the settings accordingly.
2. Similarly, visit 'Admin > Configuration > Sales > Invoice Settings' and adjust the settings accordingly.
3. After making these changes, create an order and generate an invoice.

Fixed - #8700

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

Not able to remove the attribute's option while editing the related attribute from the admin panel.
If you want to add some attribute options and want to remove any option from the related attribute, then not able to remove the option.
Not able to remove the attribute's option while editing the related attribute from the admin panel.

[Fixed: #8800]

---

packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

#8809
Draggable functionality is not working for Attribute Options at the Admin end.
https://prnt.sc/S1E7FlfWFGpj
Go to 'Admin Panel'
Click on 'Edit Attribute & rearrange the order of options'
Save with changed order
See error
If you check by editing the same attribute, It will not reflect.
Fixed.

[Fixed: #8809]

---

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/datagrid/index.blade.php

- For modules, certain custom filters need parameters to change the query builder.
~~~php
<x-admin::datagrid
:src="route('admin.settings.exchange_rates.index')"
ref="datagrid"
>
this.$refs.datagrid.get({
param1: 'value1',
param2: 'value2',
});
~~~

feat: extra params added which gives ability to add some extra request in backend for changing query

---

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php

500 api response when there is no item in cart on cart page.
When there is no item in cart and go to checkout/cart path, api response is 500, and also display cross sell loading effect.
1. Go to checkout/cart path without adding an item to cart.

fix(api-shop-cart): handle empty cart item with try catch

---

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php

Request: GET
Url: domain/admin/customers/customers/search?query=test
Response
Status Code: 500
error message:  "SQLSTATE[42S22]: Column not found: 1054 Unknown column '__msh__first_name' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `__msh__customers` where `email` like %test% or CONCAT(__msh__first_name, \" \", __msh__last_name) like %test%)",

Fix DB::getTablePrefix() issue

---

packages/Webkul/Product/src/Helpers/SEO.php

Now the "weight" is saved as "image" which is wrong.
There is a bug in SEO.php where the "weight" is written as "image", so in this PR i have fixed that!

Update SEO.php to fix the "weight" paramenter

---

packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php

Two new events have been added to the mobile view of the shop layout. These events are triggered before and after the category view is rendered. This could assist in adding custom functionality or tracking user interaction with this section.
There is no way no in mobile drawer to add links before or after the categories.
If you need to add a new link, like "Blog" for example, you can do that on Desktop view, but in mobile view, there is no way without changing the Theme files to add links before or after the categories. 
By adding these `view_render_event('...')` before and after `<v-mobile-category>` you can now add your own menus, or some other packages can add their own.
You can add an Event listener that inserts the link there like these example:
```php …
```

Feature: Add events before and after mobile category view

---

packages/Webkul/Core/src/Providers/VisitorServiceProvider.php

This commit resolves the issue with the incompatible method signature in the `Webkul\Core\Providers\VisitorServiceProvider` class. The `boot` and `register` methods in this class have been updated to include the `void` return type, ensuring compatibility with the parent class `Shetabit\Visitor\Provider\VisitorServiceProvider`.

Fix incompatible method signature in VisitorServiceProvider

---

packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
packages/Webkul/Paypal/src/Http/Controllers/StandardController.php
packages/Webkul/Shop/src/Http/Controllers/API/OnepageController.php
packages/Webkul/Shop/src/Http/Controllers/OnepageController.php

Serialization of 'Closure' is not allowed
#9609
Checkout OnePage controller is storing unnecessary at session the full order object that leads to an error on redirections because of processing the Request object (loading/storing cookies and session).  
New installation (master) with fake data and simple checkout.

Serialization of Closure on checkout end

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/controls.blade.php

Fixed image type attribute exception issue
1. Create an image type attribute.
2. Go to the product edit page.
3. Check the image type attribute field broken image appearing.
4. Click on the image it gives an exception

Fixed image type attribute exception issue

---

packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/address.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/create/recent-order-items.blade.php

Whenever we save the address and hit the proceed button then there is issue appear that default_address can not be null (fixed).

issue: default_address issue fixed.

---

packages/Webkul/Admin/src/Resources/views/emails/layout.blade.php

The logo URL is not correct, and the image is not displayed in the admin emails.  In the admin layouts where the logo is shown, it's displayed using `{{ Storage::url($logo) }}`

Update admin email layout.blade.php

---

packages/Webkul/Installer/src/Console/Commands/Installer.php

#9946 
This pull request enhances the updateEnvChoice method by adding an optional parameter, `$useSuggest`.  
When this parameter is set to **true**, the method will use the **suggest** function instead of **select** for user prompts. 
This enhancement provides a more efficient way for users to find and select options, particularly useful for long lists like timezones.
Video for reference:
[![Watch the video](https://img.youtube.com/vi/0uSZ68Cw08s/default.jpg)](https://youtube.com/watch?v=0uSZ68Cw08s)
run `php artisan bagisto:install` and select your timezone

Improved updateEnvChoice to support suggest functionality

---

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
packages/Webkul/DataGrid/src/ColumnTypes/Aggregate.php
packages/Webkul/DataGrid/src/ColumnTypes/Boolean.php
packages/Webkul/DataGrid/src/ColumnTypes/Date.php
packages/Webkul/DataGrid/src/ColumnTypes/Datetime.php
packages/Webkul/DataGrid/src/ColumnTypes/Decimal.php
packages/Webkul/DataGrid/src/ColumnTypes/Integer.php
packages/Webkul/DataGrid/src/ColumnTypes/Text.php
packages/Webkul/DataGrid/src/Enums/ColumnTypeEnum.php
packages/Webkul/DataGrid/src/Exceptions/InvalidColumnExpressionException.php

This guide explains how to use the enhanced filtering capabilities for Decimal and Integer column types in your data grid.
The Decimal and Integer column types support various filtering operations, including:
- Exact match
- Greater than / Less than
- Greater than or equal to / Less than or equal to
- Range queries
- Exact match: `"10.5"`
- Greater than: `">10.5"`
- Less than: `"<20.75"`
- Greater than or equal to: `">=15.0"`
- Less than or equal to: `"<=25.5"`
- Range: `"10.5-20.75"`
- Exact match: `"10"`
- Greater than: `">10"`
- Less than: `"<20"`
- Greater than or equal to: `">=15"`
- Less than or equal to: `"<=25"`
- Range: `"10-20"`

feat: integer and decimal type enhanced

---

packages/Webkul/Core/src/Eloquent/Repository.php

#10027 
Parameter usage fixed
Use any findOneByField() method on any repository and provide $columns param.

$columns variable passed down to findByField()

---

packages/Webkul/Sales/src/Repositories/OrderRepository.php

This issue happens when Bagisto is retrying to create orders. The rolled-back order is still being returned **after** the latest created order because lacking of a return for `createOrderIfNotThenRetry` recalling. Instead, the application should return the latest created order and exist the recursive call.
Issue can be reproduced by making a fail order creation query, then on the retry, make it success. 
We can test this by placing an order as usual.

adding return to recursive call

---

packages/Webkul/Shop/src/Http/Middleware/Locale.php

When a locale is installed but not activated on a channel (as Polish for example), the locale is even accessible in the frontend with the url: url/?locale=pl where url have to be replaced by your current url
- To test this, you have to edit the channel you want to test (Settings > Channels and then edit it). You must have at least 2 locales installed (on the picture we have installed five)
- Deactivate one locale as on the picture below (here we have deactivated Polish => pl)
- Once this is done, go on your frontend and add /?locale=pl at the end of the url as below
The locale has to remain unchanged instead of being in polish

[Bug] Locales intalled but not activated can be accessible in the front

---

composer.json

The installation of a module doesn't need anymore to update manually the root config/app.php file.
Imagine we want to create a module Vendor/Package. We then had to add the file PackageServiceProvider in the config/app.php.
Now, we don't have do do it anymore.
- Create a package with the command: php artisan package:make VendorName/PackageName for example. Then you will get in your packages folder:
- Now, create a composer.json file in your package (packages/VendorName/PackageName/composer.json) as following:
You can then install the package with the command: composer require vendorname/packagename
Or uninstall it with the command: composer remove vendorname/packagename

Improve the module development

---

packages/Webkul/Installer/src/Console/Commands/Installer.php

[https://github.com/bagisto/bagisto/pull/10148](url)
In the installer file (packages\Webkul\Installer\src\Console\Commands\Installer.php), a static /admin url path is implemented despite the availability of environment variable APP_ADMIN_URL, which is not being used to show the admin url after installation.

Use of APP_ADMIN_URL env variable in installer for admin URL

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php

In desktop and tablet view, the prices are shown as selected in the admin, but in the mobile, the prices were just shown without taxes. In this PR I fix that problem.
Check in mobile that the prices don't react to the admin, display, with / without /both taxes. It only shows one version.
In tablet / desktop, this problem does not exist.

Fix pricing on Cart mobile view.

---

packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php

Fixed Category Datagrid 
When we add a category in multiple locales data doesn't show locale-wise in the data grid 
Go to the category section in the admin
Add a category in multiple locales
Check the data grid

Fixed Category Datagrid 

---

docker-compose.yml

Link: https://github.com/bagisto/bagisto/issues/9962
This guide walks you through the process of setting up Bagisto using Laravel Sail.
To install Composer dependencies on a fresh clone of your project, the default PHP version is 8.3. However, you may switch to a Bagisto-supported PHP version by using one of the following:
- `laravelsail/php81-composer:latest`
- `laravelsail/php82-composer:latest`
- `laravelsail/php83-composer:latest`
When changing the PHP version, remember to update the Dockerfile context in the `docker-compose` file accordingly. For more details, refer to the [Laravel Sail documentation on PHP versions](https://laravel.com/docs/11.x/sail#sail-php-versions).
```bash
docker run --rm \
-u "$(id -u):$(id -g)" \
-v "$(pwd):/var/www/html" \
-w /var/www/html \ …
```

feat: laravel sail support

---

packages/Webkul/Admin/src/Config/system.php

#10370 
There is only `numeric` validation rule applied on the invoice number length in configuration file. So, I added general extra rules to prevent user from entering unexpected length. I checked the `generate` method that is used `sprintf` function to specify zero padding with user provided length. The `sprintf` function thrown **ValueError** exception if the length is less than zero or bigger than [PHP_INT_MAX](https://www.php.net/manual/en/reserved.constants.php#constant.php-int-max). https://github.com/bagisto/bagisto/blob/28ed27ed72a629c51027a289ecf58e00a56c4f52/packages/Webkul/Sales/src/Generators/Sequencer.php#L109-L115

add proper validation rule

---

packages/Webkul/Admin/src/Http/Controllers/Settings/RoleController.php
packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php

#10388 
There is no validation for permissions value on store method. So, I added appropriate rules to validate the field. Also, it would be better to use Form Request validation to customize error message when the permissions are not selected and then submit the form.
https://github.com/user-attachments/assets/b178a7dc-b40b-49c5-8255-2476ddebcdac

add permissions array validation rule on store method

---

packages/Webkul/DataGrid/src/ColumnTypes/Date.php

Date range queries of DataGrid are generating not-right date strings for pre-defined date ranges.
Predefined ranges are defined in `packages/Webkul/DataGrid/src/Enums/DateRangeOptionEnum.php`. In it's `options()` method, the default date format is 'Y-m-d H:i:s'.  So it's generating a string like '2025-02-01 00:00:00'. 
Then again, in `packages/Webkul/DataGrid/src/ColumnTypes/Date.php`, the `processFilter()` method is adding ' 00:00:01' and ' 23:59:59' for all from-to dates. As a result, it's becoming something like `(`date` between '2025-02-01 00:00:00 00:00:01' and '2025-02-28 23:59:59 23:59:59')`.
Checking if the date string has time fragment (by checking space). Adding time fragment only if it's not present. 
Actually, time fragment is not there if custom date range is used.

Fixed date filter issues with predefined date ranges

---

packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php

Depending on the order in which filters were applied, previously set filters were sometimes reset to their default values.
1. Set the default sorting order and display mode (grid/list) in the admin panel.
2. Go to the shop and change either the display mode OR the sort order of the products - test them one at a time. 
3. One of the settings will not work as expected — it will always revert to the default value.
4. If you're unable to reproduce the issue, check the pull request commit for more details — the bug is quite obvious, and reviewing the changes should help you understand how to replicate it.

Bug fix of products filtering

---

packages/Webkul/CartRule/src/Helpers/CartRule.php
packages/Webkul/Checkout/src/Cart.php

Alternative approach to fix [#10720](https://github.com/bagisto/bagisto/pull/10720)
This is a better approach, as it avoids refetching the cart object every time the applied cart rules are updated. In this way, the original bug does not occur. Pest test cases are passing successfully. This PR reverts the changes made in [#10720](https://github.com/bagisto/bagisto/pull/10720) and makes necessary other changes.
- [x ] Target Branch: 2.2

refactor: remove unused CartRepository dependency and streamline cart updates

---

packages/Webkul/DataGrid/src/ColumnTypes/Date.php
packages/Webkul/DataGrid/src/ColumnTypes/Datetime.php

- Fix datagrid not filtering as expected when user select predefined date range.

Fix datagrid missing query when selecting predefined date range filter

---

packages/Webkul/Core/src/Core.php

We use "d M Y" date format in multiple places, but the month ("M") was always displayed in English. This PR fixes the issue by using Carbon's translatedFormat method.

Format dates with translations

---

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php

Empty search results caused SQL error related to sort by an empty array:
```
.... order by FIELD(product_flat.product_id, ) asc)
```
Full error:
```
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') asc ' at line 1 (Connection: mysql, SQL: select distinct `product_flat`.`locale`, `product_flat`.`channel`, `product_images`.`path` as `base_image`, `pc`.`category_id`, `ct`.`name` as `category_name`, `product_flat`.`product_id`, `product_flat`.`sku`, `product_flat`.`name`, `product_flat`.`type`, `product_flat`.`status`, `product_flat`.`price`, `product_flat`.`url_key`, `product_flat`.`visible_individually`, `af`.`name` as `attribute_family`, SUM(DISTINCT …
```

Bug fix - Admin ProductDataGrid.php

---

packages/Webkul/Admin/src/DataGrids/Marketing/SearchSEO/SitemapDataGrid.php

Fix sitemap URLs when default storage disk differs from public

Always use public disk for sitemap url

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/address/form.blade.php

Phone number validation should allow "+" sign at the beginning. There is already custom "phone" rule - why we don't use it?

Change phone validation rule to 'required|phone'

---

packages/Webkul/Admin/src/Resources/lang/ca/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/BookingProduct/src/Helpers/Booking.php
packages/Webkul/Shop/src/Http/Controllers/Customer/GDPRController.php
packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php
packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php

Fixes #10883
`php artisan route:list` was failing because `GDPRController` called `abort(404)` in its constructor when GDPR is disabled. 
Artisan instantiates controllers while resolving routes, so the HTTP abort surfaced in the CLI.
**Change (minimal):**
Skip the abort when running in console:
```php
if (! core()->getConfigData('general.gdpr.settings.enabled') && ! app()->runningInConsole()) {
abort(404);
}

fix: skip 404 in CLI so artisan route:list works (#10883)

---

packages/Webkul/Product/src/Type/Bundle.php

An exception occurs when a bundle product is added to the cart and exceeds the second child's inventory.
Create a bundle product with 2 children.
Set default quantities to 20 for both.
Set the first product inventory to 40 from the simple product edit page
Set the second product inventory to 20 from the simple product edit page
Add bundle product to cart.
Again, click the "Add to cart' button
array_merge(): Argument #1 must be of type array, string given

Handled string exception when bundle product add to cart

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php

#10898
Resolves issue #10898 where an unnecessary validation error occurred on the price field during mass updates for configurable product variants, despite the field not being mandatory. The validation check is now skipped if the field is left empty.

Fix(mass-update): Prevent validation error on empty price field

---

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php

#10982 
- Destroy the correct editor before reinitializing the tinymce editor
- Now after changing theme when multiple tinymce editors are present on the same page the editors will still work as editors instead of reverting to plain textarea input.

fix(admin): ensure TinyMCE editors are reinitialized correctly after theme change
