bagisto/bagisto

- README.md
Just a tiny update to the Readme - Vuejs is not a node.js framework as was stated. It doesn't rely on node at all, I opted to use the description the Vue developers use on their homepage / github of `Progressive JavaScript Framework` in my edit :)
> Vue is not a node.js framework

- packages/Webkul/Category/src/Repositories/CategoryRepository.php
Improved some coding issues and styles
> code improvement

- packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
- packages/Webkul/Admin/src/DataGrids/OrderShipmentsDataGrid.php
Customer grid, orders grid and orders shipments grid full name now being displayed.
> Order, order shipments full name fixes in datagrid

- packages/Webkul/Admin/src/DataGrids/AttributeDataGrid.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
- packages/Webkul/Shop/src/Resources/assets/sass/app.scss
Critical bugs in cart and mini cart style fix.
> cart bug fixes and small css fix

- packages/Webkul/Checkout/src/Cart.php
flash notification for critical bug fixed
> Cart flash message fixed

- README.md
[Updated: README.md file updated.]
> [Updated: README.md file updated.]

- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
> Fixed issue 513

- packages/Webkul/Customer/src/Http/Controllers/SessionController.php
**url.intended** key was missing in session
> Fixed issue #143

- packages/Webkul/Ui/src/Resources/lang/en/app.php
- packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
Confirm box implementation on datagrid actions.
> Confirm box implemented for datagrid actions

- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
> sync with base master

- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
email names are same for signup form and footer email address field. so i changed footer email addess to subscriber_email @jitendra-webkul
> subscriber_email changes

- packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php
change email subscriber_email as footer field assign to this field. @jitendra-webkul #660
> subscriber_email email changes

- packages/Webkul/Admin/src/Http/Controllers/ExportController.php
https://youtu.be/IdR_i779Bug
You may watch this video about this refactor
> Flattened the code

- packages/Webkul/Product/src/Http/Controllers/ProductController.php
Product mass deletion was causing this issue
> fixed issue #765

- packages/Webkul/Attribute/src/Models/Attribute.php
- packages/Webkul/Attribute/src/Models/AttributeOption.php
- packages/Webkul/Category/src/Models/Category.php
Eager load translations for models
> Issue #803 fixed

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rule/create.blade.php
- packages/Webkul/Discount/src/Http/Controllers/CartRuleController.php
- packages/Webkul/Shop/src/Resources/views/checkout/total/summary.blade.php
> Revert "Revert "Fixed issue with order summary rendering on cart page""

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Discount/src/Database/Migrations/2019_05_13_024326_create_cart_rule_table.php
- packages/Webkul/Discount/src/Helpers/Discount.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
> Revert "Revert "Development""

- packages/Webkul/Discount/src/Helpers/Discount.php
- packages/Webkul/Product/src/Helpers/ProductImage.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
Added Flash message for error & issue 1051.
> flash message for discount & error

- packages/Webkul/Discount/src/Actions/BuyAGetB.php
- packages/Webkul/Discount/src/Actions/FixedAmount.php
- packages/Webkul/Discount/src/Actions/PercentOfProduct.php
Discount is not applying according to quantity of item.
> quantity issue in discount

- public/installer/install.php
Disable strict mode in installer.
> disable strict mode in installer

- packages/Webkul/Admin/src/Resources/views/layouts/nav-left.blade.php
> icon issue in admin dashboard

- packages/Webkul/Discount/src/Http/Controllers/CartRuleController.php
- packages/Webkul/Discount/src/Http/Controllers/CatalogRuleController.php
Change  info to success for message.
> issue #1086

- packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Change document.onreadystatechange function with $(document).ready() for opera browser.
> issue #951

- packages/Webkul/Admin/src/Http/Controllers/ExportController.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
Added product export on product's grid in Admin panel
> Product export now added

- README.md
> Rework and fix anchors in README

- packages/Webkul/Theme/src/ViewRenderEventManager.php
https://github.com/bagisto/bagisto/issues/1280
> fix Event get params

- README.md
- packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/CMS/src/Http/Controllers/Admin/PageController.php
- packages/Webkul/Discount/src/Helpers/Catalog/Apply.php
- packages/Webkul/Discount/src/Helpers/Catalog/ConvertXToProductId.php
- packages/Webkul/Discount/src/Repositories/CatalogRuleProductsRepository.php
Fixed issue with CMS pages datagrid columns with channel and locales columns got interchanged.
> Fixed channel locale issue in cms datagrid

- packages/Webkul/Theme/src/ViewRenderEventManager.php
send data view
Ex:
```
public function addDownloadble(ViewRenderEventManager $ViewRenderEventManager)
{
$view_render = view('KarimQaderi_Dowloadble::hello')->with([
'foo'=>'bar'
])->render();
$ViewRenderEventManager->addTemplate($view_render);
}
```
> ViewRenderEventManager send string template

- packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/CMS/src/Database/Seeders/CMSPagesTableSeeder.php
- packages/Webkul/CMS/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/Core/src/Config/concord.php
- packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
- packages/Webkul/Core/src/Repositories/SliderRepository.php
> Added entry for CMS in core's concord.php

- composer.json
fixed this error again after my previous fix was overwritten during the PR: [Changes in core repository made](https://github.com/bagisto/bagisto/pull/1390)
> fixed #1367

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rule/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rule/edit.blade.php
- packages/Webkul/Discount/src/Helpers/Cart/Discount.php
- packages/Webkul/Discount/src/Helpers/Catalog/ConvertXToProductId.php
- packages/Webkul/Discount/src/Helpers/Catalog/Sale.php
- packages/Webkul/Discount/src/Http/Controllers/CatalogRuleController.php
- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
> Fixed translation issue in catalog rule delete notification

- public/installer/Admin.php
- public/installer/Email.php
- public/installer/EmailConfig.php
- public/installer/Finish.php
- public/installer/Views/requirements.blade.php
- public/installer/index.php
This adds a form in the web installer to configure the mail settings.
> Feature: mail configuration in web installer

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
- packages/Webkul/Customer/src/Models/Customer.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
Footer bottom's visibility made optional using configuration.
> Fixed issue #1532

- packages/Webkul/Shop/src/Resources/lang/ar/app.php
Correct Arabic translation errors.
> Update Arabic localization text.

- app/Console/Commands/GenerateProducts.php
- packages/Webkul/Core/src/Database/Migrations/2019_10_03_105451_change_rate_column_in_currency_exchange_rates_table.php
Lower decimal precision for column **rates** column is now changed to **decimal 24, 12**.
> Fixed decimal precision issue for currency_exchange_rates table's rate column.

- .env.example
- .github/ISSUE_TEMPLATE/3_Support_question.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- packages/Webkul/Product/src/Repositories/ProductRepository.php
> Release version updated & added pull request template.

- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
> Fixed checkout issue

- packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/refunds/view.blade.php
- packages/Webkul/Sales/src/Models/RefundItem.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php
Updated refund with new product types
> Updated refund with new product types

- packages/Webkul/Sales/src/Repositories/RefundRepository.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-refund.blade.php
Updated refund for new product types
> Updated refund for new product types

- .github/FUNDING.yml
> Added sponsor button

- packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
> Fixed issue #1563

- packages/Webkul/API/Http/Controllers/Shop/AddressController.php
- packages/Webkul/API/Http/routes.php
> Issue #1540

- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
Fix the problem with layered navigation on pages
> Fix for issue #1433

- packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/wishlist.blade.php
> Issue #1573 fixed

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #1574 fixed

- packages/Webkul/Admin/src/Resources/views/settings/currencies/edit.blade.php
> Issue #1578 fixed

- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
> Issue #1585 fixed

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/views/settings/sliders/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/sliders/edit.blade.php
> Issue #1580 fixed

- packages/Webkul/Admin/src/Resources/views/tax/tax-rates/edit.blade.php
> Issue #1581 fixed

- packages/Webkul/Sales/src/Repositories/DownloadableLinkPurchasedRepository.php
- packages/Webkul/Sales/src/Repositories/OrderRepository.php
> Issue #1583 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php
- packages/Webkul/Sales/src/Repositories/OrderRepository.php
- packages/Webkul/Shop/src/Resources/assets/sass/app.scss
- packages/Webkul/Shop/src/Resources/views/products/view.blade.php
- packages/Webkul/Shop/src/Resources/views/products/view/grouped-products.blade.php
> Issue #1571 fixed

- packages/Webkul/Paypal/src/Payment/Standard.php
> Issue #1569 fixed

- packages/Webkul/Shop/src/Http/Controllers/ProductController.php
> Issue #1568 fixed

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
- packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
**Core development ideas or discussion:**
Now action can have a key called condition which must return boolean in order to trigger that action's visibility in the datagrid.
> Datagrid actions enhancement

- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
- packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
> Issue #1587 fixed

- packages/Webkul/Ui/src/DataGrid/DataGrid.php
**BUGS:**
Fixed issue #1595 causing ambiguous class issue when using php extension libevent.
> Fixed issue #1595

- packages/Webkul/Sales/src/Config/system.php
> Issue #1550 fixed

- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
Change category to categoryRepository.
> category repository issue

- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
> Issue #1607 fixed

- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
> Issue #1611 fixed

- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
**BUGS:**
Purchased downloadable product grid date filter issue fixed
> Purchased downloadable product grid date filter issue fixed

- packages/Webkul/Admin/src/DataGrids/OrderRefundDataGrid.php
> Issue #1609 fixed

- packages/Webkul/Sales/src/Repositories/OrderRepository.php
> Issue #1623 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
> Issue #1552 fixed

- packages/Webkul/Sales/src/Repositories/RefundRepository.php
> Issue #1618 fixed

- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
> Issue #1489 fixed

- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
> Issue #1629 fixed

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
- public/installer/Environment.php
Cart method name from add to AddProduct changes.
> cart method name for API

- packages/Webkul/Product/src/Type/Virtual.php
- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
- packages/Webkul/Sales/src/Repositories/RefundItemRepository.php
- packages/Webkul/Sales/src/Repositories/RefundRepository.php
- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
> Issue #1631 fixed

- public/installer/Migration.php
**BUGS:**
Fixes a typo in the Migration GUI
> Fix typo in Migration GUI

- packages/Webkul/Admin/src/Http/Controllers/ExportController.php
**BUGS:**
Bug #1555 : There was an issue related to the order refund export. [v0.1.8]
Fixed: I fixed the export feature of Order Refund at the admin end by adding the DataGrid name of Refund in the array i.e. $exportableGrids.
> [Bug Fixed #1555: order refund export related issue resolved.]

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
**BUGS:**
Fixes - #1662 
When a product is added to cart using API, we remove the product from wish list after adding it to the cart.
> Remove item from wishlist, when added to Cart - fixes #1662

- packages/Webkul/Admin/src/Exceptions/Handler.php
- packages/Webkul/Shop/src/Exceptions/Handler.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
**BUGS:**
Replace $_SERVER['REQUEST_URI'] with Larvel's request object #1251 - fixed
> #1251 - fixed

- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
**BUGS:**
Issues #1620, #1671 fixed
> Issues #1620, #1671 fixed

- config/mail.php
- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
- packages/Webkul/Product/src/Type/Bundle.php
> Issue #1676 fixed

- config/translatable.php
- packages/Webkul/Core/src/Eloquent/TranslatableModel.php
- packages/Webkul/Core/src/Helpers/Locales.php
- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
**BUGS:**
Issue #1620, #1671 fixed
> Issue #1620, #1671 fixed

- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
- packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
- packages/Webkul/Sales/src/Repositories/OrderRepository.php
> Issue #1680 fixed

- packages/Webkul/Admin/src/Resources/views/tax/tax-categories/create.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-categories/edit.blade.php
> Issue #1686 fixed

- packages/Webkul/Core/src/Http/Controllers/CountryStateController.php
- packages/Webkul/Product/src/Type/Bundle.php
> Issue #1684 fixed

- packages/Webkul/API/Http/Controllers/Shop/SessionController.php
- packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php
- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
- packages/Webkul/Shop/src/Http/routes.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-checkout.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/session/index.blade.php
- packages/Webkul/User/src/Http/Controllers/SessionController.php
**BUGS:**
[Bug Fixed #1219 ]
All password type field field should be encrypted and on inspect element also its value should be in encrypted form.
1. Now admin login and the customer login password filed is encrypted form.
[Enhancement #1182]
At checkout if guest user entered an email that is already registered then provide an option to sign-in at time of checkout.
1.Now in the checkout page if customer already registered then in the checkout page shown the password field for login.
2.  Register customer not need to fill all checkout form.
> [Bug Fixed #1219 ] & [Enhancement #1182]  Fixed 

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
**BUGS:**
>Move wishlist to cart issue fixed
> Move wishlist to cart issue fixed

- packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
**BUGS:**
>Removed comment from WishlistController
> Removed comment from WishlistController

- packages/Webkul/Checkout/src/Database/Migrations/2019_10_24_173437_change_postcode_column_type_in_cart_address_table.php
- packages/Webkul/Customer/src/Database/Migrations/2019_10_24_173507_change_postcode_column_type_in_customer_addresses_table.php
- packages/Webkul/Sales/src/Database/Migrations/2019_10_24_173358_change_postcode_column_type_in_order_address_table.php
**BUGS:**
>postcode column changed to varchar from int
> postcode column changed to varchar from int

- packages/Webkul/Product/src/Models/ProductAttributeValue.php
- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #1638 fixed

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
> wishlist api fixed

- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
- packages/Webkul/Product/src/Type/Grouped.php
- packages/Webkul/Product/src/Type/Simple.php
- packages/Webkul/Product/src/Type/Virtual.php
> Issue #1657 fixed

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
- packages/Webkul/API/Http/Controllers/Shop/WishlistController.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #1662 fixed

- packages/Webkul/Discount/src/Actions/Cart/WholeCartToFixed.php
- packages/Webkul/Discount/src/Actions/Cart/WholeCartToPercent.php
Namespace changed for WholeCartToFixedAmount and WholeCartToPercent action classes of cart rules.
> Fixed issue #1715

- packages/Webkul/API/Http/Controllers/Shop/SessionController.php
- packages/Webkul/Checkout/src/Listeners/CustomerEventsHandler.php
- packages/Webkul/Checkout/src/Providers/CheckoutServiceProvider.php
- packages/Webkul/Checkout/src/Providers/EventServiceProvider.php
- packages/Webkul/Customer/src/Http/Controllers/SessionController.php
> Issue #1519 fixed

- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
> Issue #1644 fixed

- packages/Webkul/Admin/src/Resources/views/tax/tax-categories/edit.blade.php
- packages/Webkul/Product/src/Type/Downloadable.php
> Issue #1721 fixed

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Core/src/Models/Channel.php
- packages/Webkul/Core/src/Repositories/ChannelRepository.php
> Issue #1724 fixed

- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
**BUGS:**
$rule undefined variable at checkout's save payment.
> Fixed issue undefined variable  at checkout

- packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php
Added client side email validation for field.
> Issue #1733

- packages/Webkul/Discount/src/Actions/Cart/FixedAmount.php
- packages/Webkul/Discount/src/Actions/Cart/PercentOfProduct.php
- packages/Webkul/Discount/src/Actions/Cart/WholeCartToFixed.php
- packages/Webkul/Discount/src/Actions/Cart/WholeCartToPercent.php
- packages/Webkul/Ui/src/Resources/views/datagrid/partials/default-header.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/partials/mass-action-header.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
**BUGS:**
> Fixed issue with whole cart rules creating exception during checkout.
> Fixed issue #1728

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Product/src/Type/AbstractType.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
- packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
> Issue #1347 fixed

- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
Default Billing and Shipping Method.
> default shipping and billing address

- packages/Webkul/Shop/src/Http/Middleware/Currency.php
- packages/Webkul/Shop/src/Http/Middleware/Locale.php
> Issue #1732 fixed

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/emails/admin/forget-password.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/layouts/logo.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
> Issue #1559 fixed

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
**BUGS:**
>Issue #1704 fixed (Update channel 'Base Curreny' label to 'Default Currency')
> Issue #1704 fixed (Update channel 'Base Curreny' label to 'Default Currency')

- packages/Webkul/Admin/src/Exceptions/Handler.php
> Issue #1303 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/boolean.blade.php
- packages/Webkul/Product/src/Http/Requests/ProductForm.php
> Issue #1745 fixed

- packages/Webkul/Admin/src/Resources/views/export/export.blade.php
> Issue #924 fixed

- packages/Webkul/Core/src/Http/Controllers/SubscriptionController.php
> Issue #1753 fixed

- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-checkout.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
**BUGS:**
>Issue #1746, #1271, #1735 fixed
> Issue #1746, #1271, #1735 fixed

- packages/Webkul/Discount/src/Actions/Cart/Action.php
- packages/Webkul/Discount/src/Actions/Cart/FixedAmount.php
- packages/Webkul/Discount/src/Actions/Cart/PercentOfProduct.php
- packages/Webkul/Discount/src/Helpers/Cart/ConvertXToProductId.php
- packages/Webkul/Discount/src/Helpers/Cart/CouponAbleRule.php
- packages/Webkul/Discount/src/Helpers/Cart/Discount.php
- packages/Webkul/Discount/src/Helpers/Catalog/Apply.php
- packages/Webkul/Discount/src/Helpers/Catalog/ConvertXToProductId.php
- packages/Webkul/Discount/src/Helpers/Catalog/Sale.php
- packages/Webkul/Discount/src/Repositories/CartRuleRepository.php
- packages/Webkul/Discount/src/Repositories/CatalogRuleRepository.php
**BUGS:**
>Fixed discount code standard
> Fixed discount code standard

- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
**A minor fix**
> Showing incorrect message after clicking on apply coupon button without entering any value.
>_Issue #1643_
> Issue 1643 fix

- packages/Webkul/Discount/src/Actions/Cart/Action.php
- packages/Webkul/Discount/src/Actions/Cart/FixedAmount.php
- packages/Webkul/Discount/src/Actions/Cart/PercentOfProduct.php
Solved issues leading to wrong calculation of discount amounts.
> Fixed issue #1547, #1453

- packages/Webkul/Attribute/src/resources/manifest.php
- packages/Webkul/CMS/src/resources/manifest.php
- packages/Webkul/Category/src/resources/manifest.php
- packages/Webkul/Checkout/src/resources/manifest.php
- packages/Webkul/Core/src/resources/manifest.php
- packages/Webkul/Customer/src/resources/manifest.php
- packages/Webkul/Discount/src/resources/manifest.php
- packages/Webkul/Inventory/src/resources/manifest.php
- packages/Webkul/Product/src/resources/manifest.php
- packages/Webkul/Sales/src/resources/manifest.php
- packages/Webkul/Tax/src/resources/manifest.php
- packages/Webkul/User/src/resources/manifest.php
**BUGS:**
Running `php artisan concord:routes` gives the following output:
```
ErrorException  : include(/var/www/html/bagisto/packages/Webkul/Attribute/src/resources/manifest.php): failed to open stream: No such file or directory
at /var/www/html/bagisto/vendor/konekt/concord/src/BaseServiceProvider.php:150
146|      */
147|     public function getManifest(): Manifest
148|     {
149|         if (!$this->manifest) {
> 150|             $data = include($this->basePath . '/' . $this->convention->manifestFile());
151| 
152|             $name    = $data['name'] ?? 'N/A';
153|             $version = $data['version'] ?? 'n/a';
154| 
Exception trace:
1   include()
/var/www/html/bagisto/vendor/konekt/concord/src/BaseServiceProvider.php:150
2   Konekt\Concord\BaseServiceProvider::getManifest() …
```
> add resources/manifest.php skeletons for Webkul packages

- composer.json
- packages/Webkul/Core/src/Events/ComposerEvents.php
- packages/Webkul/Core/src/Templates/on-boarding.php
**BUGS:**
- _Bagisto_ text will be printed on the terminal when creation of the project is completed via composer.
- This PR also includes indentation of _composer.json_
> Bagisto text and Indentation

- packages/Webkul/Core/src/Templates/on-boarding.php
> template correction

- .gitignore
- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
- packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
- packages/Webkul/Sales/src/Repositories/OrderRepository.php
- packages/Webkul/Sales/src/tests/sales/order/OrderRepositoryCest.php
I also did a little refactoring to the generateIncrementId() method - please review if i have done this right and if you like this style :)
> introduce 'checkout.order.orderitem.save.[before/after]' events

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024320_remove_tables.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024321_create_cart_rules_table.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024325_create_cart_rule_customers_table.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024327_create_cart_rule_coupon_usage_table.php
- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/CartRule/src/Helpers/Validator.php
- packages/Webkul/CartRule/src/Listeners/Order.php
- packages/Webkul/CartRule/src/Models/CartRule.php
- packages/Webkul/CartRule/src/Models/CartRuleCouponUsage.php
- packages/Webkul/CartRule/src/Models/CartRuleCustomer.php
- packages/Webkul/CartRule/src/Providers/CartRuleServiceProvider.php
- packages/Webkul/CartRule/src/Providers/EventServiceProvider.php
- packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Checkout/src/Database/Migrations/2019_11_30_165644_add_discount_columns_in_cart_shipping_rates_table.php
- packages/Webkul/Checkout/src/Models/Cart.php
- packages/Webkul/Checkout/src/Models/CartShippingRate.php
- packages/Webkul/Sales/src/Database/Migrations/2019_11_30_124437_add_applied_cart_rule_ids_column_in_orders_table.php
> Cart rule completed

- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/CatalogRule/src/Contracts/CatalogRule.php
- packages/Webkul/CatalogRule/src/Database/Migrations/2019_12_03_175253_create_remove_catalog_rule_tables.php
- packages/Webkul/CatalogRule/src/Models/CatalogRule.php
- packages/Webkul/CatalogRule/src/Models/CatalogRuleProxy.php
- packages/Webkul/CatalogRule/src/Providers/CatalogRuleServiceProvider.php
- packages/Webkul/CatalogRule/src/Providers/ModuleServiceProvider.php
- packages/Webkul/CatalogRule/src/Repositories/CatalogRuleRepository.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Fixed issues

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
> Issue #1825 fixed

- packages/Webkul/Admin/src/DataGrids/CartRuleCouponDataGrid.php
- packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/CartRule/src/Helpers/CartRule.php
> Issue #1847 fixed

- packages/Webkul/CartRule/src/Helpers/CartRule.php
> Issue #1849 fixed

- packages/Webkul/CartRule/src/Helpers/Validator.php
> Issues #1856, #1857 fixed

- packages/Webkul/CartRule/src/Helpers/CartRule.php
Date range filter added to cart rule validation
> Date range filter added to cart rule validation

- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/CatalogRule/src/Console/Commands/PriceRuleIndex.php
- packages/Webkul/CatalogRule/src/Contracts/CatalogRuleProductPrice.php
- packages/Webkul/CatalogRule/src/Database/Migrations/2019_12_06_110507_create_catalog_rule_product_prices_table.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRule.php
- packages/Webkul/CatalogRule/src/Models/CatalogRuleProductPrice.php
- packages/Webkul/CatalogRule/src/Models/CatalogRuleProductPriceProxy.php
- packages/Webkul/CatalogRule/src/Providers/CatalogRuleServiceProvider.php
- packages/Webkul/CatalogRule/src/Providers/ModuleServiceProvider.php
- packages/Webkul/CatalogRule/src/Repositories/CatalogRuleProductPriceRepository.php
- packages/Webkul/Rule/src/Helpers/Validator.php
Product price migration added to the CatalogRule package
> Product price migration added to the CatalogRule package

- packages/Webkul/CatalogRule/src/Console/Commands/PriceRuleIndex.php
- packages/Webkul/CatalogRule/src/Contracts/CatalogRuleProduct.php
- packages/Webkul/CatalogRule/src/Database/Migrations/2019_12_06_101110_create_catalog_rule_products_table.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRule.php
- packages/Webkul/CatalogRule/src/Models/CatalogRuleProduct.php
- packages/Webkul/CatalogRule/src/Models/CatalogRuleProductProxy.php
- packages/Webkul/CatalogRule/src/Providers/ModuleServiceProvider.php
- packages/Webkul/CatalogRule/src/Repositories/CatalogRuleProductRepository.php
> Issue fixed

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
Mass Action Crashes the system.
> Issue #1844, Mass Action Crashes the system

- packages/Webkul/Shop/src/Resources/views/products/reviews/index.blade.php
> Issue #1821, price at review page

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php
- packages/Webkul/Product/src/Helpers/Price.php
Catalog price rule applied for simple products
> Catalog price rule applied for simple products

- packages/Webkul/Admin/src/Config/menu.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php
- packages/Webkul/Product/src/Helpers/Price.php
Catalog rules applied configurable products
> Catalog rules applied configurable products

- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
- packages/Webkul/CatalogRule/src/Listeners/Product.php
- packages/Webkul/CatalogRule/src/Providers/CatalogRuleServiceProvider.php
- packages/Webkul/Rule/src/Helpers/Validator.php
> Issues #1883, #1882 fixed

- packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
> Issue #1904 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
> Multiple type file error

- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/Rule/src/Helpers/Validator.php
Removed duplicate function for discount validation
> Removed duplicate function for discount validation

- packages/Webkul/Rule/src/Helpers/Validator.php
> Issue #1875 fixed

- CHANGELOG for v0.1.x.md
- packages/Webkul/Core/src/Config/concord.php
> Updated changelog file

- packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
Necessary for our project specific enhancements
thanks a lot !
> add two events to profile index blade view

- packages/Webkul/Product/src/Helpers/Price.php
Configurable min price issue fixed if catalog rule not exist
> Configurable min price issue fixed if catalog rule not exist

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
- packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
- packages/Webkul/CatalogRule/src/Listeners/Product.php
- packages/Webkul/Product/src/Helpers/Price.php
Index creation completed on product update and rule creation
> Index creation completed on product update and rule creation

- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/edit.blade.php
Vue js issue fixed on catalog rule edit page
> Vue js issue fixed on catalog rule edit page

- packages/Webkul/Shop/src/Http/Controllers/ReviewController.php
**BUGS:**
If any customer directly hits the review page url, the review page will be rendered and it won't check whether the customer is in session or not.
**SOLUTION:**
I have added a check that will check the customer in session.
> Throw exception when user is not is session

- CHANGELOG for v0.1.x.md
> Changelog file updated

- packages/Webkul/Product/src/Helpers/Price.php
ProductFlat to Product instance passed in getRulePrice function
> ProductFlat to Product instance passed in getRulePrice function

- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/edit.blade.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
- packages/Webkul/Rule/src/Helpers/Validator.php
> Issue #1928 fixed

- CHANGELOG for v0.1.x.md
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php
> Changelog updated

- packages/Webkul/Product/src/Helpers/Price.php
fixed bug in haveSpecialPrice function
> fixed bug in haveSpecialPrice function

- packages/Webkul/Rule/src/Helpers/Validator.php
Bug fixed Rule package if condition is not set
> Bug fixed Rule package if condition is not set

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
> Issue #1935 fixed

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/CartRule/src/Helpers/CartRule.php
> Issue #1938 fixed

- packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
> Issue #1939 fixed

- CHANGELOG for v0.1.x.md
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
Updated changelog and closed condition accordian on edit page
> Updated changelog and closed condition accordian on edit page

- .env.example
Updated app version in .env file
> Updated app version in .env file

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
Fixed exception issue if rule condition is null
> Fixed exception issue if rule condition is null

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
> Minor code standard corrected

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php
Removed commented exception handler
> Removed commented exception handler

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
Catalog Rule priority issue fixed
> Catalog Rule priority issue fixed

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
Fixed issue if condition value is not set
> Fixed issue if condition value is not set

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
> Issue #1959 fixed

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
> Issue #1957 fixed

- packages/Webkul/CartRule/src/Helpers/CartRule.php
> Issue #1958 fixed

- packages/Webkul/Shop/src/Resources/lang/en/app.php
> Issue #1955 fixed

- .env.example
- CHANGELOG for v0.2.x.md
> Updated version in .env file

- public/installer/Finish.php
…lication url
Fixed a bug when installation is done was redirecting to wrong url.
> fix: broken url sometimes when finishing installation,go to wrong address

- packages/Webkul/Product/src/Repositories/ProductRepository.php
Increase maintainability by replacing hard coded class name `'Webkul\Product\Repositories\ProductFlatRepository'` by `ProductFlatRepository::class` in ProductRepository.
> Minor code style improvement in ProductRepository

- packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
Allow datagrid action to have target="_blank".
> Allow datagrid action to have target="_blank"

- packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
Replaced hard coded links to product in two views.
> Fixed product links in two views (replaced hard coded link with route)

- .env.example
- CHANGELOG for v0.2.x.md
- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
**BUGS:**
* Catalog rule product price issue fixed 
* Changed copyright text in footer
> Fixed catalog rule price issue

- packages/Webkul/Admin/src/Resources/views/tax/tax-rates/create.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-rates/edit.blade.php
> Tax rates for all states

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Product/src/Listeners/ProductFlat.php
- packages/Webkul/Product/src/Models/Product.php
- packages/Webkul/Tax/src/Http/Controllers/TaxRateController.php
**BUGS:**
Issues #1997, #1994 fixed
> Issues #1997, #1994 fixed

- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
> Issue #1983

- config/app.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Sales/src/Database/Migrations/2020_01_09_154851_add_shipping_discount_columns_in_orders_table.php
- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
> Issue #1979 fixed

- README.md
- Corrected some spelling and grammar
- Added some punctuation
- Rephrased some bits
> README.md: Updates to improve readability

- packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
- packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
- packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
- packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
- packages/Webkul/Admin/src/DataGrids/OrderRefundDataGrid.php
- packages/Webkul/Admin/src/DataGrids/OrderShipmentsDataGrid.php
- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
- packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
- packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php
- packages/Webkul/Sales/src/Database/Migrations/2020_01_09_202815_add_inventory_source_name_column_in_shipments_table.php
- packages/Webkul/Sales/src/Repositories/ShipmentRepository.php
- packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
- packages/Webkul/Ui/src/DataGrid/DataGrid.php
> Issue #1845 fixed

- packages/Webkul/Shop/src/Resources/lang/en/app.php
> Issue #1842 fixed

- packages/Webkul/CMS/src/Http/Controllers/Shop/PagePresenterController.php
- packages/Webkul/Shop/src/Resources/views/cms/page.blade.php
> Issue #1804 fixed

- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
> Issue #1808

- packages/Webkul/Core/src/Models/Country.php
- packages/Webkul/Core/src/Models/CountryState.php
**BUGS:**
Eager loaded translations for country and country state models
> Eager loaded translations for country and country state models

- packages/Webkul/Product/src/Repositories/ProductDownloadableLinkRepository.php
- packages/Webkul/Product/src/Repositories/ProductDownloadableSampleRepository.php
> Issue #1781 fixed

- packages/Webkul/Shipping/src/Config/system.php
> Issue #1777 fixed

- packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
> Issue #1764 fixed

- packages/Webkul/Core/src/Contracts/Validations/Decimal.php
- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #1795 fixed

- config/modules.php
- packages/Webkul/Product/src/Type/Bundle.php
> Issue #1760 fixed

- packages/Webkul/Admin/src/Resources/views/settings/currencies/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/currencies/edit.blade.php
add "enctype" attribute in form for uploading attachments.
> updates for uploading attachments

- packages/Webkul/Admin/package.json
- packages/Webkul/Admin/src/Resources/assets/js/app.js
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Shop/src/Resources/assets/js/app.js
> Issue #1779 fixed

- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
> Issue #2045

- packages/Webkul/Admin/src/DataGrids/CartRuleCouponDataGrid.php
> Issue #1971

- packages/Webkul/Core/src/Repositories/SliderRepository.php
Addtion will fire event when slider created/updated on admin panel.
> fire event on creating/updating slider

- packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
> Issue #1863 fixed

- packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
- packages/Webkul/Shop/src/Resources/views/products/view/bundle-options.blade.php
**BUGS:**
Removed ')' in page edit blade
> Removed ')' in page edit blade

- packages/Webkul/Product/src/Type/Bundle.php
> Issue #2054 fixed

- .env.example
> Added mail from name field in .env.example file, Issue #2051

- packages/Webkul/Admin/src/Resources/views/settings/locales/edit.blade.php
- packages/Webkul/Core/src/Repositories/SliderRepository.php
**BUGS:**
There was no locale information in view_render_event when locale is being edited.
> pass locale data in view_render_event

- .gitignore
- composer.lock
In my opinion, the composer.lock should be included in the repository:
https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control
please discuss why this is not a good idea, if so.
> remove composer.lock from .gitignore

- packages/Webkul/Admin/src/Config/menu.php
- packages/Webkul/Admin/src/Http/routes.php
**BUGS:**
Removed Developement menu
> Removed Developement menu

- packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
- packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
**BUGS:**
Fixed cms textarea field issue
> Fixed cms textarea field issue

- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
- packages/Webkul/Category/src/Repositories/CategoryRepository.php
> Issue #2075 fixed

- composer.lock
- packages/Webkul/CMS/src/Repositories/CmsRepository.php
- packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
- packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Core/src/Repositories/SliderRepository.php
**BUGS:**
Cart rule and catalog rule updated for laravel 6.0
> Cart rule and catalog rule updated for laravel 6.0

- README.md
**BUGS:**
PHP version updated in readme file
> PHP version updated in readme file

- public/installer/Classes/Requirement.php
php version updated for installer.
> php version updated for installer.

- config/app.php
- packages/Webkul/Customer/src/Http/Controllers/AddressController.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/country-state.blade.php
For some comfort features, it may be handy to provide an default country in which the majority of the customers are being expected.
> introduce default_country application configuration key

- composer.json
**BUGS:**
PHP version updated in composer.json
> PHP version updated in composer.json

- .env.ci
> Added .env.ci file

- composer.lock
**BUGS:**
composer.lock file updated
> composer.lock file updated

- .github/workflows/ci.yml
**BUGS:**
Added php extensions
> Added php extensions

- .github/workflows/ci.yml
**BUGS:**
Fixed syntax in ci.yml
> Fixed syntax in ci.yml

- .env.testing
- .github/workflows/ci.yml
See #2107 for details
Closes #2107
> #2107 add automated test pipeline

- .env.testing
- .github/workflows/ci.yml
> Revert "Revert "#2107 add automated test pipeline""

- .env.testing
> Fixed App URL in

- packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/users/reset-password/create.blade.php
- packages/Webkul/Admin/src/Resources/views/users/users/create.blade.php
- packages/Webkul/Admin/src/Resources/views/users/users/edit.blade.php
> Issue #1397 fixed

- packages/Webkul/Customer/src/Http/Controllers/ResetPasswordController.php
- packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
- packages/Webkul/Shop/src/Http/routes.php
- packages/Webkul/User/src/Http/Controllers/ForgetPasswordController.php
> Issue #2087

- packages/Webkul/Checkout/src/Cart.php
> Issue #2088

- packages/Webkul/Product/src/Type/Bundle.php
**condtion added for bundle product while adding cart**
> condtion added for bundle product while adding cart

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
> Issue #2128 fixed

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
> Issue #2124 fixe

- packages/Webkul/Attribute/src/Database/Factories/AttributeFamilyFactory.php
- packages/Webkul/Core/src/Database/Factories/SubscriberListFactory.php
- packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php
- packages/Webkul/Customer/src/Database/Factories/CustomerFactory.php
- packages/Webkul/Customer/src/Database/Factories/CustomerGroupFactory.php
- packages/Webkul/Customer/src/Providers/CustomerServiceProvider.php
- packages/Webkul/Product/src/Database/Factories/ProductReviewFactory.php
- packages/Webkul/Sales/src/Database/Factories/InventorySourceFactory.php
- packages/Webkul/Sales/src/Database/Factories/InvoiceFactory.php
- packages/Webkul/Sales/src/Database/Factories/OrderAddressFactory.php
- packages/Webkul/Sales/src/Database/Factories/OrderFactory.php
- packages/Webkul/Sales/src/Database/Factories/RefundFactory.php
- packages/Webkul/Sales/src/Database/Factories/ShipmentFactory.php
- packages/Webkul/Sales/src/Providers/SalesServiceProvider.php
- tests/_support/Helper/DataMocker.php
- tests/functional.suite.yml
- tests/functional/Admin/Catalog/AttributeCest.php
- tests/functional/Admin/Catalog/AttributeFamilyCest.php
- tests/functional/Admin/Catalog/CategoryCest.php
- tests/functional/Admin/Catalog/ProductCest.php
- tests/functional/Admin/Customer/CustomerCest.php
- tests/functional/Admin/Customer/GroupsCest.php
- tests/functional/Admin/Customer/NewsletterSubscriptionCest.php
- tests/functional/Admin/Customer/ReviewCest.php
- tests/functional/Admin/Sales/InvoiceCest.php
- tests/functional/Admin/Sales/OrderCest.php
- tests/functional/Admin/Sales/RefundCest.php
- tests/functional/Admin/Sales/ShipmentsCest.php
Tests are executed automatically by ci-pipeline. In order to ensure that bagisto is working, this pr adds several simple tests for the admin-backend. They check a lot of index (list) views and some create/update forms.
The pr also includes all factories needed for creating test-data.
> add basic backend tests

- packages/Webkul/Product/src/Type/Bundle.php
> Issue #2146 fixed

- public/installer/index.php
> Issue #2149

- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2087 fixed

- packages/Webkul/Shop/src/Http/Controllers/CartController.php
**BUGS:**
Removed commented code
> Removed commented code

- packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php
- packages/Webkul/Customer/src/Database/Migrations/2020_01_28_102422_add_new_column_and_rename_name_column_in_customer_addresses_table.php
- packages/Webkul/Customer/src/Http/Controllers/AddressController.php
- packages/Webkul/Customer/src/Models/CustomerAddress.php
> Issue #2155

- packages/Webkul/Admin/src/Resources/views/settings/locales/edit.blade.php
> Issue #2168 fixed

- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- public/installer/Email.php
> Issue #742 and #2165

- packages/Webkul/Payment/src/Config/paymentmethods.php
> Issue #2167 fixed

- packages/Webkul/Product/src/Http/Requests/ProductForm.php
> Issue #2162 fixed

- packages/Webkul/Admin/src/Resources/views/settings/locales/create.blade.php
> Issue #2173 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
- packages/Webkul/Sales/src/Repositories/RefundRepository.php
**BUGS:**
Shipping discount issue fixed during refund creation
> Shipping discount issue fixed during refund creation

- packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
> Issue #2183 fixed

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
> #Issue 2190

- packages/Webkul/Admin/src/Resources/views/export/temp.blade.php
> Issue #2192

- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
> Issue #2207 fixed

- packages/Webkul/API/Http/Controllers/Shop/CustomerController.php
> [Fixed: changed customer group code for newly created customer.]

- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #2202 fixed

- packages/Webkul/Admin/src/Resources/views/customers/edit.blade.php
> Issue #2182 fixed

- packages/Webkul/Core/src/Core.php
> Issue #2226

- packages/Webkul/Admin/src/Resources/views/export/export.blade.php
> Fixed issue 2225

- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
> Issue #2237 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
> Issue #2227

- packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
- packages/Webkul/Customer/src/Http/Controllers/AddressController.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/review.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
- tests/functional/Customer/CustomerCest.php
just a tiny field that was missing... thanks a lot !
> add ability to provide company_name in address during checkout

- packages/Webkul/API/Http/Controllers/Shop/WishlistController.php
- packages/Webkul/API/Http/routes.php
**BUGS:**
[Added: review delete api route added.]
> [Added: review delete api route added.]

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
> Issue #2251

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php
- tests/functional/Admin/Customer/CustomerCest.php
In downloadable accordian, I added identifiers to section div elements because I need them for some reasons. 
I'd really appreciate this PR to be accepted, thanks.
> Added ids to sections in accordians/downloadable.blade.php

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
> Issue #1267 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> Issue #2256

- packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php
**BUGS:**
[Fixed: Issue #2279 related to Sort By functionality is not working.]
> [Fixed: Issue #2279 related to Sort By functionality is not working.]

- packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
> Issue #2295 fixed

- packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/mini-cart.blade.php
**BUGS:**
>In minicart, whole minicart container is showing clickable but only image section gets clicked to redirect to product page.
>#2281 issue solved 
>view cart mouse hover issue fixed.
> 2281 solved

- packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/forgot-password.blade.php
**BUGS:**
>Fixed Issue (Not getting password reset email for velocity theme).
> resolved issue [#2273]

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-checkout.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/slider.blade.php
> Misc. bug fixes

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
> Issue #2299 fixed

- packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/recently-viewed.blade.php
> Issue #2297

- packages/Webkul/Customer/src/Rules/VatValidator.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
**BUGS:**
[Fixed: issue #2313 resolved.]
> [Fixed: issue #2313 resolved.]

- packages/Webkul/Admin/src/Resources/lang/en/app.php
> Issue #2126 fixed

- packages/Webkul/Shop/src/Http/Controllers/CartController.php
- packages/Webkul/Shop/src/Http/Controllers/CategoryController.php
- packages/Webkul/Shop/src/Http/Controllers/Controller.php
- packages/Webkul/Shop/src/Http/Controllers/DownloadableProductController.php
- packages/Webkul/Shop/src/Http/Controllers/HomeController.php
- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
- packages/Webkul/Shop/src/Http/Controllers/OrderController.php
- packages/Webkul/Shop/src/Http/Controllers/ProductController.php
- packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
- packages/Webkul/Shop/src/Http/Controllers/ReviewController.php
- packages/Webkul/Shop/src/Http/Controllers/SearchController.php
- packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php
> Issue #2142 fixed

- packages/Webkul/Checkout/src/Cart.php
**BUGS:**
Move to wishlist issues fixed if product is already in wishlist
> Move to wishlist issues fixed if product is already in wishlist

- packages/Webkul/Velocity/src/Resources/lang/en/app.php
> Issue #2340 fixed

- packages/Webkul/Velocity/src/DataGrids/ContentDataGrid.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/category.blade.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/edit-product.blade.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/edit.blade.php
> Issue #2339 fixed

- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2335 fixed

- packages/Webkul/Ui/src/Resources/lang/ar/app.php
- packages/Webkul/Ui/src/Resources/lang/en/app.php
- packages/Webkul/Ui/src/Resources/lang/fa/app.php
- packages/Webkul/Ui/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Ui/src/Resources/views/datagrid/partials/mass-action-header.blade.php
> Issue #2307 fixed

- packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php
**BUGS:**
[Fixed: issue #2346 resolved.]
> [Fixed: issue #2346 resolved.]

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php
> Issue #1977 fixed

- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/es/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
> Issue #2360 fixed

- packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/groups/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/reviews/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/subscribers/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/currencies/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/locales/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-rates/edit.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
**FEATURE**
>old() function implemented in admin package
> old() function implemented in admin package

- packages/Webkul/Core/src/Http/Controllers/LocaleController.php
- packages/Webkul/Velocity/src/Helpers/AdminHelper.php
> Issue #2377

- packages/Webkul/Core/src/Http/Controllers/SliderController.php
> #2070 issue fixed

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
**BUGS:**
[Fixed: Issue #2397 has been resolved.]
> [Fixed: Issue #2397 has been resolved.]

- packages/Webkul/Checkout/src/Cart.php
> Issue #2395 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
> #2364 issue fixed

- packages/Webkul/Shipping/src/Carriers/AbstractShipping.php
- packages/Webkul/Shipping/src/Shipping.php
> Issue #2417 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
> Issue #2416 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
> Issue #2398 fixed

- packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
- packages/Webkul/Admin/src/Resources/views/customers/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/tax/tax-rates/create.blade.php
- packages/Webkul/Admin/src/Resources/views/users/users/create.blade.php
- packages/Webkul/Admin/src/Resources/views/users/users/edit.blade.php
**BUGS:**
Converted checkbox into switch
> Converted checkbox into switch

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/partials/sidemenu.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/slider.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> minor bug fixes

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/index.blade.php
**BUGS:**
Fixed: Issue #2322 button alignment corrected.
> Fixed: Issue #2322 button alignment corrected.

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/bundle-options.blade.php
**BUGS:**
[Fixed: layout issue regarding #2399 resolved.]
> [Fixed: layout issue regarding #2399 resolved.]

- packages/Webkul/Core/src/Repositories/CoreConfigRepository.php
**BUGS:**
Fixed intentation in CoreConfigRepository
> Fixed intentation in CoreConfigRepository

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
> Issue #2250 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/total/summary.blade.php
> Issue #2438 fixed

- packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
- packages/Webkul/Core/src/Repositories/CoreConfigRepository.php
- packages/Webkul/Payment/src/Config/system.php
- packages/Webkul/Shipping/src/Config/system.php
**BUGS:**
Converted configuration boolean type to switch
> Converted configuration boolean type to switch

- packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
**BUGS:**
[Fixed: issue #2436 has been resolved.]
> [Fixed: issue #2436 has been resolved.]

- packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-four.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-three.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-two.blade.php
**BUGS:**
[Fixed: issue #2440 has been resolved.]
> [Fixed: issue #2440 has been resolved.]

- packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
**BUGS:**
[Fixed: issue #2440 resolved.]
> [Fixed: issue #2440 resolved.]

- packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
> Issue #2449

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-info.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
**BUGS:**
checkout misc. bug fixes
> checkout misc. bug fixes

- packages/Webkul/Sales/src/Database/Factories/OrderFactory.php
- packages/Webkul/Sales/src/Database/Factories/OrderItemFactory.php
- packages/Webkul/Sales/src/Database/Factories/OrderPaymentFactory.php
- tests/functional/Shop/GuestCheckoutCest.php
Added fields to the following factories:
* OrderFactory
* OrderItemFactory
* OrderPaymentFactory
> Added fields to order related factories

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
> WIP: misc. updates

- tests/functional/Admin/Customer/CustomerCest.php
Test case for customer create at admin end.
> Test case for customer create

- packages/Webkul/Checkout/src/Cart.php
> Issue #2463

- packages/Webkul/Shop/src/Resources/views/products/view/bundle-options.blade.php
> Issue #2467

- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
- packages/Webkul/Core/src/Core.php
- packages/Webkul/Core/src/Models/Channel.php
- packages/Webkul/Product/src/Http/Controllers/ProductController.php
- packages/Webkul/Product/src/Models/Product.php
add improvements to locale determination on product creation.
The default locale that has been configured inside a custom channel was previously not obeyed.
> add improvements to locale determination on product creation

- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/recently-viewed.blade.php
> issue #2479 fixed

- packages/Webkul/Checkout/src/Http/helpers.php
> helper updated

- packages/Webkul/Core/src/Http/Controllers/CurrencyController.php
**BUGS:**
[Fixed: Currency event related code fixed. ]
> [Fixed: Currency event related code fixed. ]

- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Category/src/Http/Controllers/CategoryController.php
- packages/Webkul/Core/src/Core.php
- packages/Webkul/Core/src/Models/Channel.php
- packages/Webkul/Product/src/Http/Controllers/ProductController.php
- packages/Webkul/Product/src/Models/Product.php
Reverts bagisto/bagisto#2373.
Not working well on different locales. - https://prnt.sc/r41w1j
> Revert "add improvements to locale determination on product creation"

- packages/Webkul/Core/src/Database/Seeders/CurrencyTableSeeder.php
This pull request adds the euro currency to the currency table seeder to speed up new installations.
> Added euro currency

- public/installer/CSS/style.css
- public/installer/Classes/Requirement.php
- public/installer/Composer.php
- public/installer/Email.php
- public/installer/Environment.php
- public/installer/Finish.php
- public/installer/JS/script
- public/installer/Migration.php
- public/installer/MigrationRun.php
- public/installer/Views/requirements.blade.php
- public/installer/index.php
This pull requests contains improvements for the web installer
- Improved responsive design.
- fixed #2163
> Webinstall

- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/views/customers/confirm-password.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
- packages/Webkul/User/src/Http/Controllers/UserController.php
**BUGS:**
[Updated: resolved admin user delete issue.]
> [Updated: resolved admin user delete issue.]

- CHANGELOG for v1.x.x.md
> change log updated

- CHANGELOG for v1.x.x.md
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024321_create_cart_rules_table.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024325_create_cart_rule_customers_table.php
- packages/Webkul/CartRule/src/Database/Migrations/2019_05_13_024326_create_cart_rule_coupons_table.php
- packages/Webkul/Customer/src/Database/Migrations/2018_07_24_082930_create_customers_table.php
Issue #2500 and change log updated.
> Issue #2500 and change log updated

- CHANGELOG for v1.x.x.md
- composer.json
- composer.lock
- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
Issue #2435 and change log updated.
> Issue #2435 and change log updated

- packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
> Issue #2468

- packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
> filter issue in category

- packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
quick view short description issue
> quick view short description issue

- packages/Webkul/Velocity/src/Resources/lang/en/app.php
- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
> Issue #2526

- CHANGELOG for v1.x.x.md
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
Issue #2533 fixed and change log updated.
> Issue #2533 fixed and change log updated

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/total/summary.blade.php
> tax in velocity theme

- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
post code in shipping address.
> post code in shipping address

- CHANGELOG for v1.x.x.md
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Issue #2538 fixed and change log updated.
> Issue #2538 fixed and change log updated

- packages/Webkul/CatalogRule/src/Console/Commands/PriceRuleIndex.php
> Uncomment code 

- CHANGELOG for v1.x.x.md
> change log updated for 1.x.x

- packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
> laguage updated for order

- packages/Webkul/CartRule/src/Helpers/CartRule.php
I found a little issue on handling coupons in cart.
**To reproduce this issue you have to do:**
- create three simple products
- create a cart rule with coupon
- assign conditions, so that sku of product 1 and product 2 will match the coupon
- add product 1 to cart
- add product 2 to cart
- last add product 3 to cart (which has no coupon matching)
- apply the coupon
You get an error message.
So therefore I made some little changes.
> fix issue in coupon handling

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
Hello Bagisto Team,
I found some hard coded translations in API/CartController and entered the corresponding Webkul/Shop translation keys.
> Add translation keys in API/Cart

- .github/ISSUE_TEMPLATE/1_Bug_report.md
Spelling mistake in bug report template.
> spelling mistake in bug report template

- packages/Webkul/Theme/src/ThemeViewFinder.php
Theme system updated to support module theming
> Theme system updated to support module theming

- packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
- packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
> Issue #2616

- packages/Webkul/Sales/src/Database/Factories/InvoiceFactory.php
I made the InvoiceFactory compatible to PHP 7.3 with tiny changes.
> Tiny refactoring of InvoiceFactory

- packages/Webkul/Product/src/Providers/ProductServiceProvider.php
- packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/es/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/nl/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Tax/src/Providers/TaxServiceProvider.php
Removed static text from shop datagrid
> Removed static text from shop datagrid

- composer.lock
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/table.blade.php
- packages/Webkul/Tax/src/Providers/TaxServiceProvider.php
> Issue #2630 fixed

- packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/default.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/default.blade.php
> Issue #2650 fixed

- packages/Webkul/BookingProduct/src/Helpers/DefaultSlot.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
> Issue #2649 fixed

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
> Issue #2638 fixed

- packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php
- packages/Webkul/Product/src/Type/AbstractType.php
**BUGS:**
Catalog price rule issue fixed if discounted and normal price is same
> Catalog price rule issue fixed if discounted and normal price is same

- packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/slots.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/slots.blade.php
> Issue #2654 fixed

- packages/Webkul/BookingProduct/src/Repositories/BookingProductRepository.php
> Issue #2658 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/table.blade.php
> Issue #2660 fixed

- public/installer/Email.php
- public/installer/EmailConfig.php
> Issue #2644 fixed

- packages/Webkul/Core/src/Config/concord.php
**BUGS:**
[Updated: Core/Config.php modified.]
> [Updated: Core/Config.php modified.]

- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2672 fixed

- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
> Issue #2671 fixed

- packages/Webkul/BookingProduct/src/Helpers/Booking.php
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/Checkout/src/Cart.php
> Issue #2669 fixed

- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Checkout/src/Cart.php
> Issue #2677 fixed

- packages/Webkul/Core/composer.json
> Issue #2613 fixed

- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
> Issue #2593 fixed

- packages/Webkul/Admin/src/Listeners/Order.php
- packages/Webkul/Core/src/Database/Seeders/CurrencyTableSeeder.php
- packages/Webkul/Core/src/Database/Seeders/LocalesTableSeeder.php
> Issue #2518 fixed

- public/installer/Email.php
- public/installer/EmailConfig.php
- resources/views/vendor/notifications/email.blade.php
> Issue #2637 fixed

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
- packages/Webkul/Sales/src/Config/system.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
> Issue #2549

- packages/Webkul/Admin/src/Mail/CancelOrderNotification.php
- packages/Webkul/Admin/src/Mail/NewAdminNotification.php
- packages/Webkul/Admin/src/Mail/NewCustomerNotification.php
- packages/Webkul/Admin/src/Mail/NewInventorySourceNotification.php
- packages/Webkul/Admin/src/Mail/NewInvoiceNotification.php
- packages/Webkul/Admin/src/Mail/NewOrderNotification.php
- packages/Webkul/Admin/src/Mail/NewRefundNotification.php
- packages/Webkul/Admin/src/Mail/NewShipmentNotification.php
- packages/Webkul/Sales/src/Repositories/RefundItemRepository.php
> Issue #2594 fixed

- CHANGELOG for v1.x.x.md
- packages/Webkul/BookingProduct/src/Type/Booking.php
> Issue #2707 fixed

- packages/Webkul/API/Http/Resources/Customer/CustomerAddress.php
It would be nice if we'd receive the customer first_name, last_name and company_name via API call (api/addresses)
> extend addresses API

- packages/Webkul/Core/src/Database/Factories/CartRuleCouponFactory.php
Add a factory to create CartRuleCoupon for testing purposes.
> add CartRuleCouponFactory

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #2704 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
> Issue #2706 fixed

- packages/Webkul/BookingProduct/src/Helpers/Booking.php
- packages/Webkul/BookingProduct/src/Helpers/DefaultSlot.php
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
> Issue #2712 fixed

- packages/Webkul/BookingProduct/src/Helpers/Booking.php
- packages/Webkul/BookingProduct/src/Helpers/DefaultSlot.php
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/BookingProduct/src/Helpers/TableSlot.php
> Issue #2714 fixed

- packages/Webkul/BookingProduct/src/Database/Migrations/2020_03_23_201431_alter_booking_products_table.php
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
> Issue #2716 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/rental.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/rental.blade.php
> Issue #2719 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/default.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/slots.blade.php
> Issue #2728 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Checkout/src/Cart.php
> Issue #2722 fixed

- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2724 fixed

- packages/Webkul/BookingProduct/src/Repositories/BookingProductRepository.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2715 fixed

- packages/Webkul/Velocity/src/Helpers/Helper.php
- packages/Webkul/Velocity/src/Resources/lang/ar/app.php
- packages/Webkul/Velocity/src/Resources/lang/en/app.php
- packages/Webkul/Velocity/src/Resources/lang/fa/app.php
- packages/Webkul/Velocity/src/Resources/lang/nl/app.php
- packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
> Issue #2610 resolved

- CHANGELOG for v1.x.x.md
> Updated changelog

- CHANGELOG for v1.x.x.md
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
> Issue #2717 fixed

- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
**BUGS:**
Fixed undefind variable issue in rental booking helper
> Fixed undefind variable issue in rental booking helper

- packages/Webkul/Velocity/src/Resources/views/shop/products/add-to-cart.blade.php
> Issue #2750 resolved

- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
> Issue #2763 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
**BUGS:**
Event added: - bagisto.shop.layout.header.before
> Event added: - bagisto.shop.layout.header.before

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/index.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
compare page update height after loading images
> compare page update height after loading images

- packages/Webkul/API/Http/Controllers/Shop/ProductController.php
- packages/Webkul/Product/src/Helpers/BundleOption.php
- packages/Webkul/Product/src/Type/AbstractType.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
> api changes

- packages/Webkul/Product/src/Type/AbstractType.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
**BUGS:**
issue resolved and code optimised.
> code changed for api

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
**BUGS:**
issue #2792 resolved.
> issue #2792 resolved

- packages/Webkul/Shop/src/Resources/views/products/wishlist.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-checkout.blade.php
> misc. updates

- packages/Webkul/BookingProduct/src/Helpers/EventTicket.php
> Issue #2768 fixed

- composer.json
- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
> Issue #2713 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
> Issue #2834 resolved

- CHANGELOG for v1.x.x.md
> Issue #2846 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/default.blade.php
**BUGS:**
Fixed date icon issue
> Fixed date icon issue

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/index.blade.php
> miscellaneous bug fixes

- packages/Webkul/Admin/src/DataGrids/CustomerReviewDataGrid.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
1. Add translations for customer reviews grid massaction in admin
2. Fix "Save category" button translation in admin for languages with cases (for example - cyrillic)
> Translation fixes

- CHANGELOG for v1.x.x.md
- packages/Webkul/BookingProduct/src/Helpers/DefaultSlot.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
> Issue #2784 fixed

- CHANGELOG for v1.x.x.md
- packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
> Issue #2871 fixed

- packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
- packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php
**BUGS:**
subcategory issue resolved
> subcategory issue resolved

- packages/Webkul/Velocity/src/Helpers/Helper.php
> Issue #2875 resolved

- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/es/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/nl/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
> Issue #2793

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php
**BUGS:**
variant product's images update issue resolved
> variant product's images update issue resolved

- packages/Webkul/Velocity/src/Resources/lang/en/app.php
- packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/index.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/toolbar.blade.php
**BUGS:**
cart count update
nested category route update
#2915
> responsive updates

- packages/Webkul/Core/src/Database/Factories/ChannelFactory.php
- packages/Webkul/Core/src/Database/Factories/ChannelInventorySourceFactory.php
This PR offers two new factories, a ChannelFactory, and a ChannelInventorySourceFactory.
> introduce 2 new factories for channel and channel inventory source

- packages/Webkul/Shop/src/Resources/lang/ja/app.php
**Added Japanese translation**
Hello, I've added a Japanese translation for the `Shop` package.
You can add it to the main bagisto repository if you like.
Thanks for your work.
> Add Japanese translation

- packages/Webkul/Product/src/Type/Configurable.php
**BUGS:**
[Updated: getBaseImage() method updated for configurable product.]
> [Updated: getBaseImage() method updated for configurable product.]

- packages/Webkul/Shop/src/Http/Controllers/OrderController.php
- packages/Webkul/Shop/src/Http/routes.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
**BUGS:**
Cancel feature added in customer order
> Cancel feature added in customer order

- config/services.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
- packages/Webkul/Core/src/Console/Commands/ExchangeRateUpdate.php
- packages/Webkul/Core/src/Helpers/Exchange/ExchangeRate.php
- packages/Webkul/Core/src/Helpers/Exchange/ExchangeRates.php
- packages/Webkul/Core/src/Http/Controllers/ExchangeRateController.php
- packages/Webkul/Core/src/Models/Currency.php
- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
**BUGS:**
Auto exchange rate feature added
> Auto exchange rate feature added

- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
fix category issue and change country,state order.
> fix category issue and change country,state order

- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
max price issue in the category.
> max price issue in category

- CHANGELOG for v1.x.x.md
- config/app.php
> Updated change log

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/index.blade.php
fix add button not translated to other language.
> fix translation in add attribute button

- CHANGELOG for v1.x.x.md
- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Shop/src/Http/Controllers/CartController.php
> Issue #2954 fixed

- CHANGELOG for v1.x.x.md
- packages/Webkul/API/Http/Controllers/Shop/ProductController.php
> Issue #2945 fixed

- CHANGELOG for v1.x.x.md
**BUGS:**
Updated change log file
> Updated change log file

- .env.example
- .env.testing
> Version updated in env files

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
configuration added for favicon in admin
> configuration added for favicon in admin

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php
> Issue #2969

- packages/Webkul/API/Http/Controllers/Shop/CheckoutController.php
See [Issue 2964](https://github.com/bagisto/bagisto/issues/2964)
> resolve issue 2964

- tests/functional/Shop/GuestCheckoutCest.php
Due to some changes in ProductRepository in ordering products, tests/functional/Shop/GuestCheckoutCest will consequentaly fail.
This pr fixes this.
> fix GuestCheckoutCest.php

- packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
> favicon for admin login

- packages/Webkul/Checkout/src/Cart.php
> Issue #2987

- packages/Webkul/Admin/src/Listeners/Order.php
- packages/Webkul/Admin/src/Mail/OrderCommentNotification.php
- packages/Webkul/Admin/src/Providers/EventServiceProvider.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-order-comment.blade.php
**BUGS:**
Order comment email sent to customer
> Order comment email sent to customer

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
**BUGS:**
process checkout as a guest customer for existing customers
> checkout update

- packages/Webkul/Core/src/Contracts/Address.php
- packages/Webkul/Core/src/Models/Address.php
- packages/Webkul/Core/src/Models/AddressProxy.php
**BUGS:**
[Updated: Address's contract, model and proxy classes.]
> [Updated: Address's contract, model and proxy classes.]

- packages/Webkul/Product/src/Repositories/ProductRepository.php
**Problem:** Applying multiple product filters (only 2-3) was taking a very long time. Very often my web server would timeout before the query finished.
**Solution:** I re-wrote the way the filtering component of the query works. Rather than creating one row for every possible combination of product and attribute, it only creates one row for every combination of product and respective attribute and uses an extra group by + having clause.
_NOTE: because of this I had to manually paginate the result set. The Laravel paginate function does not handle GROUP BY's well and it was returning the wrong count result._
> Rebuilt product filter query for improved performance.

- packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
> Issue #3054 fixed

- composer.json
> Issue #3048 fixed

- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/es/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/it/app.php
- packages/Webkul/Shop/src/Resources/lang/ja/app.php
- packages/Webkul/Shop/src/Resources/lang/nl/app.php
- packages/Webkul/Shop/src/Resources/lang/pl/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Shop/src/Resources/views/products/view/stock.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/stock.blade.php
> change translation for #2794

- packages/Webkul/Category/src/Database/Seeders/CategoryTableSeeder.php
> Issue #2762 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-info.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
> Issue #3076 resolved

- packages/Webkul/Shop/src/Resources/lang/ar/app.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/lang/es/app.php
- packages/Webkul/Shop/src/Resources/lang/fa/app.php
- packages/Webkul/Shop/src/Resources/lang/it/app.php
- packages/Webkul/Shop/src/Resources/lang/ja/app.php
- packages/Webkul/Shop/src/Resources/lang/nl/app.php
- packages/Webkul/Shop/src/Resources/lang/pl/app.php
- packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php
> Issue #3079

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/it/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Category/src/Repositories/CategoryRepository.php
- packages/Webkul/Product/src/Helpers/ProductImage.php
- packages/Webkul/Product/src/Helpers/Review.php
- packages/Webkul/Product/src/Helpers/SEO.php
- packages/Webkul/Shop/src/Resources/views/products/index.blade.php
- packages/Webkul/Shop/src/Resources/views/products/view.blade.php
**BUGS:**
Rich snippet feature added for products and category
> Rich snippet feature added for products and category

- packages/Webkul/Shop/src/Resources/views/products/view.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view.blade.php
**BUGS:**
SEO optimization added for velocity and og tag added
> SEO optimization added for velocity and og tag added

- packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
> Issue #3089

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-info.blade.php
**BUGS:**
added one more case as mentioned in #3076
> Added one more case in checkout

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
> Issue #3073

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
> Issue #3097 resolved

- packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php
> Issue #3096 resolved

- packages/Webkul/Core/src/Console/Commands/Install.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
> Issue #3067 fixed

- packages/Webkul/Velocity/src/Resources/assets/js/app.js
- packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
> Issue #2997 resolved

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
> Issue #3041 resolved

- README.md
- composer.lock
**BUGS:**
Install command updated
> Install command updated

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/index.blade.php
to align it as it is in products/index.blade.php
> adjust cart rule filter position a few pixels

- resources/lang/nl/auth.php
- resources/lang/nl/pagination.php
- resources/lang/nl/passwords.php
- resources/lang/nl/validation.php
I added the dutch translations to `resources/lang/nl`.
> Add dutch laravel translations

- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-invoice.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-refund.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/review.blade.php
Hi @vaishaliwebkul ,
this PR adds address field "company_name" to views.
Please have a look.
> add field company_name to views

- package.json
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/Ui/src/Resources/assets/js/components/datetime.vue
- public/mix-manifest.json
- tests/functional/Customer/CustomerCest.php
Closes #3026
- I entered a missing configuration parameter in the vue-flatpickr component
- There is a known bug in vee-validate concerning the date_format validation rule. Because vee-validate version 2 is no longer supported, I followed the developer's suggestion [in this comment](https://github.com/logaretm/vee-validate/issues/2524#issuecomment-568306359) and implemented a custom date_format validation rule as workaround.
> #3026 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php
> Issue #1522 resolved

- packages/Webkul/Category/src/Repositories/CategoryRepository.php
> Issue #3021

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/BookingProduct/src/Helpers/Booking.php
- packages/Webkul/BookingProduct/src/Helpers/EventTicket.php
- packages/Webkul/BookingProduct/src/Helpers/RentalSlot.php
- packages/Webkul/CartRule/src/Helpers/CartRule.php
- packages/Webkul/Product/src/Contracts/ProductCustomerGroupPrice.php
- packages/Webkul/Product/src/Database/Migrations/2020_05_21_171500_create_product_customer_group_prices_table.php
- packages/Webkul/Product/src/Models/Product.php
- packages/Webkul/Product/src/Models/ProductCustomerGroupPrice.php
- packages/Webkul/Product/src/Models/ProductCustomerGroupPriceProxy.php
- packages/Webkul/Product/src/Providers/ModuleServiceProvider.php
- packages/Webkul/Product/src/Repositories/ProductCustomerGroupPriceRepository.php
- packages/Webkul/Product/src/Type/AbstractType.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Product/src/Type/Downloadable.php
**BUGS:**
Added customer group price
> Added customer group price

- packages/Webkul/Product/src/Type/Bundle.php
**BUGS:**
Fixed bundle type class compatablity issue
> Fixed bundle type class compatablity issue

- packages/Webkul/Product/src/Helpers/Toolbar.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Product/src/Type/Configurable.php
> Issue #3164 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/sliders/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/sliders/edit.blade.php
It would be helpful if we would have more tools in the TinyMCE backend editor. I added a few more functionalities such as inserting tables, lists, links and horizontal rules.
> Extend CMS editor functionality

- packages/Webkul/Product/src/Type/Bundle.php
> check if product_id exists

- packages/Webkul/Product/src/Helpers/Toolbar.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
> Issue #3113 fixed

- packages/Webkul/Product/src/Type/Bundle.php
Fixed case sensitivity typo in Bundle class
> Fixed case sensitivity typo in Bundle class

- packages/Webkul/Product/src/Database/Migrations/2020_05_21_171500_create_product_customer_group_prices_table.php
**BUGS:**
Fixed typo in customer group price migration
> Fixed typo in customer group price migration

- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #3171 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
> Issue #3070 fixed

- packages/Webkul/Admin/webpack.mix.js
- packages/Webkul/Product/src/Helpers/BundleOption.php
- packages/Webkul/Product/src/Type/Bundle.php
> Issue #3160 fixed

- packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
> Issue #3172 resolved

- .gitignore
- app/Exceptions/Handler.php
- composer.json
- composer.lock
- config/session.php
- packages/Webkul/Attribute/src/Database/Factories/AttributeOptionFactory.php
- packages/Webkul/Core/src/Exceptions/Handler.php
**BUGS:**
Migrate to laravel 7
> Migrate to laravel 7

- packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php
- packages/Webkul/Customer/src/Database/Factories/CustomerFactory.php
**BUGS:**
Replace array_random function to Arr:random
> Replace array_random function to Arr:random

- packages/Webkul/Product/src/Type/Grouped.php
- packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/locale-currency.blade.php
> Issue #3202 resolved

- packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/locale-currency.blade.php
> Issue #3204 resolved

- packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
- packages/Webkul/Customer/src/Http/Controllers/ForgotPasswordController.php
- packages/Webkul/Product/src/Http/Controllers/ProductController.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view.blade.php
> #3197 solved

- packages/Webkul/Velocity/src/Helpers/Helper.php
- packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
- packages/Webkul/Velocity/src/Providers/VelocityServiceProvider.php
- packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
velocity meta data locale support updates
> velocity meta data locale support updates

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php
- packages/Webkul/Product/src/Type/Grouped.php
- packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/locale-currency.blade.php
**BUGS:**
some changes were removed from code. This PR will add those changes again
> added previous changes

- packages/Webkul/API/Http/Controllers/Shop/ForgotPasswordController.php
- packages/Webkul/User/src/Http/Controllers/ForgetPasswordController.php
> Issue #3238 resolved

- packages/Webkul/Checkout/src/Database/Factories/CartItemFactory.php
- packages/Webkul/Sales/src/Database/Factories/OrderItemFactory.php
This PR aims to extend two factories: The OrderItemFactory and the CartItemFactory.
Tests using those enhanced factories will flicker less likely.
> extend two factories

- app/Http/Middleware/VerifyCsrfToken.php
**BUGS:**
Fixed paypal ipn csrf issue
> Fixed paypal ipn csrf issue

- composer.json
- composer.lock
- packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
**BUGS:**
Homepage 404 issue fixed
> Homepage 404 issue fixed

- packages/Webkul/API/Http/Controllers/Shop/ForgotPasswordController.php
- packages/Webkul/User/src/Http/Controllers/ForgetPasswordController.php
> Revert "Issue #3238 resolved"

- packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/multiselect.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/select.blade.php
> Issue #3237 fixed

- packages/Webkul/BookingProduct/src/Models/Booking.php
- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/slider.blade.php
> Issue #3219 fixed

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
**BUGS:**
Issue fixed if booking product is null
> Issue fixed if booking product is null

- config/debugbar.php
- config/excel.php
- config/tinker.php
- packages/Webkul/Shop/src/Resources/lang/it/app.php
- packages/Webkul/Shop/src/Resources/lang/pl/app.php
- resources/views/errors/503.blade.php
- resources/views/vendor/mail/html/button.blade.php
- resources/views/vendor/mail/html/header.blade.php
- resources/views/vendor/mail/html/themes/default.css
- resources/views/vendor/notifications/email.blade.php
- resources/views/vendor/pagination/simple-tailwind.blade.php
- resources/views/vendor/pagination/tailwind.blade.php
> Issue #3254 fixed

- CHANGELOG for v1.x.x.md
> Updated change file

- packages/Webkul/Sales/src/Database/Factories/OrderItemFactory.php
This PR extends the OrderItemFactory with the field "additional".
> OrderItemFactory extension

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
> Issue #3272 fixed

- CHANGELOG for v1.x.x.md
**BUGS:**
Fixed typo in changelog
> Fixed typo in changelog

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
> Issue #3289 fixed

- packages/Webkul/Paypal/src/Helpers/Ipn.php
> Issue #2981 fixed

- packages/Webkul/Shop/src/Resources/views/customers/account/partials/sidemenu.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/partials/sidemenu.blade.php
**BUGS:**
remove compare option from customer sidebar
> remove compare option from customer sidebar

- packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php
> Issue #3301 fixed

- packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/rental.blade.php
- packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/rental.blade.php
> Issue #3319 fixed

- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
> Issue #3320 fixed

- packages/Webkul/User/src/Http/Controllers/ForgetPasswordController.php
> Issue #3314 fixed

- packages/Webkul/Velocity/src/Database/Seeders/VelocityMetaDataSeeder.php
**BUGS:**
default compare option enable
> default compare option enable

- packages/Webkul/Core/src/Config/concord.php
> Issue #3374 fixed

- packages/Webkul/SocialLogin/src/Database/Migrations/2020_06_25_162340_change_email_password_columns_in_customers_table.php
> Issue #3373 fixed

- packages/Webkul/SocialLogin/src/Http/Controllers/LoginController.php
**BUGS:**
Added exception handler during social login redirect
> Added exception handler during social login redirect

- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- packages/Webkul/Tax/src/Database/Migrations/2020_06_30_163510_remove_unique_name_in_tax_categories_table.php
- packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php
> Issue #3354 fixed

- packages/Webkul/Velocity/src/Database/Seeders/VelocityMetaDataSeeder.php
**BUGS:**
compare option default value for en locale
> compare option default value for en locale

- packages/Webkul/SocialLogin/src/Repositories/CustomerSocialAccountRepository.php
> Issue #3395 and #3396 fixed

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/de/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/it/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/lang/tr/app.php
> Issue #3392 fixed

- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #3411 fixed

- storage/framework/cache/data/.gitignore
**BUGS:**
Inlcuded storage/cache/data folder
> Inlcuded storage/cache/data folder

- packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/pagination.blade.php
> issue #3426 fixed

- config/elastic.scout_driver.php
- packages/Webkul/Core/src/Config/scout.php
- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
**BUGS:**
Now, default scout driver will be set as null even after force vendor publish
> Issue #3425 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
> Issue #3409 fixed

- packages/Webkul/Sales/src/Repositories/OrderRepository.php
**BUGS:**
The `$data` is not passed properly to the Listener of the `checkout.order.save.before` event. This PR fixes it.
> properly pass the data array into the 'checkout.order.save.before' event

- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
**BUGS:**
Fixed issue in order view page if customer group is null
> Fixed issue in order view page if customer group is null

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php
> Issue #3423 fixed

- packages/Webkul/Product/src/Type/AbstractType.php
> Issue #3443 fixed

- packages/Webkul/Shop/src/Resources/lang/en/app.php
> Issue #3460 fixed

- packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/SocialLogin/src/Database/Seeders/CustomerSocialAccountTableSeeder.php
- packages/Webkul/SocialLogin/src/Database/Seeders/DatabaseSeeder.php
> issue #3447 fixed

- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Product/src/Type/Virtual.php
**BUGS:**
Virtual inventory issue fixed
> Virtual inventory issue fixed

- packages/Webkul/Ui/src/Resources/lang/pl/app.php
- packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php
**BUGS:**
Chinese locale search issue fixed
> Chinese locale search issue fixed

- packages/Webkul/Product/src/Repositories/ProductRepository.php
**BUGS:**
On setting limit 0 exception is caused.
Issue Link: https://github.com/bagisto/bagisto/issues/3478
> Category filter limit zero issue fixed #3478

- packages/Webkul/Ui/src/Resources/lang/pl/app.php
**BUGS:**
Error on PL lang file #3508
> Issue #3508 fixed

- packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
- packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
- packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
> Issue #3505 fixed

- packages/Webkul/Shop/src/Resources/lang/en/app.php
> issue #3514 resolved

- packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
Side bar menu is getting removed while editing/adding customer address --  fixed #3502 
https://prnt.sc/tjieph here is the screenshot of fixed issue
> fixed issue #3502 

- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/cart-rules/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/create.blade.php
- packages/Webkul/Admin/src/Resources/views/promotions/catalog-rules/edit.blade.php
> Issue #3490 fixed

- packages/Webkul/Admin/src/Http/Controllers/Sales/ShipmentController.php
- packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
- packages/Webkul/Core/src/Providers/CoreServiceProvider.php
- packages/Webkul/Core/src/Resources/views/blade/tracer/style.blade.php
> Issue #3451 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3487
> Fixed Velocity RTL product image zoom floats right - not showing #3487

- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Product/src/Type/Bundle.php
- packages/Webkul/Product/src/Type/Grouped.php
**BUGS:**
Issue in sales icon of grouped and bundles projects are now solved.
Issue Link: https://github.com/bagisto/bagisto/issues/3489
> Sales icon issue fixed in grouped as well as bundle #3489

- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Product/src/Type/Configurable.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3535
> Fixed sort by configuration from admin end is not working properly #3535

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3574
> Fixed one page checkout loader hits on adding single digit in phone number

- packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Product/src/Type/Configurable.php
- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
> Issue #3561 fixed

- packages/Webkul/Core/src/Models/Country.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/review.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/review.blade.php
> Issue #3547 fixed

- packages/Webkul/Core/src/Models/Country.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/review.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/review.blade.php
> Revert "Issue #3547 fixed"

- packages/Webkul/CartRule/src/Helpers/CartRule.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3554
> CartRule Issue Fixed #3554

- packages/Webkul/CartRule/src/Helpers/CartRule.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3556
> Fixed auto generated coupon codes are not getting applied #3556

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3487
> RTL Dynamic Issue Fixed #3487

- packages/Webkul/Product/src/Type/Bundle.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3577
> Fixed customer is able to place order of more than available qty of any bundle option product #3557

- packages/Webkul/Checkout/src/Cart.php
- packages/Webkul/Shipping/src/Shipping.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3546
> Fixed shipping charge is not getting calculated properly #3546

- packages/Webkul/Product/src/Repositories/ProductRepository.php
> Issue #3591 fixed

- packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
> cancel button position fixed #3521

- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
> Issue #2971 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/reviews.blade.php
> Issue #3604 fixed

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
> Issue #3548 resolved

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
- packages/Webkul/Velocity/src/Resources/assets/js/app.js
- packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/category.blade.php
> Issue #3631 resolved

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
- packages/Webkul/Velocity/src/DataGrids/ContentDataGrid.php
> Issue #3629 resolved

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
- packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
- packages/Webkul/Velocity/src/Http/Controllers/Admin/ContentController.php
> Issue #3628 resolved

- packages/Webkul/Product/src/Type/Configurable.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3642
> Fixed getting exception when creating configurable product in case of DB_Prefix #3642

- packages/Webkul/Admin/src/Listeners/Order.php
- packages/Webkul/Admin/src/Mail/CancelOrderAdminNotification.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel-admin.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3522
> Fixed admin is not getting mail when customer cancels order #3522

- packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3570
> Fixed translation issue on uploading high size image #3570

- packages/Webkul/Customer/src/Notifications/CustomerUpdatePassword.php
- packages/Webkul/User/src/Notifications/AdminUpdatePassword.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3526
> Just updated the comments in the customer and admin file.

- packages/Webkul/Shop/src/Resources/views/products/view/grouped-products.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/grouped-products.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3575
> Fixed inactive child product shouldn't visible in grouped product #3575

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
> Issue #3649 fixed

- packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/refunds/view.blade.php
- packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
- packages/Webkul/Customer/src/Repositories/CustomerRepository.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3422
> Fixed getting exception when view order of deleted customer #3422

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/attributes.blade.php
> Issue #3648 fixed

- packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3637
>  Fixed no records founds text in downloadable product section of customer should display in centre, in mobile view #3637 

- packages/Webkul/Paypal/src/Helpers/Ipn.php
update invoice status paid using paypal.
> update invoice status paid using paypal

- packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3534
> Fixed add validation for products per page field otherwise if admin entered string value then customer gets exception on category page #3534 

- packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3534
> Message Added To This Issue #3534

- packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3505
> Message Added In Velocity And Velocity Guest #3505

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
> Issue #3564 fixed

- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/index.blade.php
> Issue #3675 resolved

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3243
> Fixed email settings are empty in backend #3243

- packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3365
> Fixed on mobile responsive on ios sign up button is missing #3365

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
**BUGS:**
Issue 1: https://github.com/bagisto/bagisto/issues/3656
Issue 2: https://github.com/bagisto/bagisto/issues/3692
Issue 3: https://github.com/bagisto/bagisto/issues/3507
> Fixed #3507, #3656 and #3692

- packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3693
> Fixed there should not be any success message while trying to delete system attributes #3693

- packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
- packages/Webkul/Velocity/src/Helpers/Helper.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
> Issue #3494 fixed

- config/modules.php
- config/themes.php
- packages/Webkul/Theme/src/ThemeViewFinder.php
- packages/Webkul/Theme/src/Themes.php
> Revert "Multi theme system now supported in admin"

- config/themes.php
- packages/Webkul/Theme/src/ThemeViewFinder.php
- packages/Webkul/Theme/src/Themes.php
> Support multi admin theme

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3656
Added 3 columns in group by query and then added where clause.
> Fixed #3656

- packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3704
> Fixed no alert message while deleting customer with pending or processing order from admin end #3704

- packages/Webkul/Attribute/src/Models/AttributeFamily.php
- packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
Compare feature update
#3498
#3496
#3494
#3486
> Compare feature update

- packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- packages/Webkul/Shop/src/Resources/views/products/compare.blade.php
- packages/Webkul/Velocity/src/Http/Controllers/Shop/Controller.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
compare count update in default theme
> compare count update in default theme

- packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
- packages/Webkul/Theme/src/Themes.php
**BUGS:**
Issue #3720 resolved
> Issue #3720 resolved

- packages/Webkul/CartRule/src/Helpers/CartRule.php
> Issue #3638 fixed

- packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
Issue #3727 #3725 resolved
> Issue #3727 #3725 resolved

- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
> Issue #3700 fixed

- packages/Webkul/BookingProduct/src/Database/Factories/BookingProductFactory.php
- packages/Webkul/BookingProduct/src/Type/Booking.php
- packages/Webkul/Checkout/src/Cart.php
- tests/unit/Checkout/CartCest.php
- fixed a bug in BookingProductFactory (type was wrongly set)
- fixed a bug in Type/Booking (data array key was missing)
- refactoring of method mergeCart() in Cart.php (we should use the method addProduct() to add new products to the shopping cart of registered customers)
- unit test for method mergeCart() added
> refactoring of cart.php, fix issue in booking product, 

- packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3745
> Fixed getting exception in backend when having DB_PREFIX #3745

- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3742
> Fixed invoice, ship and cancel buttons are missing in order placed by guest user #3742

- packages/Webkul/CMS/src/Database/Migrations/2020_07_31_142021_update_cms_page_translations_table_field_html_content.php
**BUGS:**
> Fix the content of CMS page is cropped
> See #3611
> Update cms_page_translations table field html content from text to longtext

- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3751
> Fixed shipping tab is missing in order details for deleted customer #3751

- packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/category.blade.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/edit-product.blade.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/edit.blade.php
**BUGS:**
Issue #3747 resolved
> Issue #3747 resolved

- packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
- packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
> change code

- public/installer/EmailConfig.php
> Issue #3755 fixed

- packages/Webkul/Velocity/src/Database/Migrations/2020_08_17_104228_add_channel_to_velocity_meta_data_table.php
- packages/Webkul/Velocity/src/Helpers/Helper.php
- packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
**BUGS:**
Fixed: https://github.com/bagisto/bagisto/issues/3735
> Fixed velocity meta data section channel wise #3735

- packages/Webkul/Velocity/src/DataGrids/ContentDataGrid.php
- packages/Webkul/Velocity/src/Resources/views/admin/content/edit.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3747
> Fixed velocity content header route throwing an exception in spanish locale #3747

- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
**BUGS:**
Still there are some static values. Dynamic added.
> Static Value Removed

- CHANGELOG for v1.x.x.md
removed unnecessary data from chnagelog
> removed unnecessary data from chnagelog

- packages/Webkul/Theme/src/ThemeViewFinder.php
- packages/Webkul/Theme/src/Themes.php
- tests/unit/Checkout/CartCest.php
In commit 76afd93, the scenarios of the test for merging a guest customer's cart with the logged in customer's cart have been switched off, thus, making the test senseless, actually.
In my opinion, tests are very important, preventing us to merge faulty code into our live and productive systems. 
So I have taken the liberty to fix, refactor and extend the test, to give it a meaning again.
> Fix test for merging customer carts

- packages/Webkul/Velocity/src/Database/Seeders/VelocityMetaDataSeeder.php
- packages/Webkul/Velocity/src/Repositories/ContentRepository.php
**BUGS:**
velocity meta content channel issue resolved
> velocity meta content channel issue resolved

- packages/Webkul/Velocity/src/Resources/views/shop/products/list/recently-viewed.blade.php
> Issue #3792 fixed

- packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
Hello again, 
I added tables, lists and links to the wysiwyg editor for CMS pages.
> Expand wysiwyg editor for cms pages

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
**BUGS:**
#3785
Updated Code For Product Filter Problem #3785
> Update Product channel problem #3785

- packages/Webkul/API/Http/Resources/Checkout/Cart.php
- packages/Webkul/API/Http/Resources/Sales/Order.php
- packages/Webkul/API/Http/Resources/Sales/OrderItem.php
Hello again,
I have added some data to the return arrays of some API endpoints, that can be useful for pretty frontend works.
> minor expansion of api return data

- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
**BUGS:**
#3800 
Fix Header Content Count field Problem #3800
> Fix Header Content Count field Problem #3800

- packages/Webkul/Admin/src/DataGrids/NewsLetterDataGrid.php
**BUGS:**
#3789
Fixed Newsletter Subscription Problem #3797
> Fix Newsletter Subscription Problem #3789

- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
> Issue #3786 fixed

- config/app.php
- packages/Webkul/Core/src/Providers/EnvValidatorServiceProvider.php
**BUGS:**
https://github.com/bagisto/bagisto/issues/3782
> Fixed getting error on running php artisan migrate if db_prefix contains decimal value #3782

- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
Issue: https://github.com/bagisto/bagisto/issues/3643
UTF-8 Added.
> UTF-8 And Font Added #3643

- packages/Webkul/Core/src/Helpers/Laravel5Helper.php
**BUGS:**
Laravel5Helper.php contains some useful methods to generate different types of products for use in tests.
Currently some product attribute values do not contain all necessary fields to be valid.
**solution**
This PR corrects the creation of product attribute values.
> fix product generation for tests

- packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
**BUGS:**
Issue: https://github.com/bagisto/bagisto/issues/3643
> Some Minor Encoding Issue Fixed

- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
> Issue 3852 fixed

- packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
> Issue #3847 fixed

- packages/Webkul/Customer/src/Http/Controllers/ForgotPasswordController.php
- packages/Webkul/Customer/src/Resources/lang/en/app.php
- packages/Webkul/User/src/Http/Controllers/ForgetPasswordController.php
> Fixed Issue #3854

- packages/Webkul/Shop/src/Resources/views/emails/layouts/master.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
Some Minor CSS Changed On Mail
> Minor CSS Changed

- .gitignore
- resources/lang/de/auth.php
- resources/lang/de/pagination.php
- resources/lang/de/passwords.php
- resources/lang/de/validation.php
- resources/lang/en/auth.php
- resources/lang/en/pagination.php
- resources/lang/en/passwords.php
- resources/lang/en/validation.php
- resources/lang/nl/auth.php
- resources/lang/nl/pagination.php
- resources/lang/nl/passwords.php
- resources/lang/nl/validation.php
- resources/lang/pt_BR/auth.php
- resources/lang/pt_BR/pagination.php
- resources/lang/pt_BR/passwords.php
- resources/lang/pt_BR/validation.php
1. Added all lang files back.
2. Added admin folder to git ignore.
> Some Error Fixes

- packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/address/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/downloadable_products/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3872
> Fixed #3872

- packages/Webkul/Sales/src/Repositories/OrderRepository.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3895
> Number Of Invoiced Added #3895

- packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
- packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3907
> Instructions Added #3907

- packages/Webkul/Sales/src/Database/Migrations/2020_09_07_120413_add_unique_index_to_increment_id_in_orders_table.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3902
**Info:**
1. Added migration file which alters the `orders` table column's `increment_id` as unique.
> Fixed #3902

- packages/Webkul/SocialLogin/src/Http/Controllers/LoginController.php
**BUGS:**
https://github.com/bagisto/bagisto/issues/3886
1. Added event dispatcher in the method.
2. Sorted Imports.
> Social login cart merging

- packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
> Issue #3890 Fixed

- packages/Webkul/Core/src/Console/Commands/Install.php
Update Install.php 
Ask for enter app url #3940
> Update Install.php #3940

- packages/Webkul/Core/src/Console/Commands/Install.php
Config cache added. For caching new changes.
> Config Cache Added

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
- packages/Webkul/Admin/src/Resources/lang/de/app.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/lang/es/app.php
- packages/Webkul/Admin/src/Resources/lang/fa/app.php
- packages/Webkul/Admin/src/Resources/lang/it/app.php
- packages/Webkul/Admin/src/Resources/lang/nl/app.php
- packages/Webkul/Admin/src/Resources/lang/pl/app.php
- packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
- packages/Webkul/Admin/src/Resources/lang/tr/app.php
- packages/Webkul/Payment/src/Config/paymentmethods.php
- packages/Webkul/Payment/src/Providers/PaymentServiceProvider.php
- packages/Webkul/Paypal/src/Config/paymentmethods.php
- packages/Webkul/Paypal/src/Config/system.php
- packages/Webkul/Paypal/src/Helpers/Ipn.php
- packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
- packages/Webkul/Paypal/src/Http/routes.php
- packages/Webkul/Paypal/src/Payment/SmartButton.php
- packages/Webkul/Paypal/src/Providers/EventServiceProvider.php
- packages/Webkul/Paypal/src/Providers/PaypalServiceProvider.php
- packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Added paypal smart payment button method
> Added paypal smart payment button method

- packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php
> Issue #3956 fixed

- packages/Webkul/Admin/src/Config/system.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Resources/views/home/featured-products.blade.php
- packages/Webkul/Shop/src/Resources/views/home/new-products.blade.php
- packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/featured-products.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/home/new-products.blade.php
Add new and featured Product Config
> Add new and featured Product Config

- packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
We recently received some error messages in our log files, saying: "Trying to get property 'qty_ordered' of non-object".
With the error message came the piece of code throwing the exception, so we were pretty sure, that a customer ordered a product that neither had the attribute `qty_ordered` nor had a parent product with that attribute.
But we could not reproduce that issue. That is why I added some logging to catch the context of any further exception. 
And even more helpful, I hope, might be the work around to handle the `ordered_inventory` of the product only if the product already has an inventory. 
For instance, a downloadable product does not have an inventory, but would get an `ordered_inventory` earlier.
As we could not reproduce the issue itself, as mentioned above, I do not …
> work around a non-reproducable exception 

- config/repository.php
- packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
> Issue #3964 fixed

- config/repository.php
- packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
**Links**:
https://github.com/bagisto/bagisto/issues/3656
https://github.com/bagisto/bagisto/issues/3909
**Info**:
1. Added one more key to group by.
2. I am refrencing to this PR https://github.com/bagisto/bagisto/pull/3844, as this PR is merged so that means fallback is not needed. So in the product datagrids if all is selected then all product flat item should be shown.
> Fixed Name Issue #3656 and #3909

- packages/Webkul/Product/src/Type/Configurable.php
> Issue #3957 fixed

- packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
> fixed #3985

- packages/Webkul/Shop/src/Resources/views/products/view.blade.php
**BUGS:**
I have solved the html code showing while sharing the product on social media (Facebook)
HTML code showing while sharing because  of appropriate syntax usage in Laravel blade file that i have corrected
> Issue #3945 Fixed

- packages/Webkul/Core/src/Http/Controllers/ChannelController.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3967
> Fixed trying to get property of non object #3967

- packages/Webkul/API/Http/Controllers/Shop/CartController.php
- packages/Webkul/API/Http/Controllers/Shop/CustomerController.php
- packages/Webkul/Core/src/Exceptions/Handler.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3973
1. Fixed responses issue.
2. As the `request()` method is called multiple times, so uses the reflection API method for the request.
3. Fixed route `auth.login` to the customer login page.
> Fixed response issues in APIs #3973

- packages/Webkul/API/Http/Controllers/Shop/ReviewController.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3977
> Fixed no validation error message are shown on submitting review without required params via API #3977

- packages/Webkul/API/Http/Controllers/Shop/AddressController.php
> Issue #3981 fixed

- packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/3980
> Fixed color swatch issue #3980

- packages/Webkul/Paypal/src/Config/paymentmethods.php
> Issue #4031 Fixed

- packages/Webkul/Shop/src/Resources/views/home/featured-products.blade.php
- packages/Webkul/Shop/src/Resources/views/home/new-products.blade.php
> Issue #4030 Fixed

- packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
**BUG:**
>Fixed filter issue in cart rule, slider grid & product grid.
Issue id: #4023
> Fixed filter issue in admin panel #4023

- packages/Webkul/Admin/src/Resources/views/customers/general.blade.php
fixed issue #3983  for more info follow the link
> fixed issue #3983

- packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/customers/create.blade.php
**BUGS:**
See #4019 
Adding date format placeholder on `date_of_birth` field in Customer create page. The date picker is not appear on safari, I suggest to use external library for date picker in the new update.
> fix: showing success message on deleting

- packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
> Issue 3950 Fixed

- packages/Webkul/Product/src/Helpers/View.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4037
> Continue Added #4037

- packages/Webkul/Admin/src/Config/system.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4038
> Required Removed #4038

- packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
> Issue #4045 Fixed

- packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4049
> Decode Function Added #4049

- config/products.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4003
I am referencing to this PR https://github.com/bagisto/bagisto/pull/3853. As in Laravel, config file closures are not accepted. So I just turned that to `null` to avoid code breakage.
> Config Cache Issue Fixed #4003

- packages/Webkul/API/Http/Controllers/Shop/SessionController.php
**BUGS:**
I have fixed **issue #id** by keeping the existing code of conduct.
Another method that we can fix it by using
$validator = Validator::make($request->all(), [
'first_name'    => 'required',
'last_name'     => 'required',
'gender'        => 'required',
'date_of_birth' => 'nullable|date|before:today',
'email'         => 'email|unique:customers,email,' . $customer->id,
'password'      => 'confirmed|min:6',
]);
if ($validator->fails()) {
return redirect()
->withErrors($validator)
->withInput();
}
> Otherwise use **issue #id** if the issue was …
> Fixed #3974 (Validation Message Shown now)

- packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
Added partner id to payap smart button
> Added partner id to payap smart button

- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
> Fixed Search bar issue #3917

- packages/Webkul/Product/src/Helpers/ProductImage.php
- packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/list/card.blade.php
> Issue #4061 Fixed

- packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
Added flash message if paypal client id is invalid
> Added flash message if paypal client id is invalid

- packages/Webkul/Product/src/Type/AbstractType.php
**BUG:**
>Customer group price discount is not applied when the product price and discount amount is the same
**Issue ID #4024** Fixed.
> Fixed customer group price discount issue

- packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
Fixed invalid client id issue in velocity
> Fixed invalid client id issue in velocity

- packages/Webkul/Product/src/Config/imagecache.php
Change product image cache expire time
> Change product image cache expire time

- packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4086
> Fixed add to cart button is not coming completely on compare page #4086

- packages/Webkul/API/Http/Controllers/Shop/InvoiceController.php
- packages/Webkul/API/Http/routes.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4085
Method changed on a different controller to avoid changes in resource one.
> Fixed Invoice API Issue #4085

- packages/Webkul/Ui/src/DataGrid/DataGrid.php
> Url decode to fix special characters in product names

- packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
- packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4125
> Current channel code sent as a params #4125

- packages/Webkul/Shop/src/Resources/views/products/compare.blade.php
fixed  compare icon issue in RTL #4121
https://prnt.sc/v3q8gw
> fixed compare icon in RTL #4121

- packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php
Issue #4130
**BUGS:**
>Add decimal and min validation to event ticket price field on the admin dashboard
> event ticket price field shouldn't accept negative

- packages/Webkul/BookingProduct/src/Type/Booking.php
**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4117
> Fixed error in booking product while booking a slot #4117

- packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
**BUGS:**
>The Wishlist icon should not be visible for guest user in the checkout page.
>This issue is now fixed.
> Issue #4107 is fixed

- packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
- packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php
**BUGS:**
>Multi-product images will be changed on mouse hover.
**Issue ID : #4132**
> Product image change on mouse hover

- packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
> Add hostname to default channel on seeder #4162

- packages/Webkul/Admin/src/Resources/lang/ar/app.php
I'm starting to provide the right translation because there are a lot of errors in the translation.
> Updated some words (arabic)
