bagisto/bagisto

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php

fixed issue #4113

---

packages/Webkul/Product/src/Helpers/Toolbar.php

fixed issue #4110

---

packages/Webkul/API/Http/Controllers/Shop/InvoiceController.php
packages/Webkul/API/Http/Controllers/Shop/ResourceController.php
packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php

Fixed this error and other files with same code.
Trying to get property 'direction' of non-object (View: /packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php)
Same fix as this but applied to all files:
https://github.com/bagisto/bagisto/pull/2238/commits/8f2d1779ee67b74b62e2da0c5933b47f9d8bdbe5

Fix error with missing locale and error with route:list

---

packages/Webkul/Ui/src/DataGrid/DataGrid.php

Issue #3975 Fixed

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php

**BUGS:**
#4081
>Add max value for discount amount field in the edit catalog product customer group price

add validation for discount amt field in customer group price

---

packages/Webkul/Paypal/src/Config/paymentmethods.php
packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php

Paypal smart button issue fixed

Paypal smart button issue fixed

---

packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php

Removed commented code from paypal smart button controller

Removed commented code from paypal smart button controller

---

packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
packages/Webkul/Admin/src/Http/routes.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
packages/Webkul/Category/src/Http/Controllers/CategoryController.php
packages/Webkul/Category/src/Models/Category.php
packages/Webkul/Ui/src/Resources/lang/ar/app.php
packages/Webkul/Ui/src/Resources/lang/de/app.php
packages/Webkul/Ui/src/Resources/lang/en/app.php
packages/Webkul/Ui/src/Resources/lang/fa/app.php
packages/Webkul/Ui/src/Resources/lang/it/app.php
packages/Webkul/Ui/src/Resources/lang/nl/app.php
packages/Webkul/Ui/src/Resources/lang/pl/app.php
packages/Webkul/Ui/src/Resources/lang/pt_BR/app.php
packages/Webkul/Ui/src/Resources/lang/tr/app.php
packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/partials/mass-action-header.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

**ENHANCEMENT:**
>Added option to delete multiple categories by selecting a mass category.
**Issue ID : #4082**

Added bulk category delete functionality

---

packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4136

Wishlist check added in header #4136

---

packages/Webkul/Velocity/src/Resources/views/shop/home/slider.blade.php

**BUGS:**
Carousel RTL locale-direction value was null 
Issue from live demo 
https://www.loom.com/share/e092367576884b92b610af5eddfb7430

Bugfix carousel RTL

---

packages/Webkul/Paypal/src/Providers/EventServiceProvider.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4267
I just commented the code in the provider because we are calling DB before registering the database. This code should be somewhere else because DB is calling before its registry.

Installation errors during composer install #4267

---

packages/Webkul/Velocity/src/Resources/views/shop/products/index.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4269

Fixed error on loading category page results whoops no product found in mobile view #4269

---

packages/Webkul/Product/src/Http/Requests/ProductForm.php

Issue #4294 fixed, max video file size validation for video.

Issue #4294 fixed

---

packages/Webkul/Product/src/Helpers/Toolbar.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4110#issuecomment-733034206

Fixed layout mode default select grid issue #4110

---

packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php

**BUGS:**
>Enable/Disable issue in Image search functionality in velocity theme
**issue #4335**
**FIX:** 
>Added missing condition in velocity theme.
Fixed string issue in condition check

Image search functionality enable/disable issue solved in velocity theme.

---

packages/Webkul/Velocity/src/Resources/lang/ar/app.php
packages/Webkul/Velocity/src/Resources/lang/de/app.php
packages/Webkul/Velocity/src/Resources/lang/en/app.php
packages/Webkul/Velocity/src/Resources/lang/fa/app.php
packages/Webkul/Velocity/src/Resources/lang/it/app.php
packages/Webkul/Velocity/src/Resources/lang/ja/app.php
packages/Webkul/Velocity/src/Resources/lang/nl/app.php
packages/Webkul/Velocity/src/Resources/lang/pl/app.php
packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
packages/Webkul/Velocity/src/Resources/lang/tr/app.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php

fixed issue #4329

---

packages/Webkul/Attribute/src/Repositories/AttributeOptionTranslationRepository.php
packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php

added repository for attribute option translations

added repository for attribute option translation

---

packages/Webkul/Velocity/src/Resources/views/shop/home/category-with-custom-option.blade.php

code enhancement

---

packages/Webkul/Checkout/src/Http/Requests/CustomerAddressForm.php

**INFO:**
Vulnerability In Address Issue Fixed.

Vulnerability In Address Issue Fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4325

Fixed address is not saving on onepage checkout #4325

---

resources/lang/fa/auth.php
resources/lang/fa/pagination.php
resources/lang/fa/passwords.php
resources/lang/fa/validation.php

> translation files for persian farsi language created
>   **issue #4349 **

Translation files for persian language

---

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4359

Fixed some fields in admin configuration are not saving #4359

---

packages/Webkul/Attribute/src/Database/Seeders/AttributeTableSeeder.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4372

Brand attribute is now deletable #4372

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Checkout/src/Database/Migrations/2020_12_18_122826_add_is_tax_calculation_column_to_cart_shipping_rates_table.php
packages/Webkul/Shipping/src/Carriers/FlatRate.php
packages/Webkul/Shipping/src/Carriers/Free.php
packages/Webkul/Shipping/src/Config/carriers.php
packages/Webkul/Shipping/src/Config/system.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4350

Fixed taxes not applied to Shipping Cost #4350

---

public/installer/MigrationRun.php
public/installer/Views/migration.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4371
Actually logs are already coming just need to display the log box.

Fixed web install should return details when failing #4371

---

README.md

PHP version in readme updated

---

packages/Webkul/Admin/src/DataGrids/ChannelDataGrid.php
packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/index.blade.php
packages/Webkul/Core/src/Contracts/ChannelTranslation.php
packages/Webkul/Core/src/Database/Migrations/2020_12_21_000200_create_channel_translations_table.php
packages/Webkul/Core/src/Database/Migrations/2020_12_21_140151_remove_columns_from_channels_table.php
packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
packages/Webkul/Core/src/Http/Controllers/ChannelController.php
packages/Webkul/Core/src/Models/Channel.php
packages/Webkul/Core/src/Models/ChannelTranslation.php
packages/Webkul/Core/src/Models/ChannelTranslationProxy.php
packages/Webkul/Core/src/Repositories/ChannelRepository.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4380
**STEPS:**
- Run `composer dump-autoload`.
- Run `php artisan optimize`.
- Run `php artisan migrate`.
- Run `php artisan db:seed`.
Channel seeder has been updated, so if someone use this pr will need to take a backup of their channels table because some columns are moved to `channel_translations`.

Enhancement completed locale wise channel settings

---

packages/Webkul/User/src/Database/Seeders/RolesTableSeeder.php

Fix the 'role' typo in  packages/Webkul/User/src/Database/Seeders/RolesTableSeeder.php

Administrator role typo fix in  packages/Webkul/User/src/Database/Seeders/RolesTableSeeder.php

---

packages/Webkul/CartRule/src/Helpers/CartRule.php

#3638 fixed

---

packages/Webkul/Core/src/Repositories/ChannelRepository.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4394

Fixed maintenance mode status which is not working in channel section #4394

---

packages/Webkul/Admin/src/DataGrids/ChannelDataGrid.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4380#issuecomment-750851682

Fixed channel exception #4380

---

composer.json

composer test-win enable PHP unit test in windows platform.
Please accept my PR for [#issue-774179245](https://github.com/bagisto/bagisto/issues/4393#issue-774179245)

Added composer test-win

---

composer.json
composer.lock

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4401
**INFO:**
After checking the code, came to know that the alias i.e. ` 'Debugbar' => Barryvdh\Debugbar\Facade::class,` is executing however there is no package because the `--no-dev` command has run and I can't remove that line as well because this alias has been used in providers as well.
I can add the case for checking the environment and mode as well but I am avoiding the if-else stuff.
So moving the debug bar to the `require` section, because this can be handle from the `APP_DEBUG` key as well.

Fixed composer install --no-dev which gives error #4401

---

packages/Webkul/Velocity/src/Helpers/Helper.php

**BUGS:**
function used to fetch current channel in velocity meta data

core's function is used to fetch current channel code

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

added removed condition for multi select search.

added removed condtion for multiselect serach

---

packages/Webkul/Velocity/src/Providers/VelocityServiceProvider.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php

**BUG:**
Link: https://github.com/bagisto/bagisto/issues/4413
DB is calling in the provider which caused the test case. So added view composer.

Test Case Fix

---

packages/Webkul/Admin/src/DataGrids/SliderDataGrid.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4408

Fixed silder image not work #4408

---

packages/Webkul/Admin/src/DataGrids/CampaignDataGrid.php

Issue #4431 fixed

---

packages/Webkul/Admin/src/DataGrids/EventDataGrid.php

Issue #4434 fixed

---

packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
packages/Webkul/Shop/src/Resources/views/home/index.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4452

Fallback added to the shop home content #4452

---

composer.json
composer.lock
packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
packages/Webkul/Core/src/Core.php

The Invoice PDF in Arabic is not able to render Arabic properly. The alphabets are getting isolated instead of staying connected.
Link: https://github.com/bagisto/bagisto/issues/4420
- After lots of research `dompdf` support can only be fixed with this package. In the latest version of `ar-php`, they have given the support via composer and clean way as well.
- Added one optional param to the method i.e. `formatBasePrice`, which gives the ability to encode the formatted price.
- Run `composer install`.
- Done!

Arabic And Persian Support Added To DOM PDF #4420

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php

Split requests to reduce the loading time from the checkout page.

Countries and States data via. AJAX in checkout page

---

packages/Webkul/User/src/Models/Role.php
packages/Webkul/User/src/Repositories/RoleRepository.php

Link: https://github.com/bagisto/bagisto/issues/4428
- Updated `Role` repository class by overiding the `update` method.
- Removed and sorted unnecessary imports from Role class.

Fixed user roles permission option which are always save when trying to uncheck selected option #4428

---

packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php

Issue #4392 fixed

---

packages/Webkul/Shop/src/Providers/ShopServiceProvider.php

This allows the admin to publish the shop views to `resources/themes/shop/views`

Publish the shop views to the themes directory

---

packages/Webkul/Checkout/src/Cart.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4481

Fixed shipping costs which are not calculated with grand total #4481

---

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4420
Manual requires added inside specific controller's method, I will remove it once my autoload issue pr got merge.

Manual Require Added Till Merging Of Autoloading Fix #4420

---

packages/Webkul/Core/src/Http/Controllers/SubscriptionController.php
packages/Webkul/Core/src/Models/SubscribersList.php
packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php

added missed condition in marketing.

added missed condition in marketing

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4513

Fixed customer group column name which is invalid in csv, xls file #4513

---

composer.json
composer.lock
packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php

Manual requires removed and updated dependency to follow the autoloading compliance.

Manual Require Removed

---

packages/Webkul/Product/src/Helpers/Toolbar.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4522

Fixed on changing limit or filter from category page in ar, in which contents are showing in en locale #4522

---

composer.lock

Updated the patches\security updates for dependencies.

Updated the patches\security updates for dependencies

---

packages/Webkul/Product/src/Helpers/ConfigurableOption.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

Issue #3269 fixed

---

app/Console/Kernel.php
packages/Webkul/Marketing/src/Providers/MarketingServiceProvider.php
packages/Webkul/Product/src/Type/AbstractType.php

Issue #3572, fixes percentage for 2 decimal values.

Issue #3572, fixes percentage for 2 decimal values

---

packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php

Issue #4532 fixed

---

packages/Webkul/API/Http/Resources/Catalog/Product.php
packages/Webkul/Checkout/src/Cart.php

Link 1: https://github.com/bagisto/bagisto/issues/4510
Link 2: https://github.com/bagisto/bagisto/issues/4529
- Wishlist and cart key in products API added.
- Bundled and grouped products information added.

Wishlist and cart key in product API added #4510 and bundled and grouped product information added #4529

---

packages/Webkul/CartRule/src/Helpers/CartRule.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4542

Fixed the issue in which user cannot apply the coupon if the start date is today regardless the time #4542

---

packages/Webkul/Sales/src/Database/Migrations/2021_02_04_150033_add_download_canceled_column_in_downloadable_link_purchased_table.php
packages/Webkul/Sales/src/Models/DownloadableLinkPurchased.php
packages/Webkul/Sales/src/Repositories/DownloadableLinkPurchasedRepository.php
packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
packages/Webkul/Shop/src/Http/Controllers/DownloadableProductController.php
packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/de/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/es/app.php
packages/Webkul/Shop/src/Resources/lang/fa/app.php
packages/Webkul/Shop/src/Resources/lang/it/app.php
packages/Webkul/Shop/src/Resources/lang/ja/app.php
packages/Webkul/Shop/src/Resources/lang/nl/app.php
packages/Webkul/Shop/src/Resources/lang/pl/app.php
packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
packages/Webkul/Shop/src/Resources/lang/tr/app.php

Issue #4545

---

packages/Webkul/Product/src/Type/Configurable.php

Issue #4577

---

packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/signup/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/index.blade.php

Config Check Added #4569

---

packages/Webkul/Velocity/src/Resources/views/shop/UI/header.blade.php

Wishlist Check Added #4572

---

packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/events/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/events/edit.blade.php

Issue #4565

---

composer.lock

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4576
Reference: https://github.com/bagistobrasil/bagisto-product-social-share/pull/1
Just run `composer install --no-cache`.

Pinterest Issue Fixed In Latest Release #4576

---

packages/Webkul/Product/src/Helpers/ConfigurableOption.php
packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

Issue #4571 fixed.

---

packages/Webkul/Shop/src/Resources/views/emails/layouts/logo.blade.php

Issue #4598 fixed

---

packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/edit.blade.php
packages/Webkul/Marketing/src/Helpers/Campaign.php

Issue #4583 fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4606

Fixed product search icon which is not working properly in mobile view #4606

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4592#issuecomment-777994556

Fixed layout issues on front end #4592

---

packages/Webkul/Core/src/Core.php

Link: https://github.com/bagisto/bagisto/issues/4620
It's just a displaying issue nothing else added check-in core config. If the current locale is not present in channel locales then fallback will be added.

Core Config Check Added #4620

---

packages/Webkul/Admin/src/Resources/views/settings/sliders/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/sliders/edit.blade.php

Blank channel name on slider fixed.
Screenshot: https://prnt.sc/z898nh

Blank Channel Name On Slider Fixed

---

packages/Webkul/BookingProduct/src/Repositories/BookingProductEventTicketRepository.php

Issue #4624 fixed

---

config/auth.php
packages/Webkul/Core/src/Http/Controllers/ExchangeRateController.php
packages/Webkul/Tax/src/Models/TaxRate.php

**BUGS:**
[Updated: Duplicate queries removed.]

[Updated: Duplicate queries removed.]

---

CHANGELOG for v1.x.x.md

change log added

---

packages/Webkul/API/Http/Resources/Catalog/Product.php
packages/Webkul/API/Http/Resources/Catalog/ProductVideo.php
packages/Webkul/Core/src/Http/Controllers/SubscriptionController.php
resources/themes/.gitignore

Issue #4643 fixed

---

composer.lock

updated composer.lock file , #4654 fixed.

updated composer.lock file , #4654 fixed

---

packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
resources/themes/.gitignore

Link: https://github.com/bagisto/bagisto/issues/4633

Asterisk and `.gitignore` added for theme #4633

---

packages/Webkul/Product/src/Repositories/ProductFlatRepository.php

Issue #4344 fixed.

---

packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
packages/Webkul/Paypal/src/Providers/PaypalServiceProvider.php
packages/Webkul/Paypal/src/Resources/lang/ar/app.php
packages/Webkul/Paypal/src/Resources/lang/de/app.php
packages/Webkul/Paypal/src/Resources/lang/en/app.php
packages/Webkul/Paypal/src/Resources/lang/fa/app.php
packages/Webkul/Paypal/src/Resources/lang/it/app.php
packages/Webkul/Paypal/src/Resources/lang/ja/app.php
packages/Webkul/Paypal/src/Resources/lang/nl/app.php
packages/Webkul/Paypal/src/Resources/lang/pl/app.php
packages/Webkul/Paypal/src/Resources/lang/pt_BR/app.php
packages/Webkul/Paypal/src/Resources/lang/tr/app.php
packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4641

User Friendly Messages Updated #4641

---

CHANGELOG for v1.x.x.md

Change log sorted for version 1.3.0.

Change log modification

---

.env.testing

`.env.testing` version added

---

CHANGELOG for v0.1.x.md
CHANGELOG for v0.2.x.md
CHANGELOG for v1.x.x.md

Changelogs updated and sorted in proper orderings.

Change Log Updated And Sorted

---

CHANGELOG for v0.1.x.md

Sorted missing section changelog.

Sorted missing section changelog

---

.github/workflows/ci.yml
composer.lock

- Dependency updated.
- Workflow updated.
- Updated `shivammathur/setup-php@v1` to `shivammathur/setup-php@v2` which is depereciated.
- Extenstions added to support the composer installation.

Test Case Error Fixed

---

packages/Webkul/API/Http/Controllers/Shop/AddressController.php
packages/Webkul/API/Http/Resources/Customer/CustomerAddress.php
packages/Webkul/Core/src/Models/Address.php

**BUGS:**
Not able to create/update address from API
Not showing some fields explained in detail in linked issue
Not using ID from url, instead expecting it in request
#4677

Fix issue #4677

---

README.md

Temp changes added till auto sync from the open collective.

Temp changes added till auto sync from the open collective

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Link: https://github.com/bagisto/bagisto/issues/4686

Fixed configurable item which is still visible on search page when out of stock is disabled #4686

---

packages/Webkul/Shop/src/Http/Controllers/OrderController.php

Invoice Issue Fixed - SA2

---

packages/Webkul/Checkout/src/Cart.php

Some Cart Issue Fixed - SA1

---

README.md

Link added to sponsor image

---

packages/Webkul/Theme/src/ThemeViewFinder.php
packages/Webkul/Theme/src/Themes.php

**BUGS:**
Admin theme was not applying when setting an admin url other then "admin".

Fixed admin theme not loading with custom admin url

---

packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

Link: https://github.com/bagisto/bagisto/issues/4690

Fixed variant images which are not visible in a sorted manner as uploaded in backend #4690

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
packages/Webkul/Customer/src/Repositories/WishlistRepository.php

Link: https://github.com/bagisto/bagisto/issues/4722

Fixed getting exception on wishlist when add configurable item on cart #4722

---

packages/Webkul/Checkout/src/Cart.php

Issue #4748 fixed

---

packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

Link: https://github.com/bagisto/bagisto/issues/4755

Fixed issue in which selecting all channels from admin product list throws error #4755

---

packages/Webkul/API/Http/Controllers/Shop/CheckoutController.php

- Undefined variable in API's method removed.

Undefined Variable Removed

---

packages/Webkul/Product/src/Type/AbstractType.php

Link: https://github.com/bagisto/bagisto/issues/4758

Integer type added to quantity #4758

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php

Issue #4773 fixed

---

packages/Webkul/API/Http/Controllers/Shop/TransactionController.php
packages/Webkul/API/Http/Resources/Sales/OrderTransaction.php
packages/Webkul/API/Http/routes.php

fixed #4752

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Issue #4779 fixed

---

packages/Webkul/Paypal/src/Payment/SmartButton.php

- Paypal partner attribution ID added.

Paypal partner attribution ID added

---

packages/Webkul/Admin/src/Resources/views/tax/tax-rates/create.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-rates/edit.blade.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Tax/src/Http/Controllers/TaxRateController.php

Link: https://github.com/bagisto/bagisto/issues/4519
- `*` is already written in code, so added one more case for the empty check.

Zip Mandatory Removed On Disabled Zip Range #4519

---

packages/Webkul/Admin/src/Config/system.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Product/src/CacheFilters/Large.php
packages/Webkul/Product/src/CacheFilters/Medium.php
packages/Webkul/Product/src/CacheFilters/Small.php

Link: https://github.com/bagisto/bagisto/issues/4799
- Added core configurations.
- If the core configuration is null then the default value will be adjusted.
- If the image is already cached then the admin needs to clear its cache.
- We should give admin a button to optimize his project by adding this command `Artisan::call('optimize')`.

Dynamic product image resizing implemented #4799

---

packages/Webkul/API/Http/Resources/Catalog/Category.php

Link: #4807
- Just hit this URL i.e. http://example.com/api/categories

Category Icon Path Added #4807

---

packages/Webkul/Shop/src/Resources/lang/nl/app.php

Updated dutch translations

---

packages/Webkul/Shop/src/Http/Controllers/ProductController.php

Link: https://github.com/bagisto/bagisto/issues/4811
- Go to redirect page.

Fixed error when redirect on review page #4811

---

packages/Webkul/Attribute/src/Models/AttributeFamily.php

Issue #4813 fixed

---

packages/Webkul/Checkout/src/Cart.php

Issue #4818 fixed

---

packages/Webkul/Category/src/Repositories/CategoryRepository.php

Added `findBySlug($slug)` without fail as `findBySlugOrFail($slug)`causing issues with custom packages

Added findBySlug without fail

---

packages/Webkul/Admin/src/Providers/EventServiceProvider.php
packages/Webkul/BookingProduct/src/Providers/EventServiceProvider.php
packages/Webkul/CartRule/src/Providers/EventServiceProvider.php
packages/Webkul/Product/src/Providers/EventServiceProvider.php

Improved event service providers to make listeners overridable.
I think just need to test all events to make sure that listeners are working

Event service providers improvements

---

packages/Webkul/Product/src/Listeners/ProductFlat.php

Improved ProductFlat listener to make fillable attribute codes overridable
Try to create/update simple or configurable product, or try to extend listener and override fillable attribute codes
No I think

Improved ProductFlat listener to make fillable attribute codes overridable

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/index.blade.php

Link: #4823
- I just removed the dynamic height js code. I will handle it differently if some portion got broken.
- Go to the invoice page.

Fixed UI bug at customer invoice page if multiple invoice exist for same order id #4823

---

packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php

Link: https://github.com/bagisto/bagisto/issues/4831

Fixed header content category which is not clickable on velocity #4831

---

packages/Webkul/Admin/src/Config/acl.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Http/routes.php

Issue #4847 fixed

---

composer.json
composer.lock

This is nothing just a bug in the lower version of dependency so updated that,
Link: https://github.com/bagisto/bagisto/issues/4865
- Just run `composer install`.
- There is one dependency `tymon/auth`, they are working on PHP 8 support, however, they have mentioned that we can use the `dev-branch` no problem will be raise.
Ref: https://github.com/tymondesigns/jwt-auth/issues/2082
- And I just manually tested the API on PHP 8 and everything seems fine to me.
- I am regularly checking these issues if support is released i will update the version also.

Fixed getting exception when click on print invoice #4865

---

packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
packages/Webkul/Admin/src/Resources/views/customers/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/4854

Fixed customer address page which was always redirect to customer profile tab on filter #4854

---

packages/Webkul/Product/src/Type/Bundle.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Product/src/Type/Downloadable.php
packages/Webkul/Product/src/Type/Grouped.php
packages/Webkul/Product/src/Type/Virtual.php

Length Added #4885

---

packages/Webkul/CartRule/src/Helpers/CartRule.php

Link: https://github.com/bagisto/bagisto/issues/4891

Cart rule issue fixed #4891

---

packages/Webkul/Product/src/Models/ProductFlat.php
packages/Webkul/Shop/src/Resources/views/products/view/grouped-products.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/grouped-products.blade.php

Link: https://github.com/bagisto/bagisto/issues/4896

Fixed group product sort order functionality which is not working #4896

---

packages/Webkul/Sales/src/Database/Migrations/2021_02_04_150033_add_download_canceled_column_in_downloadable_link_purchased_table.php

Fix For Migrate Rollback
Fix migrate rollback command
Run Migrate, 
then migrate rollback

Migrate Rollback Fix in Sales Package

---

packages/Webkul/Core/src/Exceptions/Handler.php

- Depreciated class replaced in the handler class.

Depreciated class replaced in the handler class

---

packages/Webkul/Ui/src/DataGrid/DataGrid.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideExceptionHandler.php
packages/Webkul/Ui/src/Exceptions/ActionKeyException.php
packages/Webkul/Ui/src/Exceptions/ColumnKeyException.php

While writing the docs, come to know that some keys are mandatory. So it will be good for the developer if we throw some exceptions with the required keys.
- Some custom exceptions added.

Some more refinement added to datagrid

---

packages/Webkul/Ui/src/DataGrid/Traits/ProvideExceptionHandler.php

Comment updated

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php

Added empty select option for better user experience

fixed #4886

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php

This pr fix issue when addVariant button press add filed but it's name is 'variant_undefined' cause problem on updateing and saving net variant

fix variants issule on add or delete

---

packages/Webkul/Category/src/Database/Seeders/CategoryBulkTableSeeder.php
packages/Webkul/Category/src/Database/Seeders/CategoryTableSeeder.php

- Link: https://github.com/bagisto/bagisto/issues/4931#issuecomment-861192012
- Added seeder for default locales only.

Category Translations Seeder Updated #4931

---

packages/Webkul/Product/src/Models/Product.php

Fixed belongsToMany relations eager loading issue
Try to eager load any existing belongsToMany relation

Fixed belongsToMany relations eager loading issue

---

.env.example
.env.testing
packages/Webkul/Core/src/Console/Commands/Install.php

- Fixed console command to auto publish the assets without manually pressing 0
- Updated bagisto version number to 1.3.2
run `php artisan bagisto:install` vendor:publish should do everything automatically.

fixed console install to auto publish assets and updated version number

---

packages/Webkul/Admin/src/DataGrids/CustomersInvoicesDataGrid.php

- Link: https://github.com/bagisto/bagisto/issues/4947

Added requested customer's id in the invoice datagrid #4947

---

packages/Webkul/Core/src/Exceptions/Handler.php

- Sometimes in admin section needs to debug the error. So added check for that if the project is in debug mode all errors will be visible.
- If it is in false mode, then no error will be displayed it  will work same as previous.

Debug Check Added In Exceptions

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Link: https://github.com/bagisto/bagisto/issues/4977

Out Of Stock Fixed #4977

---

packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php

Link: https://github.com/bagisto/bagisto/issues/4969

Added Multi Case #4969

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Link: https://github.com/bagisto/bagisto/issues/4779

Image Search Issue Fixed #4779

---

packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php

Link: https://github.com/bagisto/bagisto/issues/4989

Some Extra Fields Added #4989

---

packages/Webkul/Checkout/src/Http/helpers.php

- Cart helper has been bound from the container.

Cart helper bound from container

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/reset-password.blade.php

Link: https://github.com/bagisto/bagisto/issues/5013

Warning Message Added #5013

---

packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5012

French Locale Issue Fixed #5012

---

packages/Webkul/Admin/src/DataGrids/InvoicesTransactionsDatagrid.php
packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
packages/Webkul/Admin/src/Resources/views/sales/transactions/view.blade.php

Link: https://github.com/bagisto/bagisto/issues/5018

Invoice ID Recognizable #5018

---

packages/Webkul/Marketing/src/Helpers/Campaign.php

Link: https://github.com/bagisto/bagisto/issues/5021

Fixed Mail For Guest #5021

---

CHANGELOG for v1.x.x.md

Changelog Added

---

packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
packages/Webkul/Shop/src/Resources/views/products/add-to-cart.blade.php

- Link: https://github.com/bagisto/bagisto/issues/5046

Fixed add to cart button which is not working in compare page for default theme #5046

---

CHANGELOG for v1.x.x.md

Latest Changelog

---

CHANGELOG for v1.x.x.md

- Some changes in the changelog.

Some changes in the changelog

---

packages/Webkul/Velocity/src/Resources/views/admin/category/create.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/category/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/category.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/edit-product.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/link.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/product.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/static.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/create.blade.php
packages/Webkul/Velocity/src/Resources/views/admin/content/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-info.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/payment.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/shipping.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/country-state.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/session/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/forgot-password.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/reset-password.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/reviews/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/bundle-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/downloadable.blade.php

Link: https://github.com/bagisto/bagisto/issues/5053

Slots Avoided On Validations And Added V-Text #5053

---

packages/Webkul/Shop/src/Http/Controllers/CartController.php
packages/Webkul/Shop/src/Http/routes.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/wishlist.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
packages/Webkul/Shop/src/Resources/views/products/wishlist.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

- Security fixes on wishlist route.
- Add, remove and remove all wishlists in both themes.
- Check in listings wherever wishlist icon is available.

Security Fixes On Wishlist Route

---

public/installer/index.php

- Link: https://github.com/bagisto/bagisto/issues/5057
- Just try to install Bagisto with db prefix from GUI.

DB Prefix Added #5057

---

packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-four.blade.php

- Link: https://github.com/bagisto/bagisto/issues/5056
- Test default banners in RTL.
- Test banners from admin panel in RTL.

RTL Banner Issue Fixed #5056

---

packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Bundle.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Product/src/Type/Downloadable.php
tests/unit/Tax/Helpers/TaxCest.php

Link: https://github.com/bagisto/bagisto/issues/5051
- Added round function to `validateCartItem` and `finalizeCartTotals`.

Fixed missmatch in grand total and sub total in HKD currency in cart summary #5051

---

packages/Webkul/Customer/src/Helpers/Wishlist.php

Link: https://github.com/bagisto/bagisto/issues/5067

Is Wishlist API Key Fixed #5067

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

Link: https://github.com/bagisto/bagisto/issues/5004
- Refreshed shipping component on saving address request.
- Just send your updated shipping HTML via. ajax.

Refreshed Shipping Component On Save Address Request #5004

---

packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5001

Displayed total unpaid invoices on the dashboard #5001

---

packages/Webkul/Product/src/Type/Configurable.php

- Removed unnecessary round-off because rounded of added in the final price method,
https://github.com/bagisto/bagisto/blob/eba4ddf41716a79a1270ae3240732401a8b8acc4/packages/Webkul/Product/src/Type/AbstractType.php#L568

Removed Round Off As Already Rounded Of From The Final Price

---

packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/SocialLogin/src/Resources/lang/fa/app.php
packages/Webkul/Tax/src/Resources/lang/fa/app.php

Hi,
I fixed some Persian translations in the admin panel and translated the tax and social login package.

Persian translations

---

.github/PULL_REQUEST_TEMPLATE.md

- Slightly changes in the template.

PR Template Updated

---

packages/Webkul/Admin/src/DataGrids/SliderDataGrid.php
packages/Webkul/Core/src/Http/Controllers/SliderController.php

Link: https://github.com/bagisto/bagisto/issues/5091

Slider issue fixed on DB prefix #5091

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php

Link: https://github.com/bagisto/bagisto/issues/5101
- As per the vee-validate docs, proper validation can only apply if the type is text. So I just changed the number to text.
- Just try to save decimal or blank values.

Numeric Added With Text Type #5101

---

packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php

Link: https://github.com/bagisto/bagisto/issues/5100
- Added default first name and last name.
- Try to check the customer's address create page.

Default Names Added #5100

---

packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5104

Last Name Validation Added #5104

---

packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

Link: https://github.com/bagisto/bagisto/issues/5065
- `doAction` method added to Vue component method.
- Dynamic function used `onclick` event because it is out of scope. That's why it's getting warnings in the console.
- Just check each Datagrid for delete operations.

Fixed dev warnings and some delete function #5065

---

packages/Webkul/Theme/src/Themes.php

Link: https://github.com/bagisto/bagisto/issues/5110
- Added dynamic prefix.
- Just test this by changing the admin URL from `.env`.

Fixed theme prefix issue #5110

---

composer.lock

- Depandabot alert fixed.
- Updated codeception patch number.

Dependabot Fixed

---

packages/Webkul/Core/src/Core.php

Link: https://github.com/bagisto/bagisto/issues/5109#issuecomment-913446095

Admin Key Updated #5109#issuecomment-913446095

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php

Link: https://github.com/bagisto/bagisto/issues/5111

Meta Twice Removed #5111

---

packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php

Link: https://github.com/bagisto/bagisto/issues/5115

Exception handled in case admin change url by passing 0 in place of asc or desc #5115

---

packages/Webkul/Core/src/Repositories/CoreConfigRepository.php

Link: https://github.com/bagisto/bagisto/issues/5113

Fixed error in Admin -> Configuration after added custom scripts #5113

---

packages/Webkul/Velocity/src/Resources/views/shop/cms/page.blade.php

Link: https://github.com/bagisto/bagisto/issues/5112

Removed Offset #5112

---

packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/general.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php

Link: https://github.com/bagisto/bagisto/issues/5122

Numeric Validation Added #5122

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php

- Hostname placeholder updated.

Hostname Placeholder Updated

---

packages/Webkul/Admin/src/Listeners/ChannelSettingsChange.php
packages/Webkul/Core/src/Console/Commands/DownChannelCommand.php
packages/Webkul/Core/src/Console/Commands/DownCommand.php
packages/Webkul/Core/src/Console/Commands/UpChannelCommand.php
packages/Webkul/Core/src/Console/Commands/UpCommand.php
packages/Webkul/Core/src/Http/Middleware/CheckForMaintenanceMode.php
packages/Webkul/Core/src/Providers/CoreServiceProvider.php

- Fixed issue in which if one channel is down then all channel is down.
- Separate channel command in which database is not updated.
- Parent commands will impact on all channels.
- Try to enable/disable the maintenance mode of the channel.

Maintainence Mode Enhanced

---

packages/Webkul/Shop/src/Http/Controllers/CartController.php

- 5 attempts per minute were added to the apply coupon.

Throttling Middleware Added To Apply Coupon Method

---

public/installer/EnvConfig.php
public/installer/Views/environment.blade.php

Link: https://github.com/bagisto/bagisto/issues/5061
- Added database prefix in GUI installer.
- Try to install Bagisto using a GUI installer.

DB Prefix Added In GUI Installer #5061

---

packages/Webkul/Core/src/Http/Middleware/SecureHeaders.php

#5152
* Before removing headers, will check if not already sent

FEAT: Check if headers weren't sent already

---

packages/Webkul/Admin/src/Http/routes.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php
packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
tests/functional/Admin/Catalog/AttributeCest.php

Link: https://github.com/bagisto/bagisto/issues/5009
- Added load more to avoid accessive dom size.
- Avoided multiple times searching for a key in the loop, to check the new and existing options.
- Avoided double loops for deleting the options in the backend.
- Options will be coming from AJAX.
- Try to create new options.
- Try to update an existing one.
- Try to delete the options and save the form.

Attribute Page Optimization #5009

---

tests/unit/Tax/Helpers/TaxCest.php

- Minor check added on the second method also.

Minor check added on the second method also

---

packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
packages/Webkul/Admin/src/DataGrids/AttributeDataGrid.php
packages/Webkul/Admin/src/DataGrids/CampaignDataGrid.php
packages/Webkul/Admin/src/DataGrids/CartRuleCouponsDataGrid.php
packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
packages/Webkul/Admin/src/DataGrids/CatalogRuleDataGrid.php
packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/DataGrids/CustomerOrderDataGrid.php
packages/Webkul/Admin/src/DataGrids/CustomerReviewDataGrid.php
packages/Webkul/Admin/src/DataGrids/CustomersInvoicesDataGrid.php
packages/Webkul/Admin/src/DataGrids/EmailTemplateDataGrid.php
packages/Webkul/Admin/src/DataGrids/InventorySourcesDataGrid.php
packages/Webkul/Admin/src/DataGrids/LocalesDataGrid.php
packages/Webkul/Admin/src/DataGrids/NewsLetterDataGrid.php
packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
packages/Webkul/Admin/src/DataGrids/OrderInvoicesDataGrid.php
packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
packages/Webkul/Admin/src/DataGrids/TaxRateDataGrid.php
packages/Webkul/Admin/src/DataGrids/UserDataGrid.php
packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
packages/Webkul/Ui/src/DataGrid/DataGrid.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php
packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
packages/Webkul/Velocity/src/DataGrids/CategoryDataGrid.php
packages/Webkul/Velocity/src/DataGrids/ContentDataGrid.php

Link 1: https://github.com/bagisto/bagisto/issues/5163
Link 2: https://github.com/bagisto/bagisto/issues/5173
- Added single key i.e. `closure`.
- In later versions, the `wrapper` key will get removed.

Datagrid Enhancement #5163

---

.env.example
.env.testing
.github/ISSUE_TEMPLATE/1_Bug_report.md

Version Number Updated

---

CHANGELOG for v1.x.x.md

Changelog For V1.3.3

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/ExportController.php

Issue Link: https://github.com/bagisto/bagisto/issues/5194
- Removed arguments from constructor instance.

Export issue fixed #5194

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/downloadable.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/images.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/videos.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/create.blade.php
packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/users/forget-password/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/reset-password/create.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/appointment.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/default.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/rental.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/table.blade.php

Link: https://github.com/bagisto/bagisto/issues/5180
- This is due to the availability of the `@parent` directive. Laravel will place their placeholder when you use this.
- Replaced `yield` with `stack` and pushed CSS where section used.
- Edited files further enhanced to latest ECMA standards. Updated JS codes.
- Some indentations and lines were fixed.
- Test all types of products, cart rules, and catalog rules because changes are mostly in the products file.

Blade CSS And JS Stack Enhanced #5180

---

packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/checkbox.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/text.blade.php

Some minor fixes were done

---

packages/Webkul/Shipping/src/Config/system.php

Link: https://github.com/bagisto/bagisto/issues/5307

Added Select Type #5307

---

packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

Link: https://github.com/bagisto/bagisto/issues/5219

[Fixed: #5219 Issue in multi select data in every datagrid.]

---

packages/Webkul/Ui/src/Resources/views/datagrid/body.blade.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

Link: https://github.com/bagisto/bagisto/pull/5242#issuecomment-946372798

Datagrid Checkboxes Enhanced #5242#issuecomment-946372798

---

packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Shipping/src/Carriers/AbstractShipping.php
packages/Webkul/Shipping/src/Carriers/FlatRate.php
packages/Webkul/Shipping/src/Carriers/Free.php
packages/Webkul/Shipping/src/Shipping.php

#5305 
Checker added to saveShippingMethod.
Add a product to cart disable a shipping method and try to use save-shipping API, you will get a 400 error.

Shipping method validation

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/scripts.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

Link: https://github.com/bagisto/bagisto/issues/5226
- Reduced a load of ids as DOM element giving warning if same product ids are coming which is the reason element is not going to wishlist.

Wishlist Issue Fixed #5226

---

packages/Webkul/Product/src/Models/ProductFlat.php

- Not saving any values in the database.
- Just checking for the null values for channel and locale-based, if found then default product attribute values will be passed.
Link: https://github.com/bagisto/bagisto/issues/5233

Fallback Added To Product Flat Model's Attributes #5233

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5325

Delete Profile Fixed #5325

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5328

Disabled System Attributes #5328

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/de/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/es/app.php
packages/Webkul/Shop/src/Resources/lang/fa/app.php
packages/Webkul/Shop/src/Resources/lang/fr/app.php
packages/Webkul/Shop/src/Resources/lang/it/app.php
packages/Webkul/Shop/src/Resources/lang/ja/app.php
packages/Webkul/Shop/src/Resources/lang/nl/app.php
packages/Webkul/Shop/src/Resources/lang/pl/app.php
packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
packages/Webkul/Shop/src/Resources/lang/tr/app.php

Missing translations added

---

app/Http/Middleware/VerifyCsrfToken.php
packages/Webkul/Paypal/src/Http/routes.php

Paypal routes improved and used `withoutMiddleware`

---

packages/Webkul/Velocity/src/Resources/views/shop/products/list/card.blade.php

- Removed setters and used helpers.

Removed Setters And Used Helpers

---

.github/workflows/ci.yml
composer.json
composer.lock
config/app.php
packages/Webkul/Customer/src/Models/Customer.php

- Replaced `tymon/jwt-auth` with `php-open-source-saver/jwt-auth`. As earlier version is not supporting the PHP 8.0.
- Dropped PHP 7.3 support.

Packages Updated

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php

fix for issue #5075
modified file packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php to add the number of records in the datagrid and modified packages/Webkul/Admin/src/Resources/lang/en/app.php for translation
can be tested on data grids in the admin attached screenshots for the reference
https://nimb.ws/y6TrvD
https://nimb.ws/QBK3wU (filtered grid)

fixing issue 5075

---

packages/Webkul/Velocity/src/Resources/views/shop/products/list/card.blade.php

Link: https://github.com/bagisto/bagisto/issues/5347

Cross Sell Image Fixed #5347

---

packages/Webkul/Admin/src/Resources/views/export/temp.blade.php

Link: https://github.com/bagisto/bagisto/issues/5350
- Removed preg match, all special chars should be handled at the time of validations and insertion in the database.

Pregmatch Removed #5350

---

packages/Webkul/Shipping/src/Shipping.php

Link: https://github.com/bagisto/bagisto/issues/5353

Rates Reset #5353

---

packages/Webkul/Core/src/Contracts/Validations/PhoneNumber.php
packages/Webkul/Core/src/Resources/lang/en/validation.php
packages/Webkul/Core/src/Resources/lang/es/validation.php
packages/Webkul/Core/src/Resources/lang/fa/validation.php
packages/Webkul/Core/src/Resources/lang/it/validation.php
packages/Webkul/Core/src/Resources/lang/pt_BR/validation.php
packages/Webkul/Core/src/Resources/lang/tr/validation.php
packages/Webkul/Customer/src/Http/Controllers/AddressController.php
packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php
packages/Webkul/Customer/src/Http/Requests/CustomerProfileRequest.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
tests/functional/Customer/CustomerCest.php

- Profile and address validations fixed.

Profile and address validations fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Checkout/src/Http/Requests/CustomerAddressForm.php

[Updated: api and customer auth updated and added API locale translations.]

---

packages/Webkul/Product/src/Repositories/ProductRepository.php
packages/Webkul/Product/src/resources/manifest.php

Link 1: https://github.com/bagisto/bagisto/issues/5365
Link 2: https://github.com/bagisto/bagisto/issues/5370

Filter issue #5365

---

packages/Webkul/Core/src/Http/Controllers/ExchangeRateController.php

Duplication removed.
There was a duplication in the construct method of this controller.

Updated: Duplicate variable removed.

---

packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php
tests/functional/Customer/CustomerCest.php

Link: https://github.com/bagisto/bagisto/issues/5377

Wishlist Issue Fixed #5377

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/coupon.blade.php

Link: https://github.com/bagisto/bagisto/issues/5381

Coupon Fixed #5381

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php

Link: https://github.com/bagisto/bagisto/issues/5381#issuecomment-985334670

Replicated In Default Theme #5381#issuecomment-985334670

---

packages/Webkul/Category/src/Repositories/CategoryRepository.php
packages/Webkul/User/src/Models/Admin.php

[Updated: Category locale request issue(using API, GraphQL) fixed.]

---

packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerGroupController.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/index.blade.php
packages/Webkul/BookingProduct/src/Models/BookingProduct.php
packages/Webkul/CartRule/src/Models/CartRuleCoupon.php
packages/Webkul/CatalogRule/src/Models/CatalogRule.php
packages/Webkul/CatalogRule/src/Models/CatalogRuleProduct.php
packages/Webkul/Core/src/Models/Country.php
packages/Webkul/Core/src/Models/CurrencyExchangeRate.php
packages/Webkul/Core/src/Models/Slider.php
packages/Webkul/Product/src/Models/Product.php
packages/Webkul/Velocity/src/Models/VelocityCustomerCompareProduct.php

[Updated: customer_group event and Models mappings.]

---

README.md
resources/lang/ar/auth.php
resources/lang/ar/pagination.php
resources/lang/ar/passwords.php
resources/lang/ar/validation.php

1. Added Arabic translation for Laravel.
2. Added Egypt flag in the README.md file.
3. Fixed a typo in the README.md file.

Added Arabic translation for Laravel

---

packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
packages/Webkul/Shop/src/Routes/customer-routes.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/mobile.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php

- Due to so many emails about this, I am making a pull request for method changing in the Logout page to avoid CSRF.

Logout Method Changed

---

packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php

fixed #5406

---

packages/Webkul/Shop/src/Routes/customer-routes.php

Link: https://github.com/bagisto/bagisto/issues/5408

Namespace Added #5408

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php

Link: https://github.com/bagisto/bagisto/issues/5398

Case Removed Only For Configurable #5398

---

packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/reviews/reviews.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/reviews/index.blade.php

https://github.com/bagisto/bagisto/issues/5409
Add  **v-pre**

Fixed issue #5409

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/scripts.blade.php

Link: https://github.com/bagisto/bagisto/issues/5424

Wishlist confirm fixed #5424

---

packages/Webkul/Admin/src/Resources/views/customers/general.blade.php

Link: https://github.com/bagisto/bagisto/issues/5423

Date of birth issue fixed #5423

---

packages/Webkul/Admin/src/Http/Controllers/ExportController.php

Export issue is fixed

---

packages/Webkul/Shop/src/Routes/checkout-routes.php
packages/Webkul/Shop/src/Routes/customer-routes.php

Link: https://github.com/bagisto/bagisto/issues/5429

Moved Some Routes #5429

---

packages/Webkul/Product/src/Models/ProductFlat.php

Link: https://github.com/bagisto/bagisto/issues/5430

Null Issue Fixed #5430

---

packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
packages/Webkul/Sales/src/Repositories/RefundRepository.php

Link: https://github.com/bagisto/bagisto/issues/5428

Invalid Quantity Refund Issue Fixed #5428

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php

Link -> https://github.com/bagisto/bagisto/issues/5423#issuecomment-994790202

Added Date Tag #5423#issuecomment-994790202

---

packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php

Link: https://github.com/bagisto/bagisto/issues/5436

Invoice Issue Fixed #5436

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5440

Default Quantity Changer Fixed #5440

---

packages/Webkul/Shop/src/Http/Controllers/OrderController.php

Fix @param namespace issue for $invoiceRepository and $refundRepository
I saw @param namespace issue in `packages/Webkul/Shop/src/Http/Controllers/OrderController.php: 40, 41` and fixed it.
NaN
Nan

invoiceRepository, refundRepository @param include path fix

---

packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php

Link: https://github.com/bagisto/bagisto/issues/5443

Attribute Issue Fixed #5443

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist-product.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/scripts.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

Link: https://github.com/bagisto/bagisto/issues/5445#issuecomment-997777539

Wishlist Issue Fixed #5445#issuecomment-997777539

---

packages/Webkul/Admin/src/Resources/views/customers/note.blade.php

Admin should be able to edit/view customer note

v-pre added for customer note

---

packages/Webkul/Admin/src/Http/Controllers/Sales/ShipmentController.php
packages/Webkul/Sales/src/Repositories/InvoiceRepository.php

Link: https://github.com/bagisto/bagisto/issues/5444

Zero Quantity Fixed #5444

---

packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
packages/Webkul/Admin/src/Resources/views/layouts/tinymce.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/templates/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/templates/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/sliders/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/sliders/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5450

TinyMCE Image Issue Fixed #5450

---

packages/Webkul/Product/src/Type/Configurable.php

Link: https://github.com/bagisto/bagisto/issues/5451

Quantity Added #5451

---

packages/Webkul/Product/src/Type/Configurable.php

- Reverted this PR: https://github.com/bagisto/bagisto/pull/5454
- Will provide new PR with all the cases check.
- Will provide unit and functional test also.

Reverted PR #5454

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php

Fixed Issue #5471

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php

Link: https://github.com/bagisto/bagisto/issues/5466

Order UI Issue Fixed #5466

---

packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5473

Cart Removed From The Top Nav In Default Theme #5473

---

packages/Webkul/Admin/src/DataGrids/SliderDataGrid.php

Link: https://github.com/bagisto/bagisto/issues/5474

Channel Code Fixed #5474

---

packages/Webkul/Core/src/Contracts/Validations/Address.php
packages/Webkul/Core/src/Resources/lang/en/app.php
packages/Webkul/Core/src/Resources/lang/en/validation.php
packages/Webkul/Core/src/Resources/lang/es/app.php
packages/Webkul/Core/src/Resources/lang/es/validation.php
packages/Webkul/Core/src/Resources/lang/fa/app.php
packages/Webkul/Core/src/Resources/lang/fa/validation.php
packages/Webkul/Core/src/Resources/lang/it/app.php
packages/Webkul/Core/src/Resources/lang/it/validation.php
packages/Webkul/Core/src/Resources/lang/pt_BR/app.php
packages/Webkul/Core/src/Resources/lang/pt_BR/validation.php
packages/Webkul/Core/src/Resources/lang/tr/app.php
packages/Webkul/Core/src/Resources/lang/tr/validation.php
packages/Webkul/Customer/src/Http/Controllers/AddressController.php
packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5484

Address Field Fixed #5484

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5485

Added Margin #5485

---

packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/wishlist-product.blade.php

Link: https://github.com/bagisto/bagisto/issues/5493

Changes Done #5493

---

packages/Webkul/User/src/Http/Middleware/Bouncer.php

Link: https://github.com/bagisto/bagisto/issues/5497

Added Flash Message #5497

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5490
- Large Screen
- Medium Screen
- Small Screen

Address Card Responsive #5490

---

packages/Webkul/Core/src/Console/Commands/DownChannelCommand.php

Link: https://github.com/bagisto/bagisto/issues/5505

Fixed maintance mode which is not working in admin panel #5505 

---

packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/edit.blade.php
packages/Webkul/Inventory/src/Http/Controllers/InventorySourceController.php
packages/Webkul/Inventory/src/Http/Requests/InventorySourceRequest.php

Link: https://github.com/bagisto/bagisto/issues/5503

Inventory Sources Validation Added #5503

---

packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
packages/Webkul/Shop/src/Resources/views/products/compare.blade.php

Link: https://github.com/bagisto/bagisto/issues/5510

Auto Count Fixed #5510

---

packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Grouped.php
packages/Webkul/Shop/src/Resources/views/products/list/card.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/list/card.blade.php

Link: https://github.com/bagisto/bagisto/issues/5511

Added Badge Case #5511

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/users/users/edit.blade.php
packages/Webkul/User/src/Http/Controllers/UserController.php
tests/functional/Admin/Settings/UsersCest.php

Link: https://github.com/bagisto/bagisto/issues/5539

Status Fixed #5539

---

packages/Webkul/Admin/src/Resources/manifest.php
packages/Webkul/Attribute/src/Resources/manifest.php
packages/Webkul/BookingProduct/src/Resources/manifest.php
packages/Webkul/CMS/src/Resources/manifest.php
packages/Webkul/CMS/src/resources/manifest.php
packages/Webkul/CartRule/src/Resources/manifest.php
packages/Webkul/CatalogRule/src/Resources/manifest.php
packages/Webkul/Category/src/Resources/manifest.php
packages/Webkul/Checkout/src/Resources/manifest.php
packages/Webkul/Checkout/src/resources/manifest.php
packages/Webkul/Core/src/CoreConvention.php
packages/Webkul/Core/src/Resources/manifest.php
packages/Webkul/Customer/src/Resources/manifest.php
packages/Webkul/Inventory/src/Resources/manifest.php
packages/Webkul/Marketing/src/Resources/manifest.php
packages/Webkul/Payment/src/Resources/manifest.php
packages/Webkul/Paypal/src/Resources/manifest.php
packages/Webkul/Product/src/Resources/manifest.php
packages/Webkul/Rule/src/Resources/manifest.php
packages/Webkul/Sales/src/Resources/manifest.php
packages/Webkul/Shipping/src/Resources/manifest.php
packages/Webkul/Shop/src/Resources/manifest.php
packages/Webkul/SocialLogin/src/Resources/manifest.php
packages/Webkul/Tax/src/Resources/manifest.php
packages/Webkul/Theme/src/Resources/manifest.php
packages/Webkul/Ui/src/Resources/manifest.php
packages/Webkul/User/src/Resources/manifest.php
packages/Webkul/Velocity/src/Resources/manifest.php

Link: https://github.com/bagisto/bagisto/issues/5513
- Now only one resource folder in each package i.e. `src/Resources`.
- Expected result,

`manifest.php` file fixed with proper consistensy #5513

---

packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
packages/Webkul/Core/src/Contracts/Validations/CommaSeperatedInteger.php
packages/Webkul/Core/src/Http/Requests/MassOperationRequest.php
packages/Webkul/Core/src/Resources/lang/en/validation.php
packages/Webkul/Core/src/Resources/lang/es/validation.php
packages/Webkul/Core/src/Resources/lang/fa/validation.php
packages/Webkul/Core/src/Resources/lang/it/validation.php
packages/Webkul/Core/src/Resources/lang/pt_BR/validation.php
packages/Webkul/Core/src/Resources/lang/tr/validation.php

- Mass operation request added for the Rest API and core.
- Testing in API first then soon will add it to the `massUpdate` and `massDestroy` method.
- Some cleanup done.

Mass Operation Request Added For Rest API and Core

---

.env.example
config/app.php
packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
packages/Webkul/Core/src/Console/Commands/BagistoVersion.php
packages/Webkul/Core/src/Core.php

Link: https://github.com/bagisto/bagisto/issues/5548

Version Improvement #5548

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php

Link: https://github.com/bagisto/bagisto/issues/5549

Translations Added #5549

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php

Link: https://github.com/bagisto/bagisto/issues/5553

Customer Group Price Fixed #5553

---

packages/Webkul/Admin/src/Resources/views/catalog/products/create.blade.php

Link: https://github.com/bagisto/bagisto/issues/5552

Removed Blank Space #5552

---

packages/Webkul/Core/src/Http/Requests/MassDestroyRequest.php
packages/Webkul/Core/src/Http/Requests/MassUpdateRequest.php

Mass Request Updated

---

packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php

Link: https://github.com/bagisto/bagisto/issues/5569

Fixed #5569

---

packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php

#5588 
Fixed ui issue in button in cms pages in mobile view

fixed cms header ui issue

---

packages/Webkul/Core/src/Core.php
packages/Webkul/Shop/src/Http/Middleware/Currency.php
packages/Webkul/Shop/src/Http/Middleware/Locale.php

- Currency is handled by a session in the middleware, then no need for session handling in the `Core` class.
- In this way, API can make their own middleware to set the currency as per their need.

Core currency method and middlewares improved

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5531#issuecomment-1014250076

Fixed Velocity Profile Issue #5531#issuecomment-1014250076

---

packages/Webkul/Velocity/src/Resources/views/shop/cms/page.blade.php

Link: https://github.com/bagisto/bagisto/issues/5625

Fixed CMS Sidebar #5625

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5633

Fixed Cart Alignment #5633

---

packages/Webkul/User/src/Http/Controllers/SessionController.php

- Removed guest middleware from admin controller. As not needed there because that controller is already handled by `bouncer` middleware.
- In this way, customer-guest is in the front, and admin is totally separated.

Fixed Admin 404 Issue

---

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
packages/Webkul/Admin/src/Routes/sales-routes.php
packages/Webkul/Core/src/Traits/CoreConfigField.php
packages/Webkul/Core/src/Traits/PDFHandler.php
packages/Webkul/Core/src/Traits/Sanitizer.php
packages/Webkul/Shop/src/Http/Controllers/OrderController.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
packages/Webkul/Shop/src/Routes/customer-routes.php

Link: https://github.com/bagisto/bagisto/issues/5396
- Removed boldness as some special chars are not supported in bold letters.
- Instead added one horizontal line which will separate the grand total.
- `PDFHandler` trait is provided for handling all the backend HTML manipulations in one place.
- INR
- EUR
- USD

Enhancement Done For Invoice PDF

---

packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php

Link: https://github.com/bagisto/bagisto/issues/5531#issuecomment-1017148009

Select Gender Added #5531#issuecomment-1017148009

---

config/database.php

- Default argument to `.env` added.

Default argument to `.env` added

---

packages/Webkul/Core/src/Providers/EnvValidatorServiceProvider.php

Added Underscore #5631

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Validations/ProductCategoryUniqueSlug.php
packages/Webkul/Category/src/Http/Controllers/CategoryController.php
packages/Webkul/Category/src/Http/Requests/CategoryRequest.php
packages/Webkul/Category/src/Repositories/CategoryRepository.php
packages/Webkul/Product/src/Http/Controllers/ProductController.php
packages/Webkul/Product/src/Http/Requests/ProductForm.php

Link: https://github.com/bagisto/bagisto/issues/5200

Slug checking added in both products and categories #5200

---

packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php

Link: https://github.com/bagisto/bagisto/issues/5672

Proper Paypal Message Added #5672

---

packages/Webkul/Sales/src/Repositories/ShipmentRepository.php

Link: https://github.com/bagisto/bagisto/issues/5311

Total Weight Updated In Shipment Table #5311

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/reviews/index.blade.php

#5619
**Fixed Issue images in review is not compatiable in mobile view.**

Fixed Image issue customer review tab in velocity theme

---

packages/Webkul/Sales/src/Repositories/DownloadableLinkPurchasedRepository.php
packages/Webkul/Shop/src/Http/Controllers/DownloadableProductController.php

Fixed Download product issue #5663

---

packages/Webkul/Shop/src/Http/Controllers/ProductController.php
packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
packages/Webkul/Shop/src/Routes/store-front-routes.php
packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php

- Handled layered navigation without category as well.

Layered Navigation With And Without Category Handled

---

packages/Webkul/Tax/src/Http/Controllers/TaxRateController.php

Link: https://github.com/bagisto/bagisto/issues/5684

Tax Rate Import Issue Fixed #5684

---

tests/functional/Admin/Catalog/ProductCest.php

Added typing to string to fix the function test error.

Update ProductCest.php by adding typecasting to string to fix the function test error.

---

packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php

Link: https://github.com/bagisto/bagisto/issues/5722

Paypal Smart Button Fixed #5722

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/sales/transactions/create.blade.php

Link: https://github.com/bagisto/bagisto/issues/5648

Select Option Text Added #5648

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/slots.blade.php

#5719 
**Fixed issue ui issue when we try to make booking product in admin panel in mobile view**

Fixed ui issue of booking product admin panel

---

packages/Webkul/Core/src/Core.php

- Currency symbol issue fixed.

Currency symbol issue fixed

---

packages/Webkul/Admin/src/Resources/lang/en/app.php

Link: https://github.com/bagisto/bagisto/issues/5761

Fixed Typo #5761

---

packages/Webkul/Admin/src/Resources/views/customers/addresses/index.blade.php
tests/_support/Actions/CleanAction.php
tests/_support/ApiTester.php
tests/_support/FunctionalTester.php
tests/functional/Admin/Customer/AddressCest.php
tests/functional/Customer/CustomerCest.php

Link: https://github.com/bagisto/bagisto/issues/5774
- Reverted one address file.
- And cleaned some test case methods to avoid duplicacy.

Reverted One Address Index File #5774

---

packages/Webkul/Checkout/src/Cart.php

Link: https://github.com/bagisto/bagisto/issues/5451

Fixed infinite variant orders #5451

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/5687

Quantity Box Removed As From Backend It Is False #5687

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
packages/Webkul/Product/src/Http/Controllers/ReviewController.php

issue #5820

---

packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php

#5234 
>remove wishlist and compare from the header section

Enhancement done #5817

---

packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php

issue #5830 fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php

#5841 
> Add translation for notification title in arabic

notification-translation-issue-fixed

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

issue #5828 fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/catalog/products/create.blade.php

#5865 
>Translation added for product type

issue #5865 fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php

#5870 
> Translation added for account section

Fixex header-translation-issues

---

packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php

#5855 
> locale filter added on category datagrid

 Issue #5855 Fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php

Changes complete

---

packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php

Issue #5770 fixed

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

#5916
>Translation added for product  mass action

Issue #5916 Fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist-product.blade.php

Issue #5931 fixed

---

packages/Webkul/Paypal/src/Resources/lang/ar/app.php
packages/Webkul/Paypal/src/Resources/lang/en/app.php
packages/Webkul/Paypal/src/Resources/lang/fa/app.php
packages/Webkul/Paypal/src/Resources/lang/nl/app.php
packages/Webkul/Paypal/src/Resources/lang/tr/app.php

#5933 
> Warning message and translation added

Issue #5933 fixed

---

packages/Webkul/Admin/src/Resources/views/users/forget-password/create.blade.php

>asterisk icon added for required fields

asterisk icon added for required fields

---

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php

>Order-status-translation-done

Order-status-translation-done

---

packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php

#5942
> Required class added on event-booking products

 Issue #5942 Fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php

#5945 
> Place holder added for user's DOB

 Issue #5945 fixed

---

packages/Webkul/BookingProduct/src/Config/menu.php
packages/Webkul/BookingProduct/src/DataGrids/Admin/BookingDataGrid.php
packages/Webkul/BookingProduct/src/Http/Controllers/Admin/BookingController.php
packages/Webkul/BookingProduct/src/Http/Controllers/Controller.php
packages/Webkul/BookingProduct/src/Http/Controllers/Shop/BookingProductController.php
packages/Webkul/BookingProduct/src/Http/admin-routes.php
packages/Webkul/BookingProduct/src/Models/Booking.php
packages/Webkul/BookingProduct/src/Providers/BookingProductServiceProvider.php
packages/Webkul/BookingProduct/src/Resources/lang/ar/app.php
packages/Webkul/BookingProduct/src/Resources/lang/en/app.php
packages/Webkul/BookingProduct/src/Resources/lang/es/app.php
packages/Webkul/BookingProduct/src/Resources/lang/fa/app.php
packages/Webkul/BookingProduct/src/Resources/lang/it/app.php
packages/Webkul/BookingProduct/src/Resources/lang/nl/app.php
packages/Webkul/BookingProduct/src/Resources/lang/pt_BR/app.php
packages/Webkul/BookingProduct/src/Resources/lang/zh_CN/app.php
packages/Webkul/BookingProduct/src/Resources/views/admin/sales/bookings/index.blade.php

Issue #2918 fixed

---

packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php

#5915
> Mandarin locale added for notifications, API and auth

Issue #5915 Fixed

---

packages/Webkul/Notification/src/Http/Controllers/Admin/NotificationController.php
packages/Webkul/Notification/src/Repositories/NotificationRepository.php

Issue #5654 fixed

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Link: https://github.com/bagisto/bagisto/issues/5995

Filter Issue Fixed #5995

---

packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
packages/Webkul/Customer/src/Repositories/CustomerRepository.php
packages/Webkul/Sales/src/Models/Order.php

Link: https://github.com/bagisto/bagisto/issues/4356

New Customer Syncing Added #4356

---

config/queue.php
database/migrations/2022_03_15_160510_create_failed_jobs_table.php
packages/Webkul/Notification/src/Events/CreateOrderNotification.php
packages/Webkul/Notification/src/Events/UpdateOrderNotification.php

Link: https://github.com/bagisto/bagisto/issues/5921
- Setup configuration from the pusher.
- After that run queue listener command i.e. `php artisan queue:work --queue=broadcastable`
- Done :100:

Notification Fixed #5921

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/locale-currency.blade.php

Issue #6040 fixed

---

packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/default.blade.php

Issue #6039 fixed

---

packages/Webkul/Checkout/src/Cart.php

PHP Doc Wrong Path Issue Fix
PHP Doc Wrong Path Issue Fix

php doc wrong path fix

---

packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php

Issue #6112 fixed (Reserve attribute codes excluded from creation)

Issue #6112 fixed (Reserve attribute codes excluded from creation)

---

packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php

Issue #6114 fixed

---

packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php

Issue #6119 fixed

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php

Issue #6111 fixed

---

lang/hi_IN/auth.php
lang/hi_IN/pagination.php
lang/hi_IN/passwords.php
lang/hi_IN/validation.php

>Hindi Locale Added For validation

Hindi Locale Added For validation

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php

Issue #1466 fixed

---

packages/Webkul/Ui/src/DataGrid/DataGrid.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php

Issue #6132 fixed

---

packages/Webkul/Checkout/src/Cart.php

Issue #6134 fixed

---

packages/Webkul/Checkout/src/Cart.php

Issue #4959 fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/total/summary.blade.php

Issue #5964 fixed

---

packages/Webkul/Admin/src/DataGrids/CategoryProductDataGrid.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/reviews/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/edit.blade.php
packages/Webkul/Admin/src/Routes/catalog-routes.php
packages/Webkul/Category/src/Http/Controllers/CategoryController.php

Issue #2278 fixed

---

packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php

Issue #6144 fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php

#6162 
> Bold class added for table header

Issue #6162 Fixed

---

packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/event.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/event.blade.php

Issue #6158 fixed

---

packages/Webkul/Shop/src/Http/Controllers/ReviewController.php

Issue #6186 fixed

---

CHANGELOG for v1.x.x.md

v4.2-ChangeLog-update

---

packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php

Issue #6192 fixed

---

packages/Webkul/Admin/src/Resources/lang/en/app.php

Updated users page title

---

packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerGroupController.php
packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
packages/Webkul/Admin/src/Http/Controllers/ExportController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/ShipmentController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
packages/Webkul/Admin/src/Routes/notification-routes.php
packages/Webkul/CMS/src/Http/Controllers/Admin/PageController.php
packages/Webkul/Customer/src/Http/Controllers/AccountController.php
packages/Webkul/Customer/src/Http/Controllers/AddressController.php
packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
packages/Webkul/Customer/src/Http/Controllers/SessionController.php
packages/Webkul/Notification/src/Http/Controllers/Admin/NotificationController.php
packages/Webkul/Shop/src/Http/Controllers/DownloadableProductController.php
packages/Webkul/Shop/src/Http/Controllers/OrderController.php
packages/Webkul/Tax/src/Http/Controllers/TaxController.php
packages/Webkul/User/src/Http/Controllers/RoleController.php
packages/Webkul/User/src/Http/Controllers/SessionController.php
packages/Webkul/User/src/Http/Controllers/UserController.php

Removed extra middlewares

---

packages/Webkul/Velocity/publishable/assets/mix-manifest.json

- Updated manifest file for proper assets working as tables not getting visible in velocity theme.

Updated Manifest File

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

#6208
> .**badge** class added for product status

Issue #6208 Fixed

---

packages/Webkul/BookingProduct/src/Resources/lang/ar/app.php
packages/Webkul/BookingProduct/src/Resources/lang/es/app.php
packages/Webkul/BookingProduct/src/Resources/lang/fa/app.php
packages/Webkul/BookingProduct/src/Resources/lang/hi_IN/app.php
packages/Webkul/BookingProduct/src/Resources/lang/it/app.php
packages/Webkul/BookingProduct/src/Resources/lang/nl/app.php
packages/Webkul/BookingProduct/src/Resources/lang/tr/app.php
packages/Webkul/BookingProduct/src/Resources/lang/zh_CN/app.php
packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/slots.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/rental.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/slots.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/table.blade.php

#6217 
>Required class added and update translations

 Issue #6217 Fixed

---

packages/Webkul/Admin/src/DataGrids/SitemapDataGrid.php

> **target_blank**-added-for-sitemap-URL [ Link For Google ]

target_blank-added-for-sitemap-url

---

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php

Issue #6190 fixed

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php

Issue #5530 fixed

---

packages/Webkul/Checkout/src/Cart.php

Guest cart session is not getting removed after last item deletion

Guest cart session is not getting removed after last item deletion

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
packages/Webkul/Core/src/Core.php

Link 1: https://github.com/bagisto/bagisto/issues/6244
Link 2: https://github.com/bagisto/bagisto/issues/6246

Currency Symbol #6244 And Product Listing Fixed #6246

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

Issue #5354 fixed

---

packages/Webkul/BookingProduct/src/Resources/lang/ar/app.php
packages/Webkul/BookingProduct/src/Resources/lang/en/app.php
packages/Webkul/BookingProduct/src/Resources/lang/es/app.php
packages/Webkul/BookingProduct/src/Resources/lang/fa/app.php
packages/Webkul/BookingProduct/src/Resources/lang/hi_IN/app.php
packages/Webkul/BookingProduct/src/Resources/lang/it/app.php
packages/Webkul/BookingProduct/src/Resources/lang/nl/app.php
packages/Webkul/BookingProduct/src/Resources/lang/pt_BR/app.php
packages/Webkul/BookingProduct/src/Resources/lang/tr/app.php
packages/Webkul/BookingProduct/src/Resources/lang/zh_CN/app.php
packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/slots.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/slots.blade.php

Issue #2718 fixed

---

packages/Webkul/Admin/src/Resources/views/customers/reviews/edit.blade.php

Issue #6250 fixed

---

packages/Webkul/Shop/src/Resources/views/checkout/success.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/success.blade.php

Issue #6253 fixed

---

composer.lock

Link: https://github.com/bagisto/bagisto/issues/5067

Updated Bagisto REST API

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php

#6283
>Quantity field's  UI update in mini cart on the default theme

Issue #6283 fixed

---

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php

#6285
> Related link Added on dashboard cards.

Issue #6285 fixed

---

packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Bundle.php
packages/Webkul/Product/src/Type/Configurable.php

- Some duplicate calls were removed.

Duplicate Calls Removed 

---

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php

Not able to add a link by using info index in configuration.
[Updated: field-type: info index updated for configuration.]

[Updated: field-type: info index updated for configuration.]

---

packages/Webkul/Product/src/Database/Factories/ProductOrderedInventoryFactory.php
packages/Webkul/Product/src/Models/ProductOrderedInventory.php
packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
tests/unit/Sales/Order/OrderItemRepositoryCest.php

Link: https://github.com/bagisto/bagisto/issues/6290

Cancelled Product Inventory Issue Fix #6290

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/wishlist/wishlist-product.blade.php

#5931
> Remove compare option from the wishlist page

Remove-compare-option-from-wishlist

---

CHANGELOG for v1.x.x.md

> Change Log updated for V1.4.3

Change Log-updated for 4.3

---

packages/Webkul/Admin/src/Resources/views/account/edit.blade.php

#6324
> Warning message added for invalid image format

Issue #6324 Fixed

---

packages/Webkul/BookingProduct/src/Resources/lang/ar/app.php

#6335
>Arabic translation added for booking  products

Issue #6335 fixed

---

packages/Webkul/Velocity/package.json
packages/Webkul/Velocity/webpack.mix.js

Removed Dependency And Traces

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php

Link: https://github.com/bagisto/bagisto/issues/6317

Added Anchor Tag On Default Theme #6317

---

packages/Webkul/Checkout/src/Cart.php

Link: https://github.com/bagisto/bagisto/issues/6397

Fixed Exception In Merged Cart #6397

---

packages/Webkul/Core/src/Contracts/Validations/AlphaNumericSpace.php

Updated Validation

---

packages/Webkul/Shop/src/Resources/views/customers/account/address/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/6402

Fixed Address Delete Issue #6402

---

packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php

Link: https://github.com/bagisto/bagisto/issues/6401

Wishlist And Compare Added #6401

---

packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php

Link: https://github.com/bagisto/bagisto/issues/6313

Common Message Added #6313

---

packages/Webkul/Shipping/src/Shipping.php

Link: https://github.com/bagisto/bagisto/issues/6277

Shipping File Updated #6277

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php

Link: https://github.com/bagisto/bagisto/issues/6333

API Route Updated #6333

---

packages/Webkul/Product/src/Type/Grouped.php

Link: https://github.com/bagisto/bagisto/issues/6339

Group Product Condition Fixed #6339

---

packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php

fixed #6419

---

packages/Webkul/Admin/src/Resources/lang/en/app.php

#6423 
> Translation added for **payment pending** order status

Issue #6423 fixed

---

packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/payment.blade.php

#6434 
> Translation added for payment methods.

Issue #6434 fixed

---

packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php

#6452 
> Target _blank added for CMS pages

Issue #6452 Fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/products/price.blade.php

#6367 
> Percentage of discount amount is added in product-view page

Enhancement #6367 done

---

packages/Webkul/Velocity/src/Resources/views/shop/products/price.blade.php

Revert "Enhancement #6367 done"

---

packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php

#6459
> js function created for delete review

Issue #6459 fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/reviews/index.blade.php

#6459
> Delete review fixed for default theme

Issue #6459-fixed-default-theme

---

packages/Webkul/Core/src/Repositories/ChannelRepository.php

There was an extra find query in the update channel repository that was not used.

Remove extra find query on update channel

---

packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php

#6507
> Remove static URL from notification component

Issue #6507 fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php

#6479
> Responsive class on View-order table

Issue #6479 fixed

---

packages/Webkul/Product/src/Http/Controllers/ProductController.php
packages/Webkul/Product/src/Http/Controllers/ReviewController.php

https://github.com/bagisto/bagisto/issues/6518
Mass action issue from admin panel.

Product mass action issue on admin panel.

---

packages/Webkul/Product/src/Type/Configurable.php

Fixed there should not be an exception if the admin is trying to add a new variant for the configurable product #6463

---

packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php

#6426 
Changed the max input value to ordered qty

Fixed issue #6426

---

packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/ben/app.php
packages/Webkul/Shop/src/Resources/lang/de/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/es/app.php
packages/Webkul/Shop/src/Resources/lang/fa/app.php
packages/Webkul/Shop/src/Resources/lang/fr/app.php
packages/Webkul/Shop/src/Resources/lang/he/app.php
packages/Webkul/Shop/src/Resources/lang/pl/app.php
packages/Webkul/Shop/src/Resources/lang/ru/app.php
packages/Webkul/Shop/src/Resources/lang/tr/app.php
packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php

#6407
Inactive user should not allow to place an order.

Inactive user placing order issue fixed #6407

---

packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
packages/Webkul/Admin/src/Routes/sales-routes.php

#6355
Redirection after creating a refund to refund index page.

After refund, redirect to refund index page #6355

---

packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
packages/Webkul/Admin/src/DataGrids/EmailTemplateDataGrid.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/images.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/videos.blade.php
packages/Webkul/Admin/src/Resources/views/configuration/dependent-field-type.blade.php
packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
packages/Webkul/Checkout/src/Cart.php
packages/Webkul/Notification/src/Repositories/NotificationRepository.php
packages/Webkul/Paypal/src/Listeners/Transaction.php
packages/Webkul/Product/src/Helpers/Toolbar.php
packages/Webkul/Product/src/Listeners/ProductFlat.php
packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
packages/Webkul/Product/src/Repositories/ProductRepository.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade.php
packages/Webkul/Shop/src/Resources/views/guest/compare/compare-products.blade.php
packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/index.blade.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideQueryResolver.php
packages/Webkul/Ui/src/DataGrid/Traits/ProvideQueryStringParser.php
packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
packages/Webkul/Velocity/src/Helpers/Helper.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php

Changed else if to elseif (Followed PSR-2 standard)

Changed else if to elseif (Followed PSR-2 standard)

---

packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/ben/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php

#6370
Admin should not be able to disable all shipping method.
At least one shipping method should be selected.

At-least one shipping method should select #6370

---

.github/workflows/ci.yml
composer.json
composer.lock
config/app.php

- Dompdf updated.
- Config files updated.

Barryvdh Dompdf Updated

---

packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php

Validation for percentage discount amt  added.

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php

Fixed issue #6458

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php

#6427 
> Change mouse property if cart is empty

Enhancement #6427 done

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/coupon.blade.php

#6417
> Flash Message Added while coupon applied/Removed

Enhancement #6417 done

---

packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php

Reverts bagisto/bagisto#6568
Reason (Calling multiple time validate function, can be done by preparing array and pass that array to the validate function)

Revert "Validation for percentage discount amt  added."

---

packages/Webkul/CartRule/src/Helpers/CartRule.php

Hi, Hope you're doing well
Some PHP docs are wrong and using the wrong namespace

fix php docs

---

packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/text.blade.php

fixed_issue #6494

---

packages/Webkul/Ui/src/DataGrid/Traits/ProvideDataGridPlus.php
packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
packages/Webkul/Ui/src/Resources/lang/en/app.php

Fixed issue #5392

---

packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php

#6340
Selected max value for default price selection.

Default selection for price filter resolved  #6340

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php

Revert "Added space in v-validate #6458"

---

packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
packages/Webkul/CartRule/src/Http/Requests/CartRuleRequest.php
packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
packages/Webkul/CatalogRule/src/Http/Requests/CatalogRuleRequest.php

#6554
Added validation for percentage amount for Catalog and Cart Rule and Handled validation using **FormRequest** and removed validation from controller.

Validation for percentage amt for Cart and Catalog Rule.

---

packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/ben/app.php
packages/Webkul/Shop/src/Resources/lang/de/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/es/app.php
packages/Webkul/Shop/src/Resources/lang/fa/app.php
packages/Webkul/Shop/src/Resources/lang/fr/app.php
packages/Webkul/Shop/src/Resources/lang/he/app.php
packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
packages/Webkul/Shop/src/Resources/lang/it/app.php
packages/Webkul/Shop/src/Resources/lang/ja/app.php
packages/Webkul/Shop/src/Resources/lang/nl/app.php
packages/Webkul/Shop/src/Resources/lang/pl/app.php
packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
packages/Webkul/Shop/src/Resources/lang/ru/app.php
packages/Webkul/Shop/src/Resources/lang/sin/app.php
packages/Webkul/Shop/src/Resources/lang/tr/app.php
packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php

#6371
Flash messages appear when catalog or cart rule applied

Fixed issue #6371

---

packages/Webkul/Admin/src/Resources/lang/ben/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/videos.blade.php
packages/Webkul/Core/src/Core.php

Fixed issue #5801

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php

Wishlist not showing if removed all items from last page.

---

packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

#6444 
> redirect page on the login page if the guest user is trying to add item to wishlist

Issue #6444 fixed

---

packages/Webkul/Shop/src/Http/Controllers/CartController.php
packages/Webkul/Shop/src/Resources/lang/ar/app.php
packages/Webkul/Shop/src/Resources/lang/ben/app.php
packages/Webkul/Shop/src/Resources/lang/de/app.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/lang/es/app.php
packages/Webkul/Shop/src/Resources/lang/fa/app.php
packages/Webkul/Shop/src/Resources/lang/fr/app.php
packages/Webkul/Shop/src/Resources/lang/he/app.php
packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
packages/Webkul/Shop/src/Resources/lang/it/app.php
packages/Webkul/Shop/src/Resources/lang/nl/app.php
packages/Webkul/Shop/src/Resources/lang/pl/app.php
packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
packages/Webkul/Shop/src/Resources/lang/ru/app.php
packages/Webkul/Shop/src/Resources/lang/sin/app.php
packages/Webkul/Shop/src/Resources/lang/tr/app.php
packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php

#6364  #6393
Showing warning in case already applied a coupon code for cart.

Showing warning in case coupon already applied.

---

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
packages/Webkul/Sales/src/Config/system.php

#6428
Changed the type of input field from text to number

Fixed issue #6428

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php

Fixed issue #6359

---

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php

Revert "Fixed issue #6359"

---

packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/ben/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php

At least one payment method should be enabled #6370

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php

Wish list redirection issue #6635

---

packages/Webkul/Core/src/Resources/views/blade/tracer/style.blade.php

Image height fixed for default theme #6654

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

Fixed issue #6461

---

CHANGELOG for v1.x.x.md

>ChangeLog Updated  For V1.4.4

ChangeLog Updated V1.4.4

---

packages/Webkul/Velocity/src/Models/VelocityMetadata.php

Velocity meta data update issue fixed #6687

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php

Fixed issue #6679

---

packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php

Fixed issue #6345

---

packages/Webkul/Velocity/src/Resources/views/shop/products/view.blade.php

Fixed issue #6394

---

app/Http/Kernel.php
app/Http/Middleware/TrustHosts.php

- Trust hosts class middleware added.

Trust Hosts Class Middleware Added

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
packages/Webkul/Admin/src/Resources/views/cms/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/events/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/templates/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/sitemaps/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/sliders/index.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/index.blade.php
packages/Webkul/Admin/src/Resources/views/users/users/index.blade.php

Permission check for add button on different views on admin panel #6697

---

packages/Webkul/Product/src/Repositories/ProductFlatRepository.php
packages/Webkul/Shop/src/Http/Controllers/ProductController.php

Issue #6422 fixed (Reverted all changes related to this issues as solution adding performance overhead)

Issue #6422 fixed

---

.env.example
CHANGELOG for v1.x.x.md

ChangeLog-updated V1.4.5

---

packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Shop/src/Resources/views/products/view/configurable-options.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

Special price option added product  if spacial price exist for configurable product. #6699

---

packages/Webkul/Category/src/Repositories/CategoryRepository.php

category slug update for requested locale #6725

---

packages/Webkul/Shop/src/Http/Controllers/CartController.php

Fixed Issue  #6732

---

CHANGELOG for v1.x.x.md

Changelog-v1.4.5-updated

---

packages/Webkul/Admin/src/Resources/views/customers/reviews/edit.blade.php
packages/Webkul/Sales/src/Repositories/OrderRepository.php

[Fixed: #6745]

---

packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php

Issue #6797 fixed

---

CHANGELOG for v1.x.x.md

improved overall text and errors

Update CHANGELOG for v1.x.x.md

---

packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php

#6844
>Add  background color on orders status for Downloadable Products

Issue #6844 fixed

---

packages/Webkul/Shop/src/Resources/lang/ar/app.php

#6747
>Default address translation issue

Issue #6747 fixed

---

packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php

#6905 
>Fixed validation message of shipping qty

Issue 6905 Fixed

---

packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php

Validations updates on back end, for customer address.

Enhancement: Customer address validation updates.

---

packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php

Just found a couple more pages where we need to have responsive tables.
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/195308462-9049892e-f3c1-4f3e-971e-c5b516965917.png) | ![image](https://user-images.githubusercontent.com/4408379/195308321-f9db0c7b-d765-47ae-818f-ffcb7be7f2c6.png) |

Make tables responsive on Families page

---

packages/Webkul/Product/src/Type/Configurable.php

cart item parent image showing issue if child image not uploaded #6765

---

packages/Webkul/Product/src/Models/ProductDownloadableLink.php
packages/Webkul/Product/src/Models/ProductDownloadableSample.php

[Updated: Downloadable Product Link & Simple models updated.]

[Updated: Downloadable Product Link & Simple models updated.]

---

packages/Webkul/Shop/src/Resources/lang/ru/app.php

Fixes #6892
Add couple of RU translations. Change some of them to make them look more natural
Just visit the page, when they are used

Add some missed RU translations. #6892

---

packages/Webkul/Product/src/Http/Requests/InventoryRequest.php

fixed Inventory Updated issues #6900

---

packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php

[Added: view render event to CMS blade file.]

[Added: view render event to CMS blade file.]

---

packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

[Fixed: #6884]

---

packages/Webkul/Admin/src/Resources/lang/fa/app.php

There was a minor issue with Farsi translations and it's fixed now.

Farsi translation corrected

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php

[Fixed: #6755]

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-left.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-right.blade.php

Added Footer links for velocity #6757

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php

Product link visible even when product individual visibility is inactive on admin #6756

---

packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php

#6729
https://prnt.sc/2v2Dxi_VzUHv

Product searching on bundle products with name and sku  #6729

---

packages/Webkul/Core/src/Core.php

[Fixed: #6761]

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php

#6957
>Customer-Orders-translation-fixed

Issue #6957  Fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/customers/session/index.blade.php

Issue #6955 fixed

---

composer.json
composer.lock

Remove php pusher dependency from the composer.json file

Remove php pusher from composer file

---

packages/Webkul/Core/src/Resources/lang/hi_IN/app.php
packages/Webkul/Core/src/Resources/lang/hi_IN/validation.php
packages/Webkul/Tax/src/Resources/lang/hi_IN/app.php

feat: added Hindi translation to `/packages/Webkul/Core/src/Resources/lang`

---

packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php

#6993 
Scroll Bar added
1. Go to Admin -> Catalog -> Products -> Create a new Booking Product - > Select Event Booking.
2. Now check the Ticket Section.
3. Inspect the details in Mobile view, there we will be able to see the issue.

Issue Fixed #6993

---

packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php

Added a badge in the datagrid for the status column

Added status badge

---

lang/it/auth.php
lang/it/pagination.php
lang/it/passwords.php
lang/it/validation.php

This is the Italian translation.
Don't know if there are other strings to translate.

Italian translation

---

packages/Webkul/Shop/src/Resources/views/customers/signup/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/emails/customer/forget-password.blade.php
packages/Webkul/Shop/src/Routes/customer-routes.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/forgot-password.blade.php

[Fixed: reset password route was missing.]

---

packages/Webkul/Shop/src/Resources/lang/bn/app.php

fixed the translation

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/ben/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/edit.blade.php
packages/Webkul/Core/src/Core.php
packages/Webkul/Core/src/Database/Migrations/2022_11_09_184539_add_decimal_columns_to_currency_table.php
packages/Webkul/Core/src/Models/Currency.php

add decimal to currency

---

packages/Webkul/Product/src/Console/Commands/Indexer.php
packages/Webkul/Product/src/Helpers/Indexers/AbstractIndexer.php
packages/Webkul/Product/src/Helpers/Indexers/Price.php
packages/Webkul/Product/src/Helpers/Indexers/Price/AbstractType.php

#7113
>Added selective indexing

Added selective indexing

---

packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/event.blade.php
packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/event.blade.php

Ticket Booking UI Description Issue #7128

---

packages/Webkul/Product/src/Type/AbstractType.php
packages/Webkul/Product/src/Type/Grouped.php

Fixed For Configurable And Grouped Product #6953

---

packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
packages/Webkul/Shop/src/Http/Controllers/CartController.php
packages/Webkul/Shop/src/Http/Controllers/ProductController.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php

Issue Fixed [#7137]

---

packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerGroupController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/ShipmentController.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php

>[Flash message issue fixed](https://github.com/bagisto/bagisto/issues/6739)
|  Before |  After |
| ---------- | ------- |
|![before](https://user-images.githubusercontent.com/86394952/208079226-a0ffdfa9-3aa4-476d-99ae-01a7303c7fd9.png) |![after](https://user-images.githubusercontent.com/86394952/208079262-b1021df7-7f0a-4600-8a60-b868cc592320.png)

Flash message issue fixed

---

packages/Webkul/Ui/src/Resources/assets/sass/app.scss

#7217
>Add margin for Notify Customer checkbox

issue #7217 fixed

---

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php

issue  #7235

---

packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php

Issue #7244 resolved

---

composer.json
composer.lock
config/app.php
packages/Webkul/Core/src/Console/Commands/BagistoPublish.php
packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
packages/Webkul/Shop/src/Resources/views/cms/page.blade.php
packages/Webkul/Shop/src/Resources/views/home/index.blade.php
packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/cms/page.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/home/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php

Link: https://github.com/bagisto/bagisto/issues/7067

Removed DB Blade Compiler #7067

---

packages/Webkul/Customer/src/Http/Controllers/ResetPasswordController.php

Fixed issue #7227

---

packages/Webkul/Admin/src/Resources/views/sales/address.blade.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

fixed invoice issue

---

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss

Category localewise

---

packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss

UI-filter Fixed

---

packages/Webkul/Core/src/Core.php

#7283
>**_getDefaultChannelLocaleCode()_** Method create inside **_core.php_** file

Issue #7283 fixed

---

packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/datetime.blade.php

Fixed issue #7177

---

packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php

issue fixed #7295

---

packages/Webkul/Core/src/Contracts/Validations/CommaSeparatedInteger.php

- Mass update and mass delete fixed.

Only natural number checking

---

packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php

Added view_render events 
```
bagisto.admin.catalog.categories.create.before
bagisto.admin.catalog.categories.create.after
bagisto.admin.catalog.products.create.before
bagisto.admin.catalog.products.create.after
```

Admin catalog viewevents

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

#3454 
>The shipping method will be **selected automatically** if only one shipping method is available.

Shippingmethod

---

packages/Webkul/Product/src/Type/Configurable.php

issue #7201

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/index.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

#6972
| Before  |  After |
|-----------|---------|
| ![before](https://user-images.githubusercontent.com/86394952/205839787-8f2cafa1-161c-44a0-9f27-e493d471dca1.png) | ![after](https://user-images.githubusercontent.com/86394952/205839820-2462cbe5-f8f1-4aad-b046-659bb8ddb314.png)

Issue #6972  Fixed

---

packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php

Link: https://github.com/bagisto/bagisto/issues/7281

Added Hot Fix For Shipment #7281

---

packages/Webkul/Velocity/src/Resources/views/shop/products/add-to-cart.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php

#7320
>wishlist text removed from card body

wishlist text removed

---

packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss

wishlist-ui-issue-code-optimize

---

config/.gitignore
config/imagecache.php

Added image cache file

---

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php

Elastic search bug fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

Issue #7200 fixed

---

packages/Webkul/Velocity/src/Resources/lang/en/app.php
packages/Webkul/Velocity/src/Resources/lang/it/app.php
packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php

#7364
>Capitalize velocity meta data text

Issue #7364 fixed

---

packages/Webkul/Core/src/Contracts/Validations/Address.php
packages/Webkul/Core/src/Contracts/Validations/AlphaNumericSpace.php

Arabic Validation issue #7181

---

packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
packages/Webkul/Ui/src/Resources/assets/sass/app.scss

issue #7371 fixed

---

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
packages/Webkul/Product/src/Repositories/ProductRepository.php

#7383 
> Issue occur with elastic search fixed

Issue #7383 occurred with elastic search fixed

---

packages/Webkul/BookingProduct/src/Resources/views/admin/sales/bookings/index.blade.php

#6989 
-> Calennder Overlapping which is showing in sale on the Booking page issue has been fixed.

Issue fixed in calender overlaping ui

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Product/src/Http/Controllers/ReviewController.php

fixed issue #7407

---

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php

Fixed Search Issues

---

packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php

#7332 
> Check permission for compare and wishlist option. on velocity

#7332 issue fixed

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php

Validation message is showing while creating catalog rules

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/bn/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php

#7407 
Translation in all locales

issue #7407 fix

---

packages/Webkul/Admin/src/Resources/assets/sass/partials/_dark.scss

issue #7459 fixed

---

packages/Webkul/Product/src/Repositories/ProductRepository.php

Now not getting exception while trying to create configurable product.

---

packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/create.blade.php

#7420
>Change route for campaign page in marketing section.

Issue #7420 Resolved

---

packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss

#7356 
->dashboard configuration menu icon issue resolved

dashboard menu icon issue resolved

---

packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php

Now we can set street address lines

---

packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue

issue #7466 fixed

---

packages/Webkul/Ui/src/Http/routes.php

#6723 
> The '**ui-kit**' & '**helper-classess**' route can not be accessed when the app env is production.

Issue fixed #6723

---

composer.json
composer.lock
config/app.php
packages/Webkul/DebugBar/src/Providers/DebugBarServiceProvider.php

- Some composer dependency updates were fixed.

Composer Dependency Update

---

packages/Webkul/Admin/src/Resources/views/customers/create.blade.php

Customer calender

---

packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php

#7281 
>Remove extra input fields from inventory section of shipping page

shipping imput filed fixed

---

packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php

Issue #7452 fixed.

---

packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss

Issue #7450 fixed

---

packages/Webkul/Ui/src/Resources/assets/js/components/image/image-wrapper.vue
packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php

#7402 
https://github.com/bagisto/bagisto/commit/4d84036d33b1a953095c06d69f50c77afc9a8ae3

add limit to Velocity advertisement image

---

packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php

issue #7419 fixed

---

packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php

#7360
>fix meta data UI for mobile

Issue #7360 fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php

Issue #7476  fixed

---

packages/Webkul/Product/src/Helpers/Toolbar.php
packages/Webkul/Product/src/Repositories/ProductRepository.php

Link: https://github.com/bagisto/bagisto/issues/7180

Default number added #7180

---

packages/Webkul/Product/src/Listeners/Product.php

Configurable price changed issue fixed #7216

---

packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php
packages/Webkul/Ui/src/DataGrid/DataGrid.php

https://github.com/bagisto/bagisto/issues/6703

Improvised cms page datagrid #6703

---

packages/Webkul/Product/src/Type/AbstractType.php

Link: https://github.com/bagisto/bagisto/issues/7492

File attribute issue fixed #7492

---

packages/Webkul/Velocity/src/Resources/assets/images/Arrow-Down-Light.svg
packages/Webkul/Velocity/src/Resources/assets/sass/app.scss

issue #7521 fixed

---

packages/Webkul/Velocity/src/Resources/assets/js/UI/components/mini-cart.vue

issue #7520 fixed

---

packages/Webkul/Admin/src/DataGrids/CartRuleCouponDataGrid.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
packages/Webkul/Admin/src/Routes/marketing-routes.php

issue #7518 fixed

---

packages/Webkul/Category/src/Models/Category.php
packages/Webkul/Core/src/Eloquent/TranslatableModel.php
packages/Webkul/Core/src/Helpers/Locales.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
pint.json

Child level and locale level category handled #7517

---

packages/Webkul/Product/src/Models/Product.php
packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php

Fixed locale issue

---

packages/Webkul/Admin/src/Validations/ConfigurableUniqueSku.php
packages/Webkul/Product/src/Type/Configurable.php

issue #7532 fixed

---

CHANGELOG for v1.x.x.md

changelog file of v1.5.0

---

packages/Webkul/Shop/src/Resources/assets/js/app.js
packages/Webkul/Shop/src/Resources/views/components/example.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php

Product blade component added

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage.blade copy.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php
packages/Webkul/Shop/src/Resources/views/home/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/index.blade copy.php
packages/Webkul/Shop/vite.config.js

Product listing

---

packages/Webkul/Shop/src/Http/Controllers/Customer/ForgotPasswordController.php
packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php
packages/Webkul/Shop/src/Http/Controllers/Customer/ResetPasswordController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
packages/Webkul/Shop/src/Routes/customer-routes.php

create signup page & login page 2.0.0

---

packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php
packages/Webkul/Shop/src/Routes/store-front-routes.php

Dynamic footer added and seeder updated

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-checkout.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
packages/Webkul/Shop/src/Resources/views/emails/customer/forget-password.blade.php
packages/Webkul/Shop/src/Resources/views/emails/customer/verification-email.blade.php
packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
packages/Webkul/Shop/src/Routes/customer-routes.php

Update route name in customer section 
add route grouping

Re-factor route name 

---

packages/Webkul/Core/src/Core.php
packages/Webkul/Product/src/Database/Migrations/2022_10_28_201144_add_columns_in_product_flat_table.php

https://github.com/bagisto/bagisto/issues/7555

fixed table prefix and add update core dev version #7555

---

packages/Webkul/Shop/src/Resources/views/components/dropdown/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/dropdown/menu/item.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php

Dropdown added

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php

added customer drop-down in Header

added customers drop-down

---

packages/Webkul/Shop/src/Http/Controllers/Customer/ResetPasswordController.php
packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/success.blade.php
packages/Webkul/Shop/src/Routes/checkout-routes.php

compleated order-success page

---

composer.json
composer.lock
packages/Webkul/Shop/src/Http/Controllers/Customer/OrderController.php
pint.json

- Simplified JSON.
- Moved some dev dependencies.
- Alphabetically sorted all the autoloads.
- Removed unwanted keys.

Composer JSON File Refined

---

packages/Webkul/Shop/src/Resources/views/categories/filters.blade.php
packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
packages/Webkul/Shop/src/Resources/views/components/range-slider/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/categories/filters.blade.php

Price range slider added

---

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
packages/Webkul/Shop/src/Http/Resources/CartItemResource.php
packages/Webkul/Shop/src/Http/Resources/CartResource.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/products/view.blade.php

Update cart and mini cart formatted price

Cart response update with resource and added formatted price

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
packages/Webkul/Shop/src/Resources/views/components/quantity-changer/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view.blade.php

2.x quantity changer

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php

Added option to return login page and correct language issues.

minor changes in language or return to login page.

---

packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Added shimmer for Wishlist page

Added shimmer for customer Wishlist page

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view.blade.php

Fixed cart shimmer issue and product view page pricing ui issue

Fixed cart shimmer issue and product view page pricing ui issue

---

packages/Webkul/Product/src/Type/AbstractType.php

Link: https://github.com/bagisto/bagisto/issues/7668

Nullable key issues fixed for configurable product

---

packages/Webkul/Checkout/src/Traits/CartTools.php
packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/cards/grid.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/cards/list.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/products/cards/list.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Added Shimmer for cards list page
Changed colour of sale icon on product cards. 
Quantity changer issue fixed in wish-list page.

Shimmer for cards/list page 

---

packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php

Changes empty result message

---

packages/Webkul/Shop/src/Resources/views/components/products/star-rating.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php

Fixed account review page issue

Fixed account review page issue

---

packages/Webkul/Shop/src/Http/Resources/ProductResource.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/home/index.blade.php

Fixed image loading issue on wish-list shimmer.
Fixed Final price issue.
Fixed language override issue.

Fixed shimmer image loading issue on wishlist page .

---

packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php
packages/Webkul/Shop/src/Http/Resources/ProductResource.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Routes/api.php

Added wish-list delete-all functionality.
Fixed UI of button.

Add delete all functionality in wish-list and fixed button UI

---

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php

Fixed category navigation issue

Fixed category navigation issue

---

packages/Webkul/Product/src/Contracts/ProductReviewAttachment.php
packages/Webkul/Product/src/Database/Migrations/2023_06_27_163529_rename_product_review_images_to_product_review_attachments.php
packages/Webkul/Product/src/Models/ProductReview.php
packages/Webkul/Product/src/Models/ProductReviewAttachment.php
packages/Webkul/Product/src/Models/ProductReviewAttachmentProxy.php
packages/Webkul/Product/src/Providers/ModuleServiceProvider.php
packages/Webkul/Product/src/Repositories/ProductReviewAttachmentRepository.php
packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
packages/Webkul/Shop/src/Http/Controllers/ReviewController.php

Rename table product_review_images to product_review_attachment.
Add default type nullable to image in column "type".

Rename table product_review_images

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/summary.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/index.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/coupon.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/payment.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/shipping.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/summary.blade.php
routes/breadcrumbs.php

Changes done in language according to file structure

---

packages/Webkul/Shop/src/Resources/views/products/view/types/downloadable.blade.php

Fixed downloadable links checkbox ui issue

Fixed downloadable links checkbox ui issue

---

packages/Webkul/Shop/src/Resources/views/products/view.blade.php

Product view page add to wishlist issue fixed.

Product view page

---

packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Fixed wishlist shimmer issue

---

packages/Webkul/Shop/src/Http/Resources/CartItemResource.php
packages/Webkul/Shop/src/Http/Resources/WishlistResource.php

Fixed cart item options issue

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/layouts/account/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Some changes in UI to make responsive
Added shimmer according to UI

Changes in wishlist UI and shimmer

---

packages/Webkul/Product/src/Database/Migrations/2023_06_27_163529_rename_product_review_images_to_product_review_attachments.php
packages/Webkul/Product/src/Models/ProductReviewAttachment.php
packages/Webkul/Product/src/Repositories/ProductReviewAttachmentRepository.php
packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
packages/Webkul/Shop/src/Http/Resources/ProductReviewResource.php
packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php
packages/Webkul/Shop/src/Resources/views/components/image/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
packages/Webkul/Shop/src/Routes/api.php

Image and video picker component.

Image and video picker component.

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/onepage/index.blade.php

Fixed checkout shimmer issue

---

packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/index.blade.php

Shimmer issue fix of shipping methods.

shimmer issue fix for shipping methods.

---

packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

Review page UI and functionality changes done.

Review page

---

packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

Fix reivew card issue.

---

packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/payment.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/shipping.blade.php
packages/Webkul/Shop/src/Resources/views/components/drawer/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php

Added front end for RTL.
Added grid active CSS on category page.

Added Front  for  RTL

---

packages/Webkul/BookingProduct/src/Type/Booking.php
packages/Webkul/Product/src/Type/Bundle.php
packages/Webkul/Product/src/Type/Configurable.php
packages/Webkul/Product/src/Type/Grouped.php
packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/coupon.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/onepage/address.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/onepage/payment-method.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/onepage/shipping-method.blade.php

Fixed coupon issue on one page.
Fixed shimmer issue on one page.
Fixed category issue on RTL.
Fixed some language issues.

Fixed minor issues

---

packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

grid issue fix.

---

packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

Fixed input field ui issue.
Fixed list shimmer image issue.

Input field UI issues

---

packages/Webkul/Category/src/Models/Category.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php

Hamburger menu for mobile view.

Hamber drawer.

---

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php

Show dropdown icon.

---

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
packages/Webkul/Shop/src/Resources/views/products/view.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

Removed button inline css and use classes

Removed button inline css and use classes

---

packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php

Added sign-up with social media and removed sprite icons

Added sign-up with social media and removed sprite icons

---

packages/Webkul/Shop/src/Resources/views/components/dropdown/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php

Locale and Currency switcher ui issues fixed

Locale and Currency switcher ui issues fixed

---

packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Added shimmer for wishlist

---

packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/categories/toolbar.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Fixed shimmer issues appearing in cart page.
Fixed category toolbar shimmer issue.

Fixed shimmer issues 

---

packages/Webkul/Category/src/Models/Category.php
packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php

[Fixed category url issue](https://github.com/bagisto/bagisto/commit/8be83e7dac83b03541e96d6f63b0cbca7e795e2b)

Fixed category url issue

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php

Fixed cart item details issue.
Fixed review mobile UI issue.

Fixed cart item details issue

---

packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php

Add secondary button class

---

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
packages/Webkul/Shop/src/Resources/views/components/quantity-changer/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php

Refactorred code

---

packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/products/cards/grid.blade.php
packages/Webkul/Shop/src/Resources/views/components/shimmer/products/cards/list.blade.php

Remove color options from product card

Remove color options from product card

---

packages/Webkul/Checkout/src/Models/Cart.php

Optimized cart

---

packages/Webkul/Admin/src/Resources/assets/css/app.css

added admin input classes

---

packages/Webkul/Admin/src/Resources/assets/css/app.css
packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/label.blade.php

added class in form component

---

packages/Webkul/Checkout/src/Models/Cart.php
packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php

Optimized checkout page

---

packages/Webkul/Admin/src/Resources/views/components/example.blade.php
packages/Webkul/Admin/src/Resources/views/components/modal/index.blade.php

[Add admin modal](https://github.com/bagisto/bagisto/commit/8ca7a7d14bcc313da5159beb2883c0d869b8e562)

Add admin modal

---

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php

[Add admin switch input field.](https://github.com/bagisto/bagisto/commit/3390c7acb5601c103fa871782c6e56213dd8f923)

Add admin switch input field.

---

packages/Webkul/Shop/src/Resources/lang/en/app.php
packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php

Added missing lang in shop package .

Added missing lang in shop package 

---

packages/Webkul/Admin/src/Http/Controllers/Core/ExchangeRateController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/create.blade.php-old
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php-old
packages/Webkul/Admin/src/Routes/settings-routes.php

added exchange-rate create page

Added exchange-rate create page

---

packages/Webkul/Admin/src/Resources/views/settings/currencies/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/locales/create.blade.php

[Add server validation.](https://github.com/bagisto/bagisto/commit/d3a1fb863ef06988121b0f1a5b1354098ab00eba)

Add server validation.

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/error.blade.php
packages/Webkul/Admin/src/Resources/views/customers/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/groups/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/locales/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/users/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/users/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php

Fixed appearing issues and add  page tittles

Fixed appearing issues and add  page tittles 

---

packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
packages/Webkul/Product/src/Helpers/SEO.php
packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php
packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
packages/Webkul/Shop/src/Resources/views/products/view.blade.php
packages/Webkul/Shop/src/Routes/store-front-routes.php
packages/Webkul/Sitemap/src/Models/Category.php
packages/Webkul/Sitemap/src/Models/Product.php
packages/Webkul/SocialShare/src/Resources/views/links/email.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/facebook.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/linkedin.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/pinterest.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/twitter.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/whatsapp.blade.php
packages/Webkul/SocialShare/src/Resources/views/share.blade.php
routes/breadcrumbs.php

fixed social share issue

---

packages/Webkul/Admin/src/Http/Controllers/Tax/TaxCategoryController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/create.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/create.blade.php-old
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/index.blade.php-old
packages/Webkul/Admin/src/Resources/views/tax/tax-rates/create.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/tax/tax-rates/index.blade.php-old
packages/Webkul/Admin/src/Routes/settings-routes.php

Added tax-category page.
Added index pages for tax-rate and category.

Added tax category page

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php

added new inventory source page.

added new inventory source page

---

packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php
packages/Webkul/Admin/src/Resources/views/layouts/nav-left.blade.php

[Sidebar configuration menu issue fixed.](https://github.com/bagisto/bagisto/commit/6a460a397bf0084356e647b7b062d794768fa616)

Sidebar configuration menu issue fixed.

---

packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php

[Sidebar menu active and inactive.](https://github.com/bagisto/bagisto/commit/3aaeaf707d938cd66225aeebcc8cfb60d59c5f83)

Sidebar menu active and inactive.

---

packages/Webkul/Admin/src/Resources/views/components/media/index.blade.php

[Media component warning in console bug fixed.](https://github.com/bagisto/bagisto/commit/489ecc6464b5a8e5a6e02a8762f4bbf556ff8e76)

Media component warning in console bug fixed.

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php
packages/Webkul/Admin/src/Resources/views/users/forget-password/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/reset-password/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php

Added user login page

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php

2.x admin code refinement

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/tax/tax-categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/edit.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/index.blade.php

updated user role page.
updated tax category create page.

updated user role page

---

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/edit.blade.php

fixed tree issue in user role/edit and category/edit page.

fixed tree issue in user role/edit and category/edit page

---

packages/Webkul/SocialShare/src/Resources/views/links/twitter.blade.php
packages/Webkul/SocialShare/src/Resources/views/links/whatsapp.blade.php

Fix template not found error.

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/events/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/events/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/templates/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/templates/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/sitemaps/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/sitemaps/index.blade.php

Add missing required field class

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/edit.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/roles/edit.blade.php
packages/Webkul/Admin/src/Resources/views/users/users/edit.blade.php

added cancel buttons in all pages.

added cancel buttons in all pages

---

packages/Webkul/Admin/src/DataGrids/LocalesDataGrid.php
packages/Webkul/Admin/src/Resources/assets/js/app.js
packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php

Attribute Create page code optimization and code refactor.

2.x admin code refactor

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php

added shipment view page

---

packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/customers/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php

Added cancel buttons in sales section.
fixed some UI and lang issue.
fixed default address order issue.

Fixed some issues

---

packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php

added some columns in order data-grid.

Order data-grid

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php

customer data-grid

---

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/customers/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
packages/Webkul/Admin/src/Resources/views/sales/refunds/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php

Refund Page

---

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php

Fixed datagrid ui issues

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php

added customer datagrid

---

packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php

Datagrid ui fixed

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/view.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php
packages/Webkul/Admin/src/Routes/customers-routes.php

Added mass action on customer data-grid.
Added customer account delete functionality.

Mass-action on data-grid

---

packages/Webkul/Admin/src/DataGrids/OrderDataGrid.php
packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
packages/Webkul/Admin/src/Resources/views/sales/orders/images.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
packages/Webkul/DataGrid/src/DataGrid.php

[Datagrid closure and orderdatagrid images issue fix.](https://github.com/bagisto/bagisto/commit/2cfa2bb29435c8494024a7042b7b8747b06da28a)

:rocket: feat:Datagrid closure and orderdatagrid images issue fix.

---

packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/index.blade.php
packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php

Updated Customer data-grid

---

packages/Webkul/Admin/src/Resources/views/configuration/dependent-field-type.blade.php
packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php
packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php

Configuration page refactored

---

packages/Webkul/Product/src/Helpers/Indexers/Flat.php

Fixed Product SKU issue

---

packages/Webkul/DataGrid/src/Action.php
packages/Webkul/DataGrid/src/Column.php
packages/Webkul/DataGrid/src/DataGrid.php
packages/Webkul/DataGrid/src/Enums/ColumnTypeEnum.php
packages/Webkul/DataGrid/src/MassAction.php

:rocket: feat: datagrid code refinement

---

packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/DataGrid/src/Column.php
packages/Webkul/DataGrid/src/DataGrid.php
packages/Webkul/DataGrid/src/Enums/FormInputTypeEnum.php
packages/Webkul/DataGrid/src/Enums/RangeOptionEnum.php
packages/Webkul/DataGrid/src/MassAction.php

- Fixed mass update option.
- Fixed range option.

fix: fixed mass update options and range options

---

packages/Webkul/Admin/src/Config/acl.php
packages/Webkul/Admin/src/Config/menu.php
packages/Webkul/Admin/src/DataGrids/Customers/AddressDataGrid.php
packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php
packages/Webkul/Admin/src/DataGrids/Customers/ReviewDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
packages/Webkul/Admin/src/Http/Controllers/Customer/ReviewController.php
packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/customers/confirm-password.blade.php
packages/Webkul/Admin/src/Resources/views/customers/customers/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
packages/Webkul/Admin/src/Routes/customers-routes.php

Fixed Typo

---

packages/Webkul/Admin/src/Config/acl.php

Fixed acl issue

---

packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php

Fixed datagrid action icon hover ui issue

Fixed datagrid action icon hover ui issue

---

packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/catalog/attributes/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/index.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/bundle.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/forget-password/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/reset-password/create.blade.php
packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php
packages/Webkul/Admin/src/Routes/settings-routes.php

Fixed ui issues

---

packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php

Fixed family panel radius ui issue

Fixed family panel radius ui issue

---

packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php

Order status label and payment method title issue fixed

Order status label and payment method title issue fixed

---

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php
packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/customers/edit.blade.php
packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/sitemaps/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/exchange_rates/index.blade.php
packages/Webkul/Admin/src/Resources/views/tax/categories/index.blade.php
packages/Webkul/Admin/src/Routes/cms-routes.php
packages/Webkul/Admin/src/Routes/customers-routes.php
packages/Webkul/Admin/src/Routes/marketing-routes.php
packages/Webkul/Admin/src/Routes/settings-routes.php
packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php

Update Post method to Put

---

packages/Webkul/Checkout/src/Cart.php

:bug: fix guest customers address save.

:bug: fix guest customers address save.

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php

Fixed duplicate key in Arabic lang.

Fixed duplicate key in Arabic lang

---

packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Core/src/Config/concord.php

fixed service provider issue
fixed lang issue

fixed service provider issue

---

packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php

remove required field from password

remove required field from password

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/bn/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/catalog/products/edit/price/group.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
packages/Webkul/Admin/src/Resources/views/tax/rates/edit.blade.php

Fixed #8179

---

packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php

Fixed issue #8178

---

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php

https://github.com/bagisto/bagisto/issues/8157

:wrench: Fixed switcher issue

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/bn/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php

https://github.com/bagisto/bagisto/issues/8188

Fixed Duplicate Lang issue on invoice

---

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php

Issue #8158 fixed.

---

packages/Webkul/Product/src/Repositories/ProductCustomerGroupPriceRepository.php

Issue #8180 fixed.

---

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php

Issue #8152 fixed.

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/bn/app.php
packages/Webkul/Admin/src/Resources/lang/de/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/fr/app.php
packages/Webkul/Admin/src/Resources/lang/he/app.php
packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
packages/Webkul/Admin/src/Resources/lang/it/app.php
packages/Webkul/Admin/src/Resources/lang/ja/app.php
packages/Webkul/Admin/src/Resources/lang/nl/app.php
packages/Webkul/Admin/src/Resources/lang/pl/app.php
packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
packages/Webkul/Admin/src/Resources/lang/ru/app.php
packages/Webkul/Admin/src/Resources/lang/sin/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/lang/uk/app.php
packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php

Issue #8195 fixed.

---

packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php

Code refinement.

---

packages/Webkul/Admin/src/Resources/assets/js/directives/slugify.js
packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php

https://github.com/bagisto/bagisto/issues/8183

:bug: Fix category Slug Issue

---

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php

Issue #8168 fixed.

---

packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php

https://github.com/bagisto/bagisto/issues/8172

Fixed Export Datagrid Issue

---

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php

Issue #8166 fixed.
