packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
Tiny mce create and update required issue fixed.
=> Tiny mce create and update required issue fixed.

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php
Fixed issue #8224 
Fixed state old value issue
=> fixed issue #8224

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php, packages/Webkul/Admin/src/Resources/views/customers/customers/edit.blade.php
fixed flash message in customer edit.
=> :bug: feat: fixed flash message in customer edit.

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Fixed Issue #8226

packages/Webkul/Admin/src/Services/DashboardService.php
:bug: feat: Issue #8235 fixed.
=> :bug: feat: Issue #8235 fixed.

packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
=> :bug: Issue #8221 fixed.

packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php, packages/Webkul/Admin/src/Http/Controllers/User/SessionController.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
=> fixed issue #8244

packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
=> fixed issue #8247

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php, packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php, packages/Webkul/Sales/src/Repositories/OrderRepository.php, packages/Webkul/Shop/src/Database/Migrations/2023_07_10_184256_create_theme_customizations_table.php
=> :bug: Issue#8156

packages/Webkul/Shop/src/Http/Middleware/AuthenticateCustomer.php
=> FIxed Issue #8249

packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
=> Fixed Issue #8245

packages/Webkul/Admin/src/DataGrids/Marketing/Communications/EmailTemplateDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Marketing/Communications/TemplateController.php
=> Fixed Issue #8257

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
=> fixed issue #8253

packages/Webkul/Admin/src/Resources/views/customers/customers/edit.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
=> fixed issue #8251

packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
Fixed category display mode issue.
=> Fixed category display mode issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Issue fixed #8267

packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
=> Issue #8221 fixed.

packages/Webkul/Admin/src/DataGrids/Marketing/Promotions/CartRuleCouponDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Marketing/Promotions/CartRuleCouponController.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php, packages/Webkul/Admin/src/Routes/marketing-routes.php
=> Fixed Issue  #8254

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
=> Issue Fixed #8235

packages/Webkul/Core/src/Models/ChannelTranslation.php, packages/Webkul/Shop/src/Resources/views/home/index.blade.php
=> Issue #8282 fixed

packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php, packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> Issue #8279 fixed

packages/Webkul/Shop/src/Resources/views/products/view/types/downloadable.blade.php
Fixed issue #8270 on product view page.
=> Fixed issue #8270

packages/Webkul/Category/src/Repositories/CategoryRepository.php, packages/Webkul/Shop/src/Http/Resources/CategoryResource.php, packages/Webkul/Shop/src/Resources/views/components/categories/carousel.blade.php
=> Category images issue and visible into category slider.

packages/Webkul/Product/src/Helpers/Indexers/Flat.php
=> Issue #8288 fixed

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
=> fixed Issue #8295 , #8162 

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
=> Issue #8268 fixed

app/Http/Middleware/EncryptCookies.php, composer.json, composer.lock, packages/Webkul/Admin/src/Providers/AdminServiceProvider.php, packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php, packages/Webkul/Payment/src/Providers/PaymentServiceProvider.php
=> Now supports octane #3846

packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> Fixed issue #8313

packages/Webkul/Shop/src/Database/Migrations/2023_07_10_184256_create_theme_customizations_table.php
=> Issue #8307 fixed

packages/Webkul/Shop/src/Routes/store-front-routes.php
Added full page support to search, compare pages
=> Added full page support to search, compare pages

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/Admin/src/Routes/settings-routes.php
Add Confirm Password Feature in user delete from admin
=> :star: Add Confirm Password Feature in user delete from admin

packages/Webkul/Shop/src/Http/Controllers/Customer/CustomerController.php, packages/Webkul/Shop/src/Resources/lang/ar/app.php, packages/Webkul/Shop/src/Resources/lang/bn/app.php, packages/Webkul/Shop/src/Resources/lang/de/app.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php, packages/Webkul/Shop/src/Resources/lang/fa/app.php, packages/Webkul/Shop/src/Resources/lang/fr/app.php, packages/Webkul/Shop/src/Resources/lang/he/app.php, packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php, packages/Webkul/Shop/src/Resources/lang/it/app.php, packages/Webkul/Shop/src/Resources/lang/ja/app.php, packages/Webkul/Shop/src/Resources/lang/nl/app.php, packages/Webkul/Shop/src/Resources/lang/pl/app.php, packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php, packages/Webkul/Shop/src/Resources/lang/ru/app.php, packages/Webkul/Shop/src/Resources/lang/sin/app.php, packages/Webkul/Shop/src/Resources/lang/tr/app.php, packages/Webkul/Shop/src/Resources/lang/uk/app.php, packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
=> Fixed issue #8342

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
=> Fixed issue #8323

packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> Fixed issue #8314

packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
Fixed issue #8343
Added date-of-birth field
=> fixed issue #8343

packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php
=> Fixed issue #8340

packages/Webkul/Shop/src/Resources/views/components/flat-picker/date.blade.php, packages/Webkul/Shop/src/Resources/views/components/flat-picker/datetime.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
=> fixed issue for RTL language

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
=> Fixed Issue #8360

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
=> Fixed Issue #8358

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
=> Issue #8357 fixed

packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/Account/WishlistController.php, packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php, packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php, packages/Webkul/Shop/src/Resources/views/products/view.blade.php
=> Fixed Issue #8351

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
=> Fixed issue #8353

packages/Webkul/Product/src/Repositories/ProductMediaRepository.php, packages/Webkul/Shop/src/Http/Resources/CategoryResource.php, packages/Webkul/Shop/src/Resources/views/components/categories/carousel.blade.php
=> Implemented webp conversion

packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php, packages/Webkul/Category/src/Repositories/CategoryRepository.php, packages/Webkul/Shop/src/Repositories/ThemeCustomizationRepository.php
Implemented theme and category images webp conversion
=> Implemented theme and category images webp conversion

packages/Webkul/Admin/src/Config/system.php
=> Remove Switcher validation from configuration

packages/Webkul/FPC/src/Listeners/Category.php
=> fixed issue #8378

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
=> Fixed datagrid issue

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php
=> fixed coupon issue #8254

packages/Webkul/Shop/src/Resources/views/components/categories/carousel.blade.php
Lazy loaded category carousal images
=> Lazy loaded category carousal images

packages/Webkul/Admin/src/Http/Controllers/Settings/ChannelController.php, packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
=> Issue #8312 fixed

packages/Webkul/Admin/src/Resources/views/tax/categories/index.blade.php
=> Fixed issue #8391

packages/Webkul/Admin/src/Resources/assets/js/directives/slugify-target.js
=> Issue #8228 fixed.

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
Fixed theme customizer theme issue
=> Fixed theme customizer theme issue

packages/Webkul/Shop/src/Http/Controllers/Customer/CustomerController.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
=> fixed issue #8341

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
=> fixed issue #8401

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> Fixed issue #8442

packages/Webkul/Shop/src/Resources/views/components/categories/carousel.blade.php
fixed issue #8403 in category carousel.
=> fixed issue #8403

packages/Webkul/Admin/src/Mail/Order/InventorySourceNotification.php
=> fixed issue #8408

config/.gitignore, config/translatable.php, packages/Webkul/Shop/src/Models/ThemeCustomization.php
=> Enable translatable fallback

packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php
=> fixed issue #8430

packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
=> fixed issue #8431

packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php, packages/Webkul/Admin/src/Resources/views/components/media/videos.blade.php, packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
=> Issue #8426 fixed

packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
=> fixed issue #8429

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> fixed issue #8452

packages/Webkul/Shop/src/Resources/views/products/view.blade.php
=> Issue #8328 fixed.

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Fixed Issue #8457

packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php
=> Fixed Issue #8456

packages/Webkul/Attribute/src/Database/Migrations/2023_09_20_102635_add_inventories_group_in_attribute_groups_table.php
Fixed minor issue in stock management migration
=> Fixed minor issue in stock management migration

packages/Webkul/Attribute/src/Database/Migrations/2023_07_20_185324_add_column_column_in_attribute_groups_table.php, packages/Webkul/Attribute/src/Database/Migrations/2023_09_20_102635_add_inventories_group_in_attribute_groups_table.php, packages/Webkul/Sales/src/Repositories/InvoiceItemRepository.php, packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
=> Refactor code

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
=> Fixed Issue #8450

packages/Webkul/Core/src/Repositories/LocaleRepository.php
=> Fixed Issue #8330

packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php
=> update password show and hide

packages/Webkul/Product/src/Type/AbstractType.php, packages/Webkul/Product/src/Type/Bundle.php, packages/Webkul/Product/src/Type/Configurable.php
=> Optimized product tax queries

packages/Webkul/Admin/src/Http/Controllers/Marketing/Promotions/CatalogRuleController.php, packages/Webkul/Admin/src/Services/DashboardService.php, packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php, packages/Webkul/CatalogRule/src/Jobs/UpdateCreateCatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Jobs/UpdateCreateProductIndex.php, packages/Webkul/CatalogRule/src/Listeners/CatalogRule.php, packages/Webkul/CatalogRule/src/Listeners/Product.php, packages/Webkul/CatalogRule/src/Providers/CatalogRuleServiceProvider.php, packages/Webkul/CatalogRule/src/Providers/EventServiceProvider.php, packages/Webkul/CatalogRule/src/Repositories/CatalogRuleProductPriceRepository.php, packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
=> Optimized catalog rule

packages/Webkul/Admin/src/Resources/views/components/products/search.blade.php
Fixed product search component search issue
=> Fixed product search component search issue

packages/Webkul/Product/src/Type/Bundle.php, packages/Webkul/Product/src/Type/Configurable.php, packages/Webkul/Product/src/Type/Grouped.php
Excluded Manage Stock group from composite products
=> Excluded Manage Stock group from composite products

packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php
=> Fixed Issue #8495

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Bundle product selected option issue fixed
=> Bundle product selected option issue fixed

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Fixed Issue  #8464

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> Refactor tailwind class

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
=> Added Improvement #8510

packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php, packages/Webkul/Product/src/Repositories/ProductRepository.php
Fixed product mega search issue
=> Fixed product mega search issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Fixed Issue #8527 and remove position Field from attribute options
=> Fixed Issue #8527 and remove position Field from attribute options

packages/Webkul/Admin/src/Http/Resources/AttributeResource.php, packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
Product create form issue fixed
=> Product create form issue fixed

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
=> Fixed Image count issue

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
=> Revert Search button changes on shop package

packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php, packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
=> Fixed Issue #8480

packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php, packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php, packages/Webkul/Shop/src/Resources/lang/ar/app.php, packages/Webkul/Shop/src/Resources/lang/bn/app.php, packages/Webkul/Shop/src/Resources/lang/de/app.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php, packages/Webkul/Shop/src/Resources/lang/fa/app.php, packages/Webkul/Shop/src/Resources/lang/fr/app.php, packages/Webkul/Shop/src/Resources/lang/he/app.php, packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php, packages/Webkul/Shop/src/Resources/lang/it/app.php, packages/Webkul/Shop/src/Resources/lang/ja/app.php, packages/Webkul/Shop/src/Resources/lang/nl/app.php, packages/Webkul/Shop/src/Resources/lang/pl/app.php, packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php, packages/Webkul/Shop/src/Resources/lang/ru/app.php, packages/Webkul/Shop/src/Resources/lang/sin/app.php, packages/Webkul/Shop/src/Resources/lang/tr/app.php, packages/Webkul/Shop/src/Resources/lang/uk/app.php, packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php, packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
=> Fixing Issue #8274

config/.gitignore, config/repository.php, packages/Webkul/CartRule/src/Helpers/CartRule.php, packages/Webkul/Core/src/Config/repository.php, packages/Webkul/Core/src/Providers/CoreServiceProvider.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
=> Optimized cart rule

packages/Webkul/Core/src/Config/concord.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
=> fixed issue_8546

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
=> Fixed Issue #8528

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
=> Fixing Issue #8511

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
=> Fixed dark mode icon issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Fixed #8520 - Configurable product option issue fix while edit attribute

packages/Webkul/Attribute/src/Models/Attribute.php
=> Issue #8497 fixed.

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
=> Issue #8509 fixed.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
=> fixed issue #8254

packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
=> fixed issue #8570

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Issue #8444 fixed.

packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
=> Fixed Issue #8585

packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProduct.php
=> Fixed Issue #8584

packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php
=> Issue #8595 fixed

config/repository.php, packages/Webkul/Core/src/Config/repository.php
Increased repository cache time
=> Increased repository cache time

packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> Fixed Issue #8516

public/installer/AdminConfig.php, public/installer/CSS/style.css, public/installer/Classes/Requirement.php, public/installer/Cleanup.php, public/installer/Composer.php, public/installer/EmailConfig.php, public/installer/EnvConfig.php, public/installer/MigrationRun.php, public/installer/Seeder.php, public/installer/Views/admin.blade.php, public/installer/Views/email.blade.php, public/installer/Views/environment.blade.php, public/installer/Views/migration.blade.php, public/installer/Views/requirements.blade.php, public/installer/Views/welcome.blade.php, public/installer/index.php, public/installer/install.php, public/installer/js/script.js
=> Refactor installer

public/installer/AdminConfig.php, public/installer/EnvConfig.php, public/installer/install.php
=> Fixed installer issue

packages/Webkul/CatalogRule/src/Jobs/UpdateCreateCatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Jobs/UpdateCreateProductIndex.php, packages/Webkul/Product/src/Jobs/ElasticSearch/DeleteIndex.php, packages/Webkul/Product/src/Jobs/ElasticSearch/UpdateCreateIndex.php, packages/Webkul/Product/src/Jobs/UpdateCreateInventoryIndex.php, packages/Webkul/Product/src/Jobs/UpdateCreatePriceIndex.php
Remove redis as hardcoded driver from jobs
=> Remove redis as hardcoded driver from jobs

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
Removed duplicate classes from dashboard blade
=> Removed duplicate classes from dashboard blade

packages/Webkul/Core/src/Jobs/UpdateCreateVisitIndex.php, packages/Webkul/Core/src/Jobs/UpdateCreateVisitableIndex.php, packages/Webkul/Core/src/Listeners/ResponseCacheHit.php, packages/Webkul/Core/src/Providers/CoreServiceProvider.php, packages/Webkul/Core/src/Providers/EventServiceProvider.php, packages/Webkul/Core/src/Visitor.php, packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
Visitor logs is now compatible with FPC and now works in background
=> Visitor logs is now compatible with FPC and now works in background

packages/Webkul/Core/src/Visitor.php
Removed query string from visitor url
=> Removed query string from visitor url

packages/Webkul/Admin/src/Resources/views/components/datagrid/filters.blade.php
fixed filter issue and also fixed for dark mode.
=> fixed filter issue and also fixed for dark mode

packages/Webkul/Admin/src/Services/DashboardService.php, packages/Webkul/Core/src/Jobs/UpdateCreateVisitIndex.php
Visit will be maintained for each day for every user
=> Visit will be maintained for each day for every user

packages/Webkul/Product/src/Type/Downloadable.php
=> Fixed translation issue #8631

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
=> fixed issue #8630

packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
=> Fixed Translation issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/thead/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/thead/tr.blade.php
=> fixed issue #8643

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php
=> fixed issue #8666

packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
=> fixed issue #8652

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> Fixed Space Issue in option

packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
#8635 
Wrap the overflow attributes tags
Go to 'Admin panel'
Click on 'Create product' inside the Catalog/products
Select Configurable product and fill in all the required field
=> Fixed #8635

packages/Webkul/Core/src/Core.php, packages/Webkul/Product/src/Type/AbstractType.php
=> fixed issue #8659

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
fixed id not visible and redirection issue in customer view
=> fixed id not visible and redirection issue in customer view

packages/Webkul/Admin/src/Resources/views/components/flat-picker/date.blade.php, packages/Webkul/Admin/src/Resources/views/components/flat-picker/datetime.blade.php
#8660 
Set the display Property in parent div of calender icon
Go to 'Admin panel'
See the stats calendar icon OR
Click on 'edit/create product' inside the catalog/products
See customer group price date & time
=> Fixed #8660 (Calender Icon Compatible with Multiple Browsers)

packages/Webkul/Admin/src/Resources/views/configuration/dependent-field-type.blade.php
fixed issue #8675
fixed issue #8671
=> fixed issue #8675

packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
=> fixed issue #8648

packages/Webkul/Shop/src/Http/Controllers/API/AddressController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/Account/AddressController.php
=> fixed issue #8649

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
=> Fixed Issue #8705

packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
Fixed review button configuration issue
Fixed product edit page UI issue on image upload
=> fixed review button configuration issue

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php, packages/Webkul/Shop/src/Resources/views/categories/view.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/wishlist/index.blade.php
Removed unnecessary classes from wish list shimmer.
Fixed issue in dark theme in theme customise input fields.
Fixed Zigzag issue of empty placeholder in category page.
=> removed unnecessary classes

packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php
=> Issue Fixed #8703

packages/Webkul/Admin/src/Http/Controllers/Reporting/ProductController.php
=> Fixed reporting issue

packages/Webkul/Admin/src/Resources/views/reporting/customers/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/index.blade.php
Fixed reporting header shifting issue
=> Fixed reporting header shifting issue

packages/Webkul/Admin/src/Helpers/Reporting/Sale.php
=> feat: changes done

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/reporting/customers/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/customers/most-orders.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/customers/most-reviews.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/customers/most-sales.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/customers/top-customer-groups.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/empty.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/most-reviews.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/most-visits.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/top-selling-by-quantity.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/products/top-selling-by-revenue.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/abandoned-carts.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/purchase-funnel.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/shipping-collected.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/tax-collected.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/sales/top-payment-methods.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Added reporting empty state

packages/Webkul/Installer/src/Http/Controllers/InstallerController.php, packages/Webkul/Installer/src/Http/Helpers/DatabaseManager.php, packages/Webkul/Installer/src/Http/Helpers/EnvironmentManager.php, packages/Webkul/Installer/src/Http/Helpers/ServerRequirements.php, packages/Webkul/Installer/src/Http/Middleware/CanInstall.php, packages/Webkul/Installer/src/Resources/views/installer/index.blade.php, packages/Webkul/Installer/src/Routes/web.php
=> Fixed installer issues

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
=> Fixed admin currency issue

packages/Webkul/Core/src/Core.php
=> Price conver issue fixed

packages/Webkul/Core/src/Core.php
=> Fixex currency issue

packages/Webkul/Core/src/Core.php
=> Optimize products api

packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php
=> Fixed: Currency exchange rate update issue.

packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php, packages/Webkul/Installer/src/Console/Commands/Install.php, packages/Webkul/Installer/src/Events/ComposerEvents.php, packages/Webkul/Installer/src/Http/Controllers/InstallerController.php, packages/Webkul/Installer/src/Providers/InstallerServiceProvider.php, packages/Webkul/User/src/Http/Middleware/Bouncer.php
=> Fixed isntaller issue

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
[Fixed: #8745]
https://prnt.sc/wZYSVKnXj77d
=> [Fixed: #8745]

packages/Webkul/Shop/src/Resources/views/checkout/success.blade.php
=> fixed issue #8701

packages/Webkul/Admin/src/Helpers/Reporting.php, packages/Webkul/Admin/src/Helpers/Reporting/Sale.php
=> [Fixed: #8743]

packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/graph.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/products/sold-quantities.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/products/wishlist-products.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/average-order-value.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/shipping-collected.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/tax-collected.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/total-orders.blade.php
Reporting shimmer ui issue fixed
=> Reporting shimmer ui issue fixed

packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/view.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
Reporting view shimmer issue fixed
=> Reporting view shimmer issue fixed

packages/Webkul/Admin/src/Resources/views/components/datagrid/filters.blade.php, packages/Webkul/Shop/src/Resources/views/components/datagrid/filters.blade.php
=> fixed filter applied UI issue

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
Fixed tinymce dark mode issue.
=> Fixed tinymce dark mode issue

packages/Webkul/Admin/src/Config/system.php
#8756 
fixed incorrect translations
- Go to **Configure**
- Click on **Payment Methods**
- Scroll down to **Money transfer**
=> fixed #8756

packages/Webkul/Admin/src/Resources/assets/images/empty-placeholders/report-empty.svg, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/reporting/empty.blade.php, public/themes/admin/default/build/assets/report-empty-c3bb4a01.svg, public/themes/admin/default/build/manifest.json
[Reporting empty placeholder updated](https://github.com/bagisto/bagisto/commit/f48b2c7b79d53bf31e3a17f562c6e45aee42cc8c)
=> Reporting empty placeholder updated

packages/Webkul/Shop/src/Resources/views/components/datagrid/toolbar.blade.php
change the button text colour if filter applied in shop package.
=> change the button text colour if filter applied in shop package

packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/purchase-funnel.blade.php
=> Fixed Issue #8776

packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php, packages/Webkul/SocialLogin/src/Providers/EventServiceProvider.php
=> Fixed Issue #8779

packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php, packages/Webkul/Installer/src/Console/Commands/Install.php
[Fixed installer](https://github.com/bagisto/bagisto/commit/9fc88a6da6f68cdce63cf33e8d999ce4919a1a75)
=> Fixed installer

config/concord.php, packages/Webkul/Core/src/Config/concord.php, packages/Webkul/Notification/src/Providers/ModuleServiceProvider.php, packages/Webkul/Notification/src/Providers/NotificationServiceProvider.php
Notification migration publish issue fixed
=> Notification migration publish issue fixed

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
=> Preload logo

packages/Webkul/Admin/src/Resources/views/dashboard/over-all-details.blade.php
Fixed non formatted price on dashboard
=> Fixed non formatted price on dashboard

packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Customer group price issue fixed
=> Customer group price issue fixed

packages/Webkul/Product/src/Helpers/ConfigurableOption.php
[Fixed: Attribute's option sort issue for the configurable product.]
https://prnt.sc/VnBWbTtu21h1
=> [Fixed: Attribute's option sort issue for the configurable product.]

app/Providers/AppServiceProvider.php
=> Remove https force

packages/Webkul/Shop/src/Resources/views/categories/view.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/summary.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/coupon.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/summary.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/features.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php
Fixed contrast radio issue for ADA
=> Fixed contrast radio issue for ADA

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
=> fixed issue #8832

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
=> fixed category issue #8824

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
=> Fixed Issue #8835

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
=> Fixed Issue #8822

packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php, packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
=> Fixed issue #8821

packages/Webkul/Installer/src/Resources/lang/ar/app.php, packages/Webkul/Installer/src/Resources/lang/bn/app.php, packages/Webkul/Installer/src/Resources/lang/de/app.php, packages/Webkul/Installer/src/Resources/lang/en/app.php, packages/Webkul/Installer/src/Resources/lang/es/app.php, packages/Webkul/Installer/src/Resources/lang/fa/app.php, packages/Webkul/Installer/src/Resources/lang/fr/app.php, packages/Webkul/Installer/src/Resources/lang/he/app.php, packages/Webkul/Installer/src/Resources/lang/hi_IN/app.php, packages/Webkul/Installer/src/Resources/lang/it/app.php, packages/Webkul/Installer/src/Resources/lang/ja/app.php, packages/Webkul/Installer/src/Resources/lang/nl/app.php, packages/Webkul/Installer/src/Resources/lang/pl/app.php, packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php, packages/Webkul/Installer/src/Resources/lang/ru/app.php, packages/Webkul/Installer/src/Resources/lang/sin/app.php, packages/Webkul/Installer/src/Resources/lang/tr/app.php, packages/Webkul/Installer/src/Resources/lang/uk/app.php, packages/Webkul/Installer/src/Resources/lang/zh_CN/app.php, packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/services.blade.php
=> Translatoins issues fixed

packages/Webkul/Installer/src/Console/Commands/Installer.php
Optimising command line Installer
=> Optimising command line Installer

packages/Webkul/Admin/src/Resources/views/emails/admin/forget-password.blade.php
[Fixed: forgot password greeting message param.]
=> [Fixed: forgot password greeting message param.]

packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
[Updated: view_render_event changes for the admin blades.]
=> [Updated: view_render_event changes for the admin blades.]

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
Fixed category page status issue
=> fixed category page status issue

packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php
Strips tags from elastic indices
=> Strips tags from elastic indices

packages/Webkul/Shop/src/Mail/Customer/UpdatePasswordNotification.php, packages/Webkul/Shop/src/Resources/views/emails/customers/update-password.blade.php
=> Password Update Mail

packages/Webkul/Shop/src/Mail/Customer/EmailVerificationNotification.php, packages/Webkul/Shop/src/Mail/Customer/RegistrationNotification.php, packages/Webkul/Shop/src/Resources/views/emails/customers/email-verification.blade.php, packages/Webkul/Shop/src/Resources/views/emails/customers/registration.blade.php
=> Fixed Issue  #8874

packages/Webkul/Admin/src/Resources/views/components/drawer/index.blade.php
=> fixed issue #8866

packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
=> Fixed Issue #8889

packages/Webkul/Installer/src/Console/Commands/Installer.php
Added installation event to installer
=> Added installation event to installer

packages/Webkul/Admin/src/Helpers/Reporting/Cart.php, packages/Webkul/Admin/src/Helpers/Reporting/Customer.php, packages/Webkul/Admin/src/Helpers/Reporting/Product.php, packages/Webkul/Admin/src/Helpers/Reporting/Sale.php, packages/Webkul/Admin/src/Helpers/Reporting/Visitor.php, packages/Webkul/Core/src/Eloquent/Repository.php
=> Issue #8892 fixed

packages/Webkul/Admin/src/Helpers/Dashboard.php, packages/Webkul/Admin/src/Helpers/Reporting.php, packages/Webkul/Admin/src/Helpers/Reporting/Product.php, packages/Webkul/Admin/src/Helpers/Reporting/Sale.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/dashboard/top-selling-products.blade.php
=> Issue #8885 fixed

packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
=> Issue #8883 fixed

packages/Webkul/Admin/src/Helpers/Reporting/Product.php
Top Selling Products By Quantity issue fixed
=> Top Selling Products By Quantity issue fixed

packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
=> Issue #8888 fixed

packages/Webkul/Sales/src/Repositories/OrderItemRepository.php, packages/Webkul/Shop/src/Http/Resources/ProductResource.php, packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
=> Issue #8908 fixed

packages/Webkul/Checkout/src/Cart.php
=> Issue #8870 fixed

packages/Webkul/Admin/src/Helpers/Reporting.php, packages/Webkul/Sales/src/Repositories/OrderItemRepository.php
=> fixed issue #8867

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php, packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
Fixed language switcher issue.
=> Fixed language switcher issue

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
fixed language switcher for category and cms page
=> fixed language switcher for category and cms page

packages/Webkul/Admin/src/Helpers/Reporting/Customer.php, packages/Webkul/Installer/src/Database/Seeders/Core/LocalesTableSeeder.php
Fixed locale image issue and reporting db prefix issue
=> Fixed locale image issue and reporting db prefix issue

packages/Webkul/Installer/src/Console/Commands/Installer.php
Updated command installer information messages
=> Updated command installer information messages

packages/Webkul/Installer/src/Console/Commands/Installer.php
Fixed command line installer locale/currency issue
=> Fixed command line installer locale/currency issue

packages/Webkul/Attribute/src/Repositories/AttributeFamilyRepository.php, packages/Webkul/Shop/src/Http/Resources/CompareItemResource.php, packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
Compare page is now showing select attribute option label instean of id
=> Compare page is now showing select attribute option label instean of id

packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
=> fixed issue #8940

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php, packages/Webkul/Product/src/Repositories/ProductRepository.php, packages/Webkul/Shop/src/Http/Controllers/API/ProductController.php, packages/Webkul/Shop/src/Resources/views/search/index.blade.php
Search duplicate query params removed
=> Search duplicate query params removed

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/DataGrids/CMS/CMSPageDataGrid.php, packages/Webkul/Admin/src/DataGrids/Catalog/AttributeDataGrid.php, packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php, packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php, packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php, packages/Webkul/Admin/src/DataGrids/Customers/ReviewDataGrid.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php, packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
remove mass-actions from acl.php file
=> remove mass-actions from acl.php file

packages/Webkul/Shop/src/Http/Resources/CartItemResource.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
=> fixed issue #8955

packages/Webkul/Admin/src/Helpers/Reporting/Product.php
=> Fixed product reporting issue

packages/Webkul/Admin/src/Resources/assets/css/app.css, packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
=> Fixed issue #8971

packages/Webkul/Paypal/src/Http/Controllers/StandardController.php, packages/Webkul/Shop/src/Resources/lang/ar/app.php, packages/Webkul/Shop/src/Resources/lang/bn/app.php, packages/Webkul/Shop/src/Resources/lang/de/app.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php, packages/Webkul/Shop/src/Resources/lang/fa/app.php, packages/Webkul/Shop/src/Resources/lang/fr/app.php, packages/Webkul/Shop/src/Resources/lang/he/app.php, packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php, packages/Webkul/Shop/src/Resources/lang/it/app.php, packages/Webkul/Shop/src/Resources/lang/nl/app.php, packages/Webkul/Shop/src/Resources/lang/pl/app.php, packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php, packages/Webkul/Shop/src/Resources/lang/ru/app.php, packages/Webkul/Shop/src/Resources/lang/sin/app.php, packages/Webkul/Shop/src/Resources/lang/tr/app.php, packages/Webkul/Shop/src/Resources/lang/uk/app.php, packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
=> Issue #8982 fixed.

packages/Webkul/Admin/src/Helpers/Reporting/Sale.php
=> Issue #8981 fixed.

packages/Webkul/Admin/src/Http/Controllers/Settings/ExchangeRateController.php
=> Issue #8942 fixed.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
=> Issue #8986 fixed.

packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
Period dropdown is now available for only graph type reporting
=> Period dropdown is now available for only graph type reporting

packages/Webkul/Admin/src/Resources/views/dashboard/top-selling-products.blade.php
Fixed 404 redirect issue in dashboard top selling products
=> Fixed 404 redirect issue in dashboard top selling products

packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
=> Issue #8931 fixed.

packages/Webkul/Shop/src/Http/Resources/ProductReviewResource.php, packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
=> Issue #8852 fixed.

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php, packages/Webkul/Admin/src/Mail/Order/InvoicedNotification.php, packages/Webkul/Shop/src/Mail/Order/InvoicedNotification.php
=> Issue #8927 fixed.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
Fixed issue #8970
Fixed issue #8969
=> fixed issue #8970

packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
=> fixed issue #9008

packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
=> fixed issue #9007

packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
=> Issue #8689 fixed.

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php, packages/Webkul/Shop/src/Resources/views/cms/page.blade.php
=> CMS page issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Fix Attribute colour swatch Issue
=> Fix Attribute colour swatch Issue

packages/Webkul/Admin/src/Config/system.php
=> fixed issue #9021

packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/seo/index.blade.php, packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
=> Fixed issue #9020

packages/Webkul/Admin/src/Config/menu.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
fixed theme customisation issue in multiple locale.
=> fixed theme customisation issue in multiple locale

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> fixed issue #9030

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> Fixed issue #9031

packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php, packages/Webkul/Shop/src/Resources/views/home/index.blade.php
Removed unused comment and code refinement.
=> Removed unused comment.

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php
Added back button in configuration to redirect in index page.
=> Added back button in configuration to redirect in index page.

packages/Webkul/Core/src/Http/Middleware/CheckForMaintenanceMode.php, packages/Webkul/Installer/src/Http/Controllers/InstallerController.php, packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
- Arrange the key of allowed locales and currencies in Installer
=> Arrange the key of allowed locales and currencies in Installer

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
=> Issue #8921 fixed.

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php, packages/Webkul/Admin/src/Routes/customers-routes.php, packages/Webkul/Shop/src/Http/Resources/ProductReviewResource.php
Added Pagination on customer orders Page
=> Added Pagination on customer orders Page

packages/Webkul/Admin/src/Providers/AdminServiceProvider.php, packages/Webkul/Core/src/Tree.php
=> Issue #9005 fixed.

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
=> Fixed tinymce darkmode issue

packages/Webkul/Theme/src/Models/ThemeCustomization.php
=> Fixed theme creation issue.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
=> Issue #9064 fixed.

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
Tinymce issue image upload image fixed.
=> Tinymce issue image upload image fixed.

packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php
Code Refinement and optimization
=> Code Refinement and optimization

packages/Webkul/Admin/src/DataGrids/Sales/OrderTransactionsDataGrid.php, packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/sitemaps/index.blade.php, packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/categories/index.blade.php
Remove Additional Overridden Data Grid Code and some Refactors
=> Remove Additional Overridden Data Grid Code and some Refactors

packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
=> added missing events

packages/Webkul/Shop/src/Http/Controllers/Customer/Account/DownloadableProductController.php
Downloadable issue fix in shop and some lang issue fixed.
=> Downloadable issue fix in shop

composer.json, composer.lock
=> Revert "Add league fractal dependency. #8991"

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/edit.blade.php
=> Fixed Issue #9076

packages/Webkul/Admin/src/Resources/views/components/form/control-group/label.blade.php, packages/Webkul/Admin/src/Resources/views/configuration/dependent-field-type.blade.php
=> Fixed form label alignment

packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/categories/carousel.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/products/carousel.blade.php, packages/Webkul/Shop/src/Resources/views/products/prices/index.blade.php
=> Fixed accessibility issue]

packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
=> Issue #8687 fixed.

packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php, packages/Webkul/Shop/src/Resources/views/products/prices/bundle.blade.php
Fixed url rewrite and accessibility issue
=> Fixed url rewrite and accessibility issue

packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
=> remove duplicate event

packages/Webkul/Admin/src/Resources/views/components/shimmer/datagrid/table/body.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/datagrid/table/head.blade.php, packages/Webkul/Shop/src/Resources/assets/js/app.js, packages/Webkul/Shop/src/Resources/views/components/datagrid/table.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/services.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/datagrid/table/body.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/datagrid/table/head.blade.php
Fixed datagrid shimmer issues and refactor code
=> Fixed datagrid shimmer issues and refactor code

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Fixed image slider autoplay issue
=> Fixed image slider autoplay issue

packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
Fixing Customer page pagination issue
=> Fixing Customer page pagination issue

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
Show image icon for upload images to tinymce.
=> Show image icon for upload images to tinymce.

packages/Webkul/Shop/src/Resources/views/categories/view.blade.php, packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Fixed body scroll issue on category page after applying filter
=> Fixed body scroll issue on category page after applying filter

packages/Webkul/Shop/src/Resources/views/categories/filters.blade.php
Fixed category page toobar mode issue
=> Fixed category page toobar mode issue

packages/Webkul/Shop/src/Resources/views/products/prices/bundle.blade.php, packages/Webkul/Shop/src/Resources/views/products/prices/index.blade.php
=> Fix Typo of Aria label

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
Fixed product gallery selected image click issue
=> Fixed product gallery selected image click issue

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/controls.blade.php
fixed file upload input field for dark theme in product page
=> fixed file upload input field for dark theme in product page

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
=> Fixed issue #9096

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php, packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
=> Issue #9093 fixed.

packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
=> Fixed checkout ui issue

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php
Now form control can be used without form
=> Now form control can be used without form

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
=> remove unnecessary word

packages/Webkul/Admin/src/Resources/views/sales/orders/images.blade.php
Fixed order datagrid items count issue
=> Fixed order datagrid items count issue

app/Console/Kernel.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Jobs/DeleteCatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Jobs/UpdateCreateCatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Listeners/CatalogRule.php, packages/Webkul/CatalogRule/src/Providers/EventServiceProvider.php, packages/Webkul/Product/src/Database/Migrations/2023_12_11_054614_add_channel_id_column_in_product_price_indices_table.php, packages/Webkul/Product/src/Helpers/Indexers/Price.php
Improved catalog rule indexing
=> Improved catalog rule indexing

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> enhance the ui issue.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
=> Remove duplicate classes

packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/label.blade.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/tabs/index.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
Fixed shop form spacing issues
=> Fixed shop form spacing issues

packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/summary.blade.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/label.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php, packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php, packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
Fixed checkout summary spacing issue
=> Shop ui issues

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
fixed product multiple image issue
=> fixed product multiple image issue

packages/Webkul/Shop/src/Resources/views/components/shimmer/products/view.blade.php, packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Fixed shop product page ui issues
=> Fixed shop product page ui issues

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php
=> Fixed broken icon issues

packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/products/reviews/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/shimmer/tabs/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/tabs/index.blade.php
optimised some classes of tabs and review
=> optimized some classes of tabs and review

routes/breadcrumbs.php
Added cart link on checkout page breadcrums
=> Added cart link on checkout page breadcrums

packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
Customer email is now sortable in order datagrid
=> Customer email is now sortable in order datagrid

packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/categories.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/customers.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/orders.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/products.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
Fixed border issue in dark theme in mega search shimmer.
Add address delete confirmation modal and fixed some minor issues.
Added confirmation modal for default address.
=> fixed border issue in dark theme in mega search shimmer

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
=> Issue #9181 fixed

packages/Webkul/Checkout/src/Cart.php, packages/Webkul/Checkout/src/Traits/CartTools.php
Fixed move to wishlist from cart issue
=> Fixed move to wishlist from cart issue

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/label.blade.php, packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
=> Fixed required field gap

packages/Webkul/Admin/src/Resources/views/dashboard/todays-details.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/images.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
=> fixed issue #9189

packages/Webkul/Admin/src/Resources/views/catalog/attributes/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/edit.blade.php, packages/Webkul/SocialShare/src/Resources/views/share.blade.php
used button classes remove unnecessary css
=> used button classes remove unnecessary css

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> Fixed search bar ui

packages/Webkul/Shop/src/Resources/views/products/view/types/downloadable.blade.php
Fixed downloadable product page ui issue
=> Fixed downloadable product page ui issue

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
=> Fixed issue #9194

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
Removed bold text from header notification dropdown
=> Removed bold text from header notification dropdown

packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
Removed extra bottom margin from apply coupon modal field
=> Removed extra bottom margin from apply coupon modal field

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php
Removed font/icon preload from head
=> Removed font/icon preload from head

packages/Webkul/Shop/src/Resources/views/components/datagrid/index.blade.php
Pass performAction in slot and add messages
=> Pass performAction in slot and add messages

packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/graph.blade.php, packages/Webkul/Shop/src/Resources/views/components/flash-group/item.blade.php, packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php, packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Added events in product view and card page
=> Added events in product view and card page

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
=> Issue #9207 fixed.

packages/Webkul/Admin/src/Resources/views/cms/create.blade.php, packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
pass variable in edit cms page events
=> pass variable in edit cms page events

packages/Webkul/Product/src/Models/Product.php
=> Issue #9227 fixed

packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/index.blade.php
=> Added tax-rate export feature

packages/Webkul/Marketing/src/Listeners/Product.php
fixed product mass update issue
=> fixed product mass update issue

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
fix configuration multiselect was not working properly.
=> fix configuration multiselect was not working properly.

packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/index.blade.php
=> fix checkout confirm issue.

config/products.php, packages/Webkul/Product/src/Type/AbstractType.php, packages/Webkul/Product/src/Type/Downloadable.php, packages/Webkul/Product/src/Type/Simple.php, packages/Webkul/Product/src/Type/Virtual.php
=> Refactorred products config

packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php
Fixed product carousel auto swipe to first if list is ended
=> Fixed product carousel auto swipe to first if list is ended

packages/Webkul/Core/src/Console/Commands/DownChannelCommand.php
Fixed maintenance enable issue
=> Fixed maintenance enable issue

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
=> fixed cart page ui

config/app.php
=> Remove unused statement.

packages/Webkul/Admin/src/Listeners/Invoice.php, packages/Webkul/Admin/src/Listeners/Shipment.php, packages/Webkul/Shop/src/Listeners/Invoice.php, packages/Webkul/Shop/src/Listeners/Refund.php, packages/Webkul/Shop/src/Listeners/Shipment.php
Email can be sended multiple times.
=> Email can be sended multiple times.

packages/Webkul/Admin/src/Helpers/Dashboard.php
Fixed dashboard billing_address issue
=> Fixed dashboard billing_address issue

packages/Webkul/Admin/src/DataGrids/Customers/GroupDataGrid.php, packages/Webkul/Admin/src/DataGrids/Customers/ReviewDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/Communications/EventDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/Communications/NewsLetterDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/SearchSEO/SearchSynonymDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/SearchSEO/SearchTermDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/SearchSEO/SitemapDataGrid.php, packages/Webkul/Admin/src/DataGrids/Marketing/SearchSEO/URLRewriteDataGrid.php, packages/Webkul/Admin/src/DataGrids/Settings/CurrencyDataGrid.php, packages/Webkul/Admin/src/DataGrids/Settings/ExchangeRatesDataGrid.php, packages/Webkul/Admin/src/DataGrids/Settings/LocalesDataGrid.php, packages/Webkul/Admin/src/DataGrids/Settings/TaxCategoryDataGrid.php, packages/Webkul/Admin/src/DataGrids/Settings/UserDataGrid.php, packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php, packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-synonyms/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-terms/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/sitemaps/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/url-rewrites/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/categories/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
Passed index value in all override data-grids
=> Passed index value in all override data-grids

packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
Theme datagrid filterable issue fix and show proper illustration for empty records
=> Theme datagrid filterable issue fix and show proper illustration for empty records

packages/Webkul/Shop/src/Http/Requests/Customer/ProfileRequest.php
=> fixed issue #9235

.github/workflows/pest_tests.yml, composer.json, composer.lock, packages/Webkul/Installer/src/Console/Commands/Installer.php
Added new laravel prompts in CLI
https://github.com/bagisto/bagisto/pull/9248
=> Added new laravel prompts in CLI

packages/Webkul/Admin/src/Routes/settings-routes.php
Moved theme routes into setting route group
=> Moved theme routes into setting route group

packages/Webkul/Admin/src/Resources/views/components/flat-picker/date.blade.php, packages/Webkul/Admin/src/Resources/views/components/flat-picker/datetime.blade.php, packages/Webkul/Shop/src/Resources/views/components/flat-picker/date.blade.php, packages/Webkul/Shop/src/Resources/views/components/flat-picker/datetime.blade.php
Date picker icon click issue fixed
=> Date picker icon click issue fixed

packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
fixed billing address issue in customers order details
=> fixed billing address issue in customers order details

packages/Webkul/Installer/src/Database/Seeders/Core/ChannelTableSeeder.php
[Fixed: installer channel's locales creation issue.]
=> [Fixed: installer channel's locales creation issue.]

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/controls.blade.php
Checkbox field label click is now working in product edit page
=> Checkbox field label click is now working in product edit page

packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Fixed configurable product options ui issue in RTL
=> Fixed configurable product options ui issue in RTL

packages/Webkul/Admin/src/Resources/views/users/forget-password/create.blade.php, packages/Webkul/Admin/src/Resources/views/users/reset-password/create.blade.php, packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php, packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php, packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php, packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
Default theme logo on some pages
Changing Admin and Shop logo in the admin panel does not affect on listed pages.
1. Admin Login
2. Admin Forget Password
3. Admin Reset Password
4. Customer Login
5. Customer Register
6. Customer Forget Password
7. Customer Reset Password
8. Shop Header Desktop
9. Shop Header Mobile
10. Shop Cart 
11. Shop Checkout
1. Go to Admin Panel > Settings > Channels > Select Default > Update Logo in **Design Section**
2. Go to Admin Panel > Configure > Design > Update Logo
=> logo consistency

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
Mega search and Datagrid are now searching same
=> Mega search and Datagrid are now searching same

packages/Webkul/Admin/tests/Feature/Catalog/AttributeFamilyTest.php, packages/Webkul/Admin/tests/Feature/Catalog/Products/Types/BundleTest.php, packages/Webkul/Admin/tests/Feature/Catalog/Products/Types/DownloadableTest.php, packages/Webkul/Admin/tests/Feature/Dashboard/DashboardTest.php, packages/Webkul/Admin/tests/Feature/Marketing/SearchAndSeo/UrlRewritesTest.php, packages/Webkul/Admin/tests/Feature/Reporting/CustomersReportTest.php, packages/Webkul/Admin/tests/Feature/Reporting/ProductReportTest.php, packages/Webkul/Admin/tests/Feature/Reporting/SalesReportTest.php, packages/Webkul/Admin/tests/Feature/Sales/InvoiceTest.php, packages/Webkul/Admin/tests/Feature/Sales/OrdersTest.php, packages/Webkul/Admin/tests/Feature/Sales/RefundTest.php, packages/Webkul/Admin/tests/Feature/Sales/ShipmentTest.php, packages/Webkul/Admin/tests/Feature/Sales/TransactionTest.php, packages/Webkul/Admin/tests/Feature/Settings/ChannelsTest.php, packages/Webkul/Checkout/src/Database/Factories/CartItemFactory.php
:bug: Fixed test cases failed when try to execute second time.
=> 🐛 Fixed test cases failed when try to execute second time.

packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/categories/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> fixed datagrid console error

packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php, packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php, packages/Webkul/Admin/src/Routes/sales-routes.php, packages/Webkul/Admin/tests/Feature/Sales/InvoiceTest.php, packages/Webkul/Shop/src/Http/Controllers/API/CartController.php, packages/Webkul/Shop/src/Providers/EventServiceProvider.php
Remove shop package dependency from admin invoice controller
=> Remove shop package dependency from admin invoice controller

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php, packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php, packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php, packages/Webkul/Admin/src/Routes/customers-routes.php
Fixed address create and edit  modal.
Change method  name case.
=> fixed address create and edit  modal

storage/framework/.gitignore
Added maintenance.php file in gitignore
=> Added maintenance.php file in gitignore

packages/Webkul/Admin/tests/Feature/Catalog/Products/Types/DownloadableTest.php, packages/Webkul/Customer/src/Database/Factories/CompareItemFactory.php, packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php, packages/Webkul/Customer/src/Models/CompareItem.php, packages/Webkul/Customer/src/Models/Wishlist.php, packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php, packages/Webkul/Shop/tests/Feature/Customers/AccountTest.php, packages/Webkul/Shop/tests/Feature/Customers/OrdersTest.php, packages/Webkul/Shop/tests/Feature/Customers/WishlistTest.php, packages/Webkul/Shop/tests/Feature/HomePageTest.php
=> Frontend test cases.

packages/Webkul/Shop/src/Http/Controllers/Customer/Account/AddressController.php
fixed customer default address issue
=> fixed customer default address issue

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php, packages/Webkul/Shop/src/Listeners/Customer.php, packages/Webkul/Shop/src/Providers/EventServiceProvider.php
Optimise customer note mail functionality
=> Optimise customer note mail functionality

config/themes.php, packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php, packages/Webkul/Shop/src/Http/Middleware/Theme.php, packages/Webkul/Theme/src/Themes.php
=> Update themes key name

packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php, packages/Webkul/CatalogRule/src/Repositories/CatalogRuleRepository.php, packages/Webkul/Core/src/Eloquent/Repository.php
=> Fixed issue #9335

packages/Webkul/Installer/src/Console/Commands/Installer.php
Removed the green background so that the text is readable
run php artisan bagisto:install
=> Removed green background from cli installer

packages/Webkul/Installer/src/Console/Commands/Installer.php
Fixed pint test case fail in installer
=> Fixed pint test case fail in installer

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php, packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Done improvement #9334

packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
extra period used by mistake, fixed.
=> extra period fixed

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
optimised checkbox component to override class
=> Refactor checkbox component to override class

packages/Webkul/Admin/src/Resources/views/dashboard/top-selling-products.blade.php
Fixed dashboard console error in top selling products
=> Fixed dashboard console error in top selling products

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Core/src/Traits/CoreConfigField.php
=> Fixed issue #9317

packages/Webkul/Admin/tests/Feature/Catalog/Products/Types/GroupedTest.php, packages/Webkul/Admin/tests/Feature/Settings/ChannelsTest.php, packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php, packages/Webkul/Shop/tests/Feature/Customers/AccountTest.php, packages/Webkul/Shop/tests/Feature/Customers/OrdersTest.php, packages/Webkul/Shop/tests/Feature/Customers/WishlistTest.php, packages/Webkul/Shop/tests/Feature/HomePageTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/BundleTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/ConfigurableTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/DownloadableTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/GroupedTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/SimpleTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/VirtualTest.php
Model wise assertions for shop package.
=> model wise assertions for shop package.

packages/Webkul/Shop/tests/Feature/Checkout/CartTest.php, packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
Write test cases for download and virtual products for shipping and payment methods.
Also wite test case for place order with multiple and different products types.
=> test: Write test case.

packages/Webkul/Admin/src/Config/system.php
=> Add validation.

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Attribute edit page configuration checkbox was not working properly.
=> Attribute edit page configuration checkbox was not working properly.

packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
=> fixed filename typo

packages/Webkul/Admin/src/Http/Controllers/Settings/ThemeController.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php, packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php, packages/Webkul/Theme/src/Repositories/ThemeCustomizationRepository.php
=> Fixed issue #9328

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> Issue #9343 fixed.

packages/Webkul/Shop/src/Resources/views/home/index.blade.php
home page: handle theme error.
=> home page: handle theme error.

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
=> Issue #9396 fixed

packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
Fixed Issue #9401
Validation added in currency modal for min and max 3 digits.
=> Fixed Issue #9401

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Fix console issue on home page in shop.
=> Fix console issue on home page in shop.

packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php
Theme issue fixed and now theme will be appear into datagrid however not update after create. #9369
=> Issue #9369 fixed.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
catalog issue when select condition fixed.
=> catalog issue when select condition fixed.

packages/Webkul/CatalogRule/src/Jobs/DeleteCatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Jobs/UpdateCreateCatalogRuleIndex.php
Added todo comment in catalog rule
=> Added todo comment in catalog rule

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
=> pagination issue.

packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php
=> Issue #8896 fixed.

packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php, packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/edit.blade.php, packages/Webkul/DataTransfer/src/Helpers/Import.php, packages/Webkul/DataTransfer/src/Helpers/Sources/AbstractSource.php, packages/Webkul/DataTransfer/src/Helpers/Sources/CSV.php, packages/Webkul/DataTransfer/src/Helpers/Sources/Excel.php
Added excel support for import
=> Added excel support for import

packages/Webkul/Customer/src/Models/Customer.php, packages/Webkul/User/src/Models/Admin.php
Added use HasApiTokens in admin and customer models
=> Added use HasApiTokens in admin and customer models

packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php, packages/Webkul/Admin/src/Routes/configuration-routes.php, packages/Webkul/Core/src/Repositories/CoreConfigRepository.php
=> Feature #8775 implemented

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Fix Console issue in Shop Home page.
=> Fix Console issue in Shop Home page.

packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
=> Theme slider add label issue.

packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php
theme datagrid results count issue fixed.
=> theme datagrid results count issue fixed.

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
fix issue on product data grid product type lang not rendered.
=> fix issue on product data grid product type lang not rendered.

packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
In mobile view there is show only default image after change from config.
=> In mobile view there is show only default image after change from config.

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php
Added missing language in Datagrid component
=> Added missing language in Datagrid component

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
left navigation disabled when there is no previos slider.
=> left navigation disabled when there is no previos slider.

packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
=> Refactor code style.

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/links.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
Added event in dashboard and fixed other events
=> Added event in dashboard and fixed other events

packages/Webkul/Shop/src/Resources/views/components/datagrid/table.blade.php
Fixed shop datagrid pagination override issue
=> Fixed shop datagrid pagination override issue

packages/Webkul/Admin/src/Resources/lang/it/app.php
=> Fixed lang in Italian(it)

packages/Webkul/Admin/src/Http/Controllers/Settings/LocaleController.php, packages/Webkul/DataGrid/src/DataGrid.php, packages/Webkul/Shop/src/Http/Resources/CompareItemResource.php
=> Fixed XSS vulnerability

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
=> Fixed image change issue

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
attribute options not working.
=> attribute options not working.

packages/Webkul/Product/src/Type/AbstractType.php
Fix error when copy the product.
=> Fix error when copy the product.

packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Fixed image issue in configurable product
=> Fixed image issue in configurable product

packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
Reset started_at and completed_at on import update
=> Reset started_at and completed_at on import update

packages/Webkul/Admin/src/Http/Controllers/Settings/ThemeController.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php, packages/Webkul/Theme/src/Repositories/ThemeCustomizationRepository.php
=> xss theme issue fixed.

packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php, packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Fixed theme customization status label color issue
=> Fixed theme customization status label color issue

packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
=> Mass deletion message issue.

packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php, packages/Webkul/Product/src/Repositories/ProductRepository.php
Optimized product db search mode and elastic indexing
=> Optimized product db search mode and elastic indexing

packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
Fixed import name typo in data import
=> Fixed import name typo in data import

packages/Webkul/FPC/src/Listeners/Order.php, packages/Webkul/FPC/src/Listeners/Refund.php
Fixed order cancel issue if the product is already deleted
=> Fixed order cancel issue if the product is already deleted

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
=> Fixed issue #9489

packages/Webkul/Admin/src/Resources/views/catalog/categories/index.blade.php
Added the following events
**bagisto.admin.catalog.categories.create.before
bagisto.admin.catalog.categories.create.after**
=> Added before and after event for create categories button

packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php, packages/Webkul/Customer/src/Repositories/CustomerRepository.php
Fixed customer delete error message on pending order
Refactor pending or processing order status check function.
=> Fixed customer delete error message on pending order

packages/Webkul/Admin/src/Resources/views/components/drawer/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/modal/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/modal/index.blade.php
Fixed Modal z-index issue on modal open.
Fixed modal and drawer component remove static text.
Added some events in profile drop down
=> Fixed some minor issues and added events

packages/Webkul/Admin/src/Config/system.php
=> Fixed issue #9514

packages/Webkul/Admin/src/DataGrids/Marketing/Communications/EventDataGrid.php, packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
Fixed order status filter converted it drop-down type and event date filter
=> Fixed order status filter and event date filter

packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
Datagrid issue fixed in hindi locale.
=> Datagrid issue fixed in hindi locale.

packages/Webkul/Shop/src/Resources/views/components/range-slider/index.blade.php
=> Issue #9500 fixed.

packages/Webkul/Shop/src/Resources/views/products/prices/bundle.blade.php
Fixed bundle product price ui issue
=> Fixed bundle product price ui issue

packages/Webkul/Product/src/Repositories/ProductRepository.php
Added elasticseach support to findBySlug function in ProductRepository
=> Added elasticseach support to findBySlug function in ProductRepository

packages/Webkul/Product/src/Repositories/ProductRepository.php
Fixed findBySlug issue in ProductRepository
=> Fixed findBySlug issue in ProductRepository

packages/Webkul/Admin/src/DataGrids/Sales/OrderTransactionsDataGrid.php
=> Fixed Issue #9544

packages/Webkul/Customer/src/Database/Factories/CustomerAddressFactory.php, packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php, packages/Webkul/Shop/tests/Feature/Product/Prices/SimpleTest.php
refactor: checkout address test cases refactored.
=> refactor: checkout address test cases refactored.

packages/Webkul/Admin/src/Http/Resources/TransactionResource.php, packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php, packages/Webkul/Admin/tests/Feature/Sales/TransactionTest.php, packages/Webkul/Shop/tests/Feature/Customers/AccountTest.php
=> Fixed transaction test case

packages/Webkul/Shop/src/Resources/views/components/datagrid/filters.blade.php, packages/Webkul/Shop/src/Resources/views/components/datagrid/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/datagrid/table.blade.php
Fixed shop data-grid Header issue
=> Fixed shop data-grid Header issue

app/Http/Kernel.php
=> Refactor Kernel

packages/Webkul/DataGrid/src/DataGrid.php
=> Fixed issue #9552

packages/Webkul/Admin/src/Http/Controllers/Customers/AddressController.php
Added email in address update method in admin package
=> Added email in address update method in admin package

packages/Webkul/Admin/src/Http/Controllers/Customers/AddressController.php, packages/Webkul/Shop/src/Http/Controllers/API/AddressController.php, packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php, packages/Webkul/Shop/tests/Feature/Customers/AccountTest.php
=> Validate email field

packages/Webkul/Shop/src/Resources/views/components/datagrid/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/datagrid/toolbar.blade.php
=> Fixed issue #9567

packages/Webkul/Checkout/src/Traits/CartTools.php, packages/Webkul/Shop/src/Http/Controllers/API/CartController.php, packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php, packages/Webkul/Shop/src/Http/Resources/WishlistResource.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
=> move to wishlist.

packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php, packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
Fixed empty phone number issue
=> Fixed empty phone number issue

packages/Webkul/SocialShare/src/Resources/views/links/email.blade.php, packages/Webkul/SocialShare/src/Resources/views/links/facebook.blade.php, packages/Webkul/SocialShare/src/Resources/views/links/linkedin.blade.php, packages/Webkul/SocialShare/src/Resources/views/links/pinterest.blade.php, packages/Webkul/SocialShare/src/Resources/views/links/twitter.blade.php
=> Fixed Issue #9610

packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
=> Fixed Issue #9612

packages/Webkul/Product/src/ProductImage.php
=> Fixed issue on null URL 

packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
=> Fixed issue #9646

packages/Webkul/Sales/src/Models/Order.php
#9645 
Fix null check in canReorder method of Order model
=> Fixed issue #9645

packages/Webkul/Admin/src/Http/Resources/ProductResource.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/items.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/compare-items.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/recent-order-items.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/wishlist-items.blade.php
Fixed order creation issue on inventory Zero
=> Fixed order creation issue on inventory Zero

packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php
=> Fix export button styling in datagrid export component on loading.

packages/Webkul/Checkout/src/Cart.php
Fix issue #9662  customer name assignment in setCustomerPersonnelDetails method
=> Fix issue #9662

packages/Webkul/Admin/src/Resources/views/components/quantity-changer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/quantity-changer/index.blade.php
#9680
Fixed for the Shop mini cart also.
=> Fixed Issue #9680

packages/Webkul/Shop/src/Resources/views/components/dropdown/index.blade.php
Dropdown component overlap issue fixed
=> Dropdown component overlap issue fixed

packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php
=> fixed Issue #9673

packages/Webkul/Shop/src/Resources/views/home/contact-us.blade.php
=> Fixed issue #9687

packages/Webkul/Admin/src/Resources/views/components/tree/view.blade.php
=> Implement feature #9685

CONTRIBUTING.md
=> Update Contribution Guide.

packages/Webkul/Admin/src/Http/Controllers/Marketing/Promotions/CartRuleCouponController.php, packages/Webkul/Admin/src/Routes/marketing-routes.php
=> Fixed issue #9701

packages/Webkul/Admin/src/Config/system.php
=> Fixed issue #9707

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
=> Fixed Issue #9714

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/address/form.blade.php
=> Fixed issue #9713

packages/Webkul/Shop/src/Http/Requests/Customer/ProfileRequest.php
Refactor profile validation rules in ProfileRequest.php #9726
=> Refactor profile validation rules in ProfileRequest.php

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/bundle.blade.php
=> Fixed issue #9705

UPGRADE.md, packages/Webkul/Admin/src/Http/Controllers/Marketing/Promotions/CartRuleCouponController.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Attribute/src/Repositories/AttributeFamilyRepository.php, packages/Webkul/CartRule/src/Repositories/CartRuleCouponRepository.php, packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleIndex.php, packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php, packages/Webkul/CatalogRule/src/Providers/CatalogRuleServiceProvider.php, packages/Webkul/CatalogRule/src/Repositories/CatalogRuleRepository.php, packages/Webkul/Customer/src/Notifications/CustomerUpdatePassword.php, packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php, packages/Webkul/Marketing/src/Jobs/UpdateCreateSearchTerm.php, packages/Webkul/Notification/src/Repositories/NotificationRepository.php, packages/Webkul/Payment/src/Listeners/GenerateInvoice.php, packages/Webkul/Paypal/src/Http/Controllers/StandardController.php, packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php, packages/Webkul/Product/src/Jobs/ElasticSearch/UpdateCreateIndex.php, packages/Webkul/Product/src/Repositories/ProductBundleOptionRepository.php, packages/Webkul/Sales/src/Repositories/ShipmentRepository.php, packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/ResetPasswordController.php, packages/Webkul/SocialLogin/src/Repositories/CustomerSocialAccountRepository.php
I removed an unwanted PHP document as a params type.
=> Refactor code to remove unused dependencies

packages/Webkul/Shop/src/Http/Controllers/API/CartController.php, packages/Webkul/Shop/src/Http/Requests/Customer/ProfileRequest.php, packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
=> Revert Changes

packages/Webkul/Shop/src/Resources/views/components/form/control-group/error.blade.php
Fixed error message issue #9733
=> Fixed error message issue #9733 

README.md
Add Bagisto Starter Pack link to README.md
=> Add Bagisto Starter Pack link to README.md

.github/PULL_REQUEST_TEMPLATE.md
=> Refactor PR-Template

packages/Webkul/Admin/src/Resources/views/customers/customers/view/invoices.blade.php
=> Fixed Issue #9728

packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/taxes/rates/index.blade.php
Refactor shimmer effect to tax rates.
=> Refactor shimmer effect to tax rates

packages/Webkul/Admin/src/DataGrids/Sales/OrderRefundDataGrid.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/recent-order-items.blade.php
refund: refund datagrid issue fix when search.
=> refund: refund datagrid issue fix when search.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Fixed issue in the catalog rule page condition section.
1: Navigate to Admin Panel -> Marketing Section -> Promotions -> Catalog Rules.
2: Edit the Added Catalog Rule.
3: Add conditions and select categories.
4: See the error.
**Note: If there are any conditions added, first remove the previous conditions and then add new ones.**
=> Fixed Catalog rule page issue.

packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/category-carousel/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/image-carousel/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/product-carousel/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/services-content/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
Fixed theme Customization shimmers
=> Fixed theme Customization shimmers

packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Fixed configurable product image issue
=> Fixed configurable product image issue

packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
=> Fixed issue #9633

UPGRADE.md
=> Fixed upgrade guide

UPGRADE.md
=> Updated upgrade file

packages/Webkul/Shop/src/Resources/views/checkout/onepage/summary.blade.php
Fixed cart item inclusve tax prices issue
=> Fixed cart item inclusve tax prices issue

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/images.blade.php, packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
Product Image Upload Validation Added
=> Product Image Upload Validation Added

UPGRADE.md, packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php, packages/Webkul/Core/src/Traits/CoreConfigField.php, packages/Webkul/Tax/src/Repositories/TaxCategoryRepository.php
=> Issue #9814 fixed

packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
image picker component console error fixed.
=> image picker component console error fixed.

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php, packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/edit.blade.php
pass variable in view rendering events for edit pages.
=> pass variable in view rendering events for edit pages.

packages/Webkul/Shop/src/Resources/views/components/datagrid/toolbar/filter.blade.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
Remove dark classes and short classes from the shop Datagrid
=> Remove dark classes and short classes from the shop Datagrid

packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
Fix admin roles with custom permission appers console erros and not working tree view.
=> Fix admin role with custom.

packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php
=> Fixed elastic indexer issue

packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php, packages/Webkul/Theme/src/Models/ThemeCustomization.php, packages/Webkul/Theme/src/Repositories/ThemeCustomizationRepository.php
=> Issue #9796 fixed.

UPGRADE.md
=> Update upgrade.md file.

packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php, packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php, packages/Webkul/Shop/src/Http/Controllers/API/WishlistController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/Account/AddressController.php
chore: Update WishlistController.php to delete wishlist item with additional validation.
chore: Update AddressController.php to update Address with additional validation.
Update the default address in a single query.
Use type hinting for method parameters
=> chore: Update controllers with additional validation

packages/Webkul/Admin/src/Http/Requests/UserForm.php
Fix user password validation from back-end API issue
=> Fix user password validation from back-end API issue

packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
=> Fixed issue #9875

packages/Webkul/Admin/src/Resources/views/emails/orders/inventory-source.blade.php, packages/Webkul/Admin/src/Resources/views/emails/orders/shipped.blade.php, packages/Webkul/Payment/src/Payment/Payment.php, packages/Webkul/Shop/src/Resources/views/emails/orders/shipped.blade.php
=> Fixed issue #9863

packages/Webkul/Admin/src/Http/Controllers/Customers/AddressController.php, packages/Webkul/Admin/src/Http/Requests/AddressRequest.php, packages/Webkul/Admin/src/Http/Requests/CartAddressRequest.php, packages/Webkul/Shop/src/Http/Controllers/API/AddressController.php, packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php, packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php
Fixed issue #9852
Create new address request for admin package
=> Fixed issue #9852

routes/breadcrumbs.php
Fixed product breadcrumbs issue
=> Fixed product breadcrumbs issue

packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js, packages/Webkul/Shop/src/Resources/assets/js/plugins/vee-validate.js
=> Issue #9883 fixed

packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
Refactor reporting view filters
=> Refactor reporting view filters

packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php
Fixed theme page Filter issues
=> Fixed theme page Filter issues

packages/Webkul/DataTransfer/src/Helpers/Importers/Product/Importer.php, packages/Webkul/Product/src/Database/Migrations/2024_06_03_174128_create_product_channels_table.php
Added channels support in data transfer import
=> Added channels support in data transfer import

packages/Webkul/Shop/src/Resources/views/components/products/ratings.blade.php, packages/Webkul/Shop/src/Resources/views/products/view.blade.php
- When add downloadable product to the cart warning message appears that
undefined `quantity` fixed.
- Rating component props of total should be number warning fixed.
=> Downloadable product add to cart and rating props warning fixed.

packages/Webkul/Product/src/Repositories/ProductRepository.php
=> Filter issue fixed

packages/Webkul/Product/src/Type/AbstractType.php, packages/Webkul/Product/src/Type/Configurable.php
Configurable product type class refactorred and optimized
=> Configurable product type class refactorred and optimized

packages/Webkul/Shop/src/Resources/views/checkout/onepage/address/customer.blade.php
=> Cart checkout

packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Bunndle product required option issue fixed
=> Bunndle product required option issue fixed

packages/Webkul/Product/src/Type/Bundle.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Bundle product option validation issue fixed
=> Bundle product option validation issue fixed

packages/Webkul/Shop/src/Resources/views/components/products/carousel.blade.php, packages/Webkul/Shop/src/Resources/views/components/tabs/index.blade.php, packages/Webkul/SocialShare/src/Resources/views/share.blade.php
=> Imporoved web vital

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
=> Fixed locale switcher for RTL

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/pagination.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view/invoices.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view/orders.blade.php, packages/Webkul/Admin/src/Resources/views/customers/customers/view/reviews.blade.php, packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/stock-threshold-products.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/todays-details.blade.php, packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php, packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php
Fixed transaction page view issue and icon issue in RTL
=> Fixed transaction page view issue and icon issue in RTL

packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php
#9932 
Resolved the issue where error messages are not displayed correctly
=> Fixed #9932 

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
=> Added events in header

packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Small hotfix related my previous PR https://github.com/bagisto/bagisto/pull/9931
=> Updated customers orders view render events

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/summary.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/types/bundle.blade.php, packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
=> Fixed multiselect issue

packages/Webkul/Shop/src/Resources/views/search/index.blade.php
=> Prevent Template Injection.

packages/Webkul/Installer/src/Console/Commands/Installer.php
There are a few fixes in the CLI installer.
=> few fixes in CLI Installer

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
=> Issue #9952 fixed.

CHANGELOG.md, packages/Webkul/Core/src/Core.php
=> Update version and changelog.

packages/Webkul/CMS/src/Repositories/PageRepository.php
Fixed CMS page email send status issue on Update.
Getting null value after CMS page update in API's.
=> Fixed CMS page email send status issue on Update.

packages/Webkul/Core/src/Exceptions/Handler.php
Fix the translation issue on the error page.
=> :bug: Fix the translation issue on the error page.

CHANGELOG.md, packages/Webkul/Core/src/Core.php
update changelog for version 2.2.2
=> update changelog for version 2.2.2

packages/Webkul/Checkout/src/Cart.php, packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
=> fixed cart page exception

packages/Webkul/Shop/src/Routes/customer-routes.php
Fixed the route issue in the customer account section.
=> Fixed the route issue in the customer account section.

packages/Webkul/Product/src/ProductImage.php
=> Update fallback images path

packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
=> Fixed Issue #10014

packages/Webkul/Sales/src/Transformers/OrderPaymentResource.php
=> hotfix: paypal smart button issue fixed

packages/Webkul/Installer/src/Database/Seeders/ProductTableSeeder.php
=> Fixed Issue #10039

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
=> Added Enhancement #10056

packages/Webkul/Shop/src/Resources/lang/ar/app.php, packages/Webkul/Shop/src/Resources/lang/bn/app.php, packages/Webkul/Shop/src/Resources/lang/de/app.php, packages/Webkul/Shop/src/Resources/lang/en/app.php, packages/Webkul/Shop/src/Resources/lang/es/app.php, packages/Webkul/Shop/src/Resources/lang/fa/app.php, packages/Webkul/Shop/src/Resources/lang/fr/app.php, packages/Webkul/Shop/src/Resources/lang/he/app.php, packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php, packages/Webkul/Shop/src/Resources/lang/it/app.php, packages/Webkul/Shop/src/Resources/lang/ja/app.php, packages/Webkul/Shop/src/Resources/lang/nl/app.php, packages/Webkul/Shop/src/Resources/lang/pl/app.php, packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php, packages/Webkul/Shop/src/Resources/lang/ru/app.php, packages/Webkul/Shop/src/Resources/lang/sin/app.php, packages/Webkul/Shop/src/Resources/lang/tr/app.php, packages/Webkul/Shop/src/Resources/lang/uk/app.php, packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
=> Added Enhancement #10055

packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
=> Fixed Issue #10010

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Fixed Issue #10002

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Fixed Issue #10004

packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php, packages/Webkul/Admin/src/Http/Controllers/Settings/Tax/TaxRateController.php, packages/Webkul/Admin/src/Routes/catalog-routes.php, packages/Webkul/Admin/src/Routes/cms-routes.php, packages/Webkul/Admin/src/Routes/configuration-routes.php, packages/Webkul/Admin/src/Routes/customers-routes.php, packages/Webkul/Admin/src/Routes/marketing-routes.php, packages/Webkul/Admin/src/Routes/notification-routes.php, packages/Webkul/Admin/src/Routes/reporting-routes.php, packages/Webkul/Admin/src/Routes/rest-routes.php, packages/Webkul/Admin/src/Routes/sales-routes.php, packages/Webkul/Admin/src/Routes/settings-routes.php, packages/Webkul/Admin/src/Routes/web.php, packages/Webkul/Category/src/Repositories/CategoryRepository.php, packages/Webkul/Shop/src/Routes/checkout-routes.php, packages/Webkul/Shop/src/Routes/customer-routes.php, packages/Webkul/Shop/src/Routes/store-front-routes.php, packages/Webkul/Shop/src/Routes/web.php
Refactor admin and shop routes.
=> Refactor admin and shop routes.

packages/Webkul/Shop/src/Resources/views/products/prices/bundle.blade.php, packages/Webkul/Shop/src/Resources/views/products/prices/grouped.blade.php, packages/Webkul/Shop/src/Resources/views/products/prices/index.blade.php
Added Missing Price class label on different types of products.
Test All types of products, and after selecting varients, the price should be updated as per the product.
=> Added Missing Price class label on different types of products.

packages/Webkul/Shop/src/Resources/views/components/categories/carousel.blade.php
Fixed category carousel image shimmer.
=> Fixed category carousel image shimmer.

packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
[Fixed: Catalog/Product event at admin end.]
=> [Fixed: Catalog/Product event at admin end.]

packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
Fixed typo in reporting section.
=> Fixed Typo.

packages/Webkul/Shop/src/Http/Middleware/Locale.php
=> Fixed Issue #10103

packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
=> Fixed Issue #10096

packages/Webkul/Admin/src/DataGrids/CMS/CMSPageDataGrid.php
=> Fixed issue #10022

packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/edit.blade.php
=> Removed Required Filed in tax states.

packages/Webkul/Paypal/src/Resources/views/checkout/onepage/paypal-smart-button.blade.php
Fix issue for multiple currencies for PayPal payments.
=> Fix issue for multiple currencies for PayPal payments.

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
Fix the minor issue inside the admin profile image height.
=> Fix minor issue inside the admin profile image height.

packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
=> Fixed Issue #10082

CHANGELOG.md
=> Change log updated.

packages/Webkul/Admin/src/Config/system.php
=> Fixed Isuse #10128

CHANGELOG.md
=> Update changelog File.

CHANGELOG.md
=> feat: Update CHANGELOG.md

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
Made the PR again on 2.2 as aked
=> Fix Subtotal display in admin order view

packages/Webkul/Shop/src/Resources/views/categories/filters.blade.php, packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/address.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/payment.blade.php, packages/Webkul/Shop/src/Resources/views/checkout/onepage/summary.blade.php, packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Found duplicate view render event into some blade file.
Check files.
=> resolved dublicate view render event on blade file

README.md
=> add Docker installation link.

packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php, packages/Webkul/Installer/src/Console/Commands/Installer.php
Fix Attribute family issue. #10193
=> Fix Attribute family issue.

packages/Webkul/Installer/src/Console/Commands/Installer.php
=> fix linting test.

packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
=> Issue #10199 fixed.

packages/Webkul/Checkout/src/Cart.php
=> Issue #10173 fixed.

packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
=> Issue #10189 fixed.

packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
=> fix issue #10188 fixed.

packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/seo/index.blade.php
Category seo component, issue #10171
=> Category seo component

packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
Fix the view page of notifications.
=> Fix the view page of notifications.

packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
=> Issue #10166 fixed.

packages/Webkul/Shop/src/Http/Controllers/PageController.php, packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
=> Issue #10162 fixed.

packages/Webkul/Installer/src/Console/Commands/Installer.php
=> issue #10179 fixed.

packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
=> Issue #10165 fixed.

packages/Webkul/Shop/src/Resources/views/search/index.blade.php
=> [2.2] fix: Getting Console Error when we add symbols On Search Bar on Shop Front. #10217

packages/Webkul/Shop/src/Http/Requests/ContactRequest.php
https://github.com/bagisto/bagisto/issues/10212
=> [2.2] fix: fixed validation issue

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/bundle.blade.php
[2.2] fix: validation issue with v-model.
=> [2.2] fix: validation issue with v-model.

packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/services.blade.php
Fixed Issue #10208 
Change the footer and services section with theme-based.
=> [v2.2]: Change the footer and services section with theme-based.

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
Fixed Issue #10229
Added default 0 value in inventory field in config product.
=> Added default 0 value in inventory field in config product.

packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/create.blade.php
=> Fixed Issue #10228

packages/Webkul/Admin/src/Resources/views/customers/customers/view/notes.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
=> Fixed Issue #10242

packages/Webkul/Admin/src/Resources/views/errors/index.blade.php
=> Fixed Issue #10249

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php, packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Adding events in the order view section for shop and admin both ends.
=> :v: [v2.2] : Adding events in the order view section for shop and admin both ends.

packages/Webkul/Checkout/src/Cart.php
- Fixed price conversion issue.
=> [2.2] fix: price conversion issue

packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
[2.2] fix: issue #10296 fixed.
=> [2.2] fix: issue #10296 fixed.

packages/Webkul/Admin/src/Http/Requests/ProductForm.php, packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php, packages/Webkul/Admin/src/Validations/ProductCategoryUniqueSlug.php
[2.2] fix: issue #10295 fixed.
=> [2.2] fix: issue #10295 fixed.

packages/Webkul/Admin/src/Resources/views/customers/customers/view/notes.blade.php, packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
[2.2] fix: issue #10297 fixed.
=> [2.2] fix: issue #10297 fixed.

packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
[2.2] fix: issue #10299 fixed.
=> [2.2] fix: issue #10299 fixed.

packages/Webkul/Product/src/Type/Configurable.php
=> :wrench: [2.2] fix: #10262 fixed variant issue

packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php, packages/Webkul/Sales/src/Exceptions/InvalidRefundQuantityException.php, packages/Webkul/Sales/src/Repositories/RefundRepository.php
=> :wrench: [2.2] fix: #10234 error exception for invalid refund quantity

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Http/Controllers/User/SessionController.php
=> :wrench: [2.2] fix: #10240 redirection issue

packages/Webkul/Shop/src/Resources/views/search/index.blade.php
=> :wrench: [2.2] fix: #10217 fixed single qoute issue

packages/Webkul/Admin/src/Resources/views/components/modal/index.blade.php, packages/Webkul/Shop/src/Resources/views/components/modal/index.blade.php
No attributes are set on the footer of the modal. The problem was that the wrong variable was used. 
Only manually. Set attributes on modal footer
=> Fix set modal footer attribute

packages/Webkul/Shop/src/Resources/views/products/view.blade.php
[2.2] fix: #10283 fixed buy now and add to cart issue
=> 🔧 [2.2] fix: #10283 fixed buy now and add to cart issue

packages/Webkul/Shop/src/Http/Requests/Customer/ProfileRequest.php, packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
=> 🔧 [2.2] fix: issue #10294 fixed.

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> 🔧 [2.2] fix: Fixed Issue #10310

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> 🔧 [2.2] fix: Fixed Issue #10308

packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php, packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/items.blade.php
=> 🔧 [2.2] fix: Fixed issue in cross-channel product search.

packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php, packages/Webkul/Admin/tests/Feature/Sales/RefundTest.php, packages/Webkul/Sales/src/Repositories/OrderItemRepository.php, packages/Webkul/Sales/src/Repositories/OrderRepository.php
fix: issue in returned qty inventory #10205
=> :wrench: [2.2] fix: issue in returned qty inventory

packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
=> 🔧 [2.2] fix: Fix the mass delete issue in the attribute datagrid.

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
=> 🔧 [2.2]:Fixed issue in datagrid text type input field section.

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/configurable.blade.php
=> 🔧 [2.2] fix : Fixed issue in configurable product varient issue

packages/Webkul/Admin/src/Http/Controllers/Settings/CurrencyController.php, packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php, packages/Webkul/Admin/tests/Feature/Settings/CurrenciesTest.php
=> 🔧 [2.2] fix: Fixed Issue #10350

packages/Webkul/Admin/src/Config/system.php
=> 🔧 [2.2] fix: Fixed Issue  #10366

packages/Webkul/Admin/src/Config/system.php
=> 🔧 [2.2] fix: Fixed Issue #10368

packages/Webkul/Installer/src/Console/Commands/Installer.php, packages/Webkul/Installer/src/Database/Seeders/Core/CurrencyTableSeeder.php
=> :wrench: [2.2] fix: fixed installer issues

packages/Webkul/Checkout/src/Cart.php
=> fix: add additional column while updating cart items

packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
Fixed cart item count issue according to configuration
=> Fixed cart item count issue according to configuration

packages/Webkul/Admin/tests/Feature/Settings/RoleTest.php
=> Fix Failing Test cases.

composer.json, composer.lock, config/visitor.php, packages/Webkul/Checkout/src/Cart.php, packages/Webkul/Core/src/Config/visitor.php, packages/Webkul/Product/src/Repositories/ProductRepository.php, packages/Webkul/Shop/tests/Feature/HomePageTest.php, packages/Webkul/Shop/tests/Feature/LoginPageTest.php, packages/Webkul/Shop/tests/Feature/RegistrationPageTest.php
=> 🎇 Fix test cases

packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
=> 🛠️ [v2.2] : Fixed Issue #10475

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
=> Fixed Issue #10472

packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
Fixed Issue #10434
After downloading the error file, we need to remove the error column after fixing the error in the csv or xls file.
I have fixed the issue on the downloading error file.
=> 🛠️ [v2.2] : Fixed Issue #10434

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/search.blade.php
=> ➕ Added Improvement #10429

packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php
=> 🛠️ [v2.2] : Fixed Issue #10426

packages/Webkul/DataTransfer/src/Helpers/Importers/Customer/Importer.php
=> 🔧 [v2.2] : Fixed Issue #10444 #10443

packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
=> 🔧 [v2.2] : Fixed Issue #10432

packages/Webkul/Admin/src/Config/system.php
=> 🔧 [v2.2] : Fixed Issue #10373

packages/Webkul/Shop/src/Resources/views/components/image-zoomer/index.blade.php
=> Fixed image zoomer UI issue

packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
=> Remove extra classes.

packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
=> bind aria-label value

packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Fixed Issue #10482 (non-editable attribute code issue)
=> Fixed Issue #10482 (non-editable attribute code issue)

packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/edit.blade.php
Fixed tax rate issue(tax rate removed after editing the tax rate)
=> Fixed tax rate issue(tax rate removed after editing the tax rate)

packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Paypal/src/Payment/SmartButton.php
https://github.com/bagisto/bagisto/issues/10232
=> fix: locked the smart button method also

packages/Webkul/Customer/src/Resources/views/captcha/scripts.blade.php, packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
https://github.com/bagisto/bagisto/issues/10497
=> :wrench: fix: fixed #10497 google captcha issue

packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php, packages/Webkul/Shop/src/Listeners/Customer.php
Fix customer registration email issues
=> Fix customer registration email issues

packages/Webkul/Shop/tests/Feature/RegistrationPageTest.php
=> fixed registration testcases

packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php
=> Fixed checkout address issue

.github/PULL_REQUEST_TEMPLATE.md
Update the new formatted pull request.
=> ✨ Update the new formatted pull request.

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php, packages/Webkul/Core/src/SystemConfig/ItemField.php
=> Fixed issue #10512

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
=> 🔨 [v2.2] : fix issue #10196

packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
=> 🔨 [v2.2] : fix Issue #10519

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Paypal/src/Config/paymentmethods.php
The sort value was set to **0**, i changed this to **4**.
=> Added sort value for paypal payment method

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
=> 🔧  fix issue #10518

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
Fixed Issue #10515
This PR is also dependent on https://github.com/bagisto/bagisto/pull/10526
=> 🔧 [v2.2] : Fixed Issue #10515

packages/Webkul/Shop/src/Resources/views/products/view.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/types/grouped.blade.php
=> 🔨 [v2.2] : fix Issue #10513

config/setup.ts, tests/admin/catalog/attribute-families.spec.ts, tests/admin/catalog/attributes.spec.ts, tests/admin/catalog/categories.spec.ts, tests/admin/catalog/products.spec.ts, tests/admin/cms.spec.ts, tests/admin/configuration/catalog.spec.ts, tests/admin/configuration/customer.spec.ts, tests/admin/configuration/email.spec.ts, tests/admin/configuration/general.spec.ts, tests/admin/configuration/sales.spec.ts, tests/admin/customers/customers.spec.ts, tests/admin/customers/groups.spec.ts, tests/admin/customers/reviews.spec.ts, tests/admin/marketing/communications.spec.ts, tests/admin/marketing/promotions.spec.ts, tests/admin/marketing/search-seo.spec.ts, tests/admin/sales.spec.ts, tests/admin/settings/channels.spec.ts, tests/admin/settings/currencies.spec.ts, tests/admin/settings/exchange-rates.spec.ts, tests/admin/settings/inventory-sources.spec.ts, tests/admin/settings/locales.spec.ts, tests/admin/settings/roles.spec.ts, tests/admin/settings/taxes.spec.ts, tests/admin/settings/themes.spec.ts, tests/admin/settings/users.spec.ts, tests/utils/admin/addressHelper.ts, tests/utils/admin/formHelper.ts, tests/utils/admin/loginHelper.ts
Updated tests of admin end, Updated config file
=> Updated tests of admin end, Updated config file

packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
update product search engine configuration in ProductsCategoriesProxyController
=> 🔨 fix: update product search engine.

packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php
#10270
The create method will verify the **_default_address_** with each request. If the **_default_address_** is already assigned to another address and a new address is being created with the **_default_address_** selected, this case will be handled.
=> 🔨 [v2.2] : Fixed Default address in shop section.

packages/Webkul/SocialLogin/src/Http/routes.php
=> Fixed Social login issue

packages/Webkul/Admin/src/Resources/lang/es/app.php
Updated Spanish (Spain) translation for Bagisto admin
=> Updated Spanish (Spain) app.php translation

README.md
Update README to reflect latest LLM integrations and use cases.
=> 📝  Update README to reflect latest LLM integrations and use cases.

packages/Webkul/Admin/tests/e2e-pw/tests/configuration/catalog/products.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/catalog/rich_snippets.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/general/content.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/general/design.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/general/general.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/general/magic-ai.spec.ts
=> Configuration Test Cases

packages/Webkul/Admin/tests/e2e-pw/tests/customers/groups.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/marketing/search-seo.spec.ts
[playwright]: Added search and seo tests
=> [playwright]: Added search and seo tests

packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
Fixed Issue in attribute section on `use attribute in configurable product`.
=> [v2.2] : Fixed Issue in attribute section.

packages/Webkul/Admin/src/Config/system.php, packages/Webkul/Admin/src/DataGrids/Customers/GDPRDataGrid.php, packages/Webkul/Admin/src/Resources/views/marketing/search-seo/url-rewrites/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/Shop/src/DataGrids/GDPRRequestsDatagrid.php
- Fixed issues,
https://github.com/bagisto/bagisto/issues/10587
https://github.com/bagisto/bagisto/issues/10602
https://github.com/bagisto/bagisto/issues/10603
https://github.com/bagisto/bagisto/issues/10598
https://github.com/bagisto/bagisto/issues/10589
https://github.com/bagisto/bagisto/issues/10593
https://github.com/bagisto/bagisto/issues/10594
=> fix: fixed minor issues

packages/Webkul/Shop/src/Resources/views/components/datagrid/table.blade.php
=> Fixed date ui issue #10595

packages/Webkul/Admin/src/Resources/views/customers/gdpr/index.blade.php
Added feature #10599 (export gdpr )
=> Added feature #10599 (export gdpr )

packages/Webkul/Core/src/Menu.php, packages/Webkul/Shop/src/Config/menu.php, packages/Webkul/Shop/src/Http/Controllers/Customer/GDPRController.php, packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php
Fixed issue #10601 disable gdpr
=> Fixed issue #10601 disable gdpr

packages/Webkul/Shop/src/Resources/views/components/layouts/cookie/consent.blade.php
=> Fixed issue #10605

app/Http/Middleware/EncryptCookies.php, bootstrap/app.php
Fixed encryptCookies middleware issue
=> Fixed encryptCookies middleware issue

packages/Webkul/Shop/tests/e2e-pw/playwright.config.ts, packages/Webkul/Shop/tests/e2e-pw/setup.ts, packages/Webkul/Shop/tests/e2e-pw/tests/auth.spec.ts, packages/Webkul/Shop/tests/e2e-pw/tests/cart.spec.ts, packages/Webkul/Shop/tests/e2e-pw/tests/checkout.spec.ts, packages/Webkul/Shop/tests/e2e-pw/utils/customer.ts
Added checkout playwright testcases
=> Added checkout playwright testcases

packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/grouped.blade.php, packages/Webkul/Admin/vite.config.js
=> Fixed Issue #10641

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts
Changes done in downloadable product
=> Changes done in downloadable product

packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
https://github.com/bagisto/bagisto/issues/10663
=> fix: fixed issue in the filename

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/attributes.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts, packages/Webkul/Admin/tests/e2e-pw/utils/faker.ts
Debug Flaky Download product Testcases.
=> Debug Flaky Download product Testcases 

README.md
Remove CI badge from README.md
=> Remove CI badge from README.md

packages/Webkul/Theme/src/Themes.php
https://github.com/bagisto/bagisto/issues/10675
=> chore: removed unwanted code

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts
=> Booking testcase

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php, packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php, packages/Webkul/Admin/src/Routes/catalog-routes.php, packages/Webkul/Admin/tests/Feature/Catalog/Products/ProductTest.php
Added Feature #10612 product copy confirmation
=> Added Feature #10612 product copy confirmation

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts
=> Fixed Edit Config. Test-cases

packages/Webkul/Admin/src/Http/Controllers/CMS/PageController.php, packages/Webkul/Admin/src/Resources/views/cms/create.blade.php, packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php, packages/Webkul/Admin/tests/Feature/Cms/CmsTest.php, packages/Webkul/Installer/src/Database/Seeders/CMS/CMSPagesTableSeeder.php, packages/Webkul/Shop/src/Http/Controllers/PageController.php
=> Fixed cms page channel issue

packages/Webkul/Admin/tests/e2e-pw/playwright.config.ts, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/attribute-families.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/attributes.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/customers/customers.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/customers/gdpr-request.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/sales.spec.ts, packages/Webkul/Shop/tests/e2e-pw/tests/customer.spec.ts, packages/Webkul/Shop/tests/e2e-pw/utils/order.ts
Customer testcases in Admin End
=> Customer testcases in Admin End

packages/Webkul/Admin/tests/e2e-pw/setup.ts, packages/Webkul/Admin/tests/e2e-pw/tests/configuration/customer/settings.spec.ts, packages/Webkul/Customer/src/Rules/VatIdRule.php, packages/Webkul/Customer/src/Rules/VatValidator.php, packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php
=> social login testcase

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts
correction in edit config product
=> correction in edit config product

packages/Webkul/Admin/tests/e2e-pw/playwright.config.ts, packages/Webkul/Admin/tests/e2e-pw/tests/sales.spec.ts
=> correction in testcase

packages/Webkul/Admin/tests/e2e-pw/playwright.config.ts, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/attributes.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts
=> Attribute type testcase

packages/Webkul/Sales/src/Database/Migrations/2025_05_07_121250_update_total_weight_columns_in_shipments_and_weight_shipment_items_tables.php
Fixed the weight and total_weight column types in migration
=> [2.2]Fixed the weight and total_weight column types in migration

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/customers/gdpr-request.spec.ts, packages/Webkul/Shop/tests/e2e-pw/tests/customer.spec.ts, packages/Webkul/Shop/tests/e2e-pw/utils/order.ts
Correction in 2.3 Flaky Testcases
=> Correction in 2.3 Flaky Testcases

packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php, packages/Webkul/Shop/src/Resources/views/products/view/gallery/desktop.blade.php
=> Added fetch priority

packages/Webkul/Admin/src/Resources/views/components/table/td.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/thead/index.blade.php
The table component first didn't provide full darkmode support.
Use the table component
=> Fixed darkmode for table component

packages/Webkul/Admin/src/Resources/views/components/shimmer/tabs/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/tabs/index.blade.php
- Updated the tabs UI component to align with the admin ui
- Added dark mode support
Use the tab component.
=> Updated tabs component to match admin ui

packages/Webkul/Shop/src/Http/Controllers/SearchController.php, packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php, packages/Webkul/Shop/src/Resources/views/categories/view.blade.php, packages/Webkul/Shop/src/Resources/views/search/index.blade.php
=> Fixed category filter issue

CHANGELOG.md, packages/Webkul/FPC/src/Hasher/DefaultHasher.php, packages/Webkul/FPC/src/Listeners/CoreConfig.php, packages/Webkul/FPC/src/Providers/EventServiceProvider.php, packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
https://github.com/bagisto/bagisto/issues/10784
=> fix: fixed search page issue and default hasher

packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php, packages/Webkul/Core/src/Http/Middleware/PreventRequestsDuringMaintenance.php
=> Optimization

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/bn/app.php, packages/Webkul/Admin/src/Resources/lang/ca/app.php, packages/Webkul/Admin/src/Resources/lang/de/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/fr/app.php, packages/Webkul/Admin/src/Resources/lang/he/app.php, packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php, packages/Webkul/Admin/src/Resources/lang/id/app.php, packages/Webkul/Admin/src/Resources/lang/it/app.php, packages/Webkul/Admin/src/Resources/lang/ja/app.php, packages/Webkul/Admin/src/Resources/lang/nl/app.php, packages/Webkul/Admin/src/Resources/lang/pl/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/ru/app.php, packages/Webkul/Admin/src/Resources/lang/sin/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/uk/app.php, packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php, packages/Webkul/Product/src/Type/Booking.php
- Added product type validation for booking products.
- Added validation message in all locales.
=> Added validation on product booking type

packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts, packages/Webkul/Shop/tests/e2e-pw/utils/order.ts
=> Testcases debug

CHANGELOG.md, packages/Webkul/Shop/src/Http/Controllers/API/CartController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/CustomerController.php, packages/Webkul/Theme/src/Theme.php, packages/Webkul/Theme/src/ThemeViewFinder.php, packages/Webkul/Theme/src/Themes.php
- https://github.com/bagisto/bagisto/issues/10838
- https://github.com/bagisto/bagisto/issues/10836
=> fix: cart issue, dob issue and theme package dev capability

packages/Webkul/Admin/src/Http/Controllers/Marketing/Communications/SubscriptionController.php, packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php, packages/Webkul/Shop/src/Http/Controllers/SubscriptionController.php
=> Issue #10841 has been fixed.

packages/Webkul/BookingProduct/src/Helpers/Booking.php
Fixed the issue where selecting a closed time slot for a booking product.
https://webkul.chatwhizz.com/share/view-recording/68b1b0aa017b412c94fa45eb
=> fix(booking): fixed for closed time slots (Closes #10694)

packages/Webkul/Admin/src/Http/Controllers/Customers/ReviewController.php, packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php, packages/Webkul/Admin/tests/Feature/Customers/ReviewTest.php
=> Fixed Sucess Message || Fixed Issue #10897

CHANGELOG.md, packages/Webkul/Admin/tests/e2e-pw/tests/customers/reviews.spec.ts
=> PR Testcases

packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php, packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php
=> Fixed Issue #10912

packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php, packages/Webkul/Product/src/Repositories/ProductRepository.php, packages/Webkul/Product/src/Repositories/SearchRepository.php, packages/Webkul/Shop/src/Http/Controllers/SearchController.php
=> Fix null query issue in search suggestions

CHANGELOG.md, packages/Webkul/Shop/src/Http/Controllers/Customer/CustomerController.php
=> Fixed issue #10937

packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php, packages/Webkul/Core/src/ElasticSearch.php, packages/Webkul/Product/src/Helpers/Indexers/ElasticSearch.php, packages/Webkul/Product/src/Helpers/Product.php, packages/Webkul/Product/src/Jobs/ElasticSearch/DeleteIndex.php, packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php, packages/Webkul/Product/src/Type/Bundle.php
https://github.com/bagisto/bagisto/issues/10903
=> feat: fixed elasticsearch issue on hindi, brazilian and chinese locale

packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
https://github.com/bagisto/bagisto/issues/10847
=> fix: fixed attribute family issue

config/responsecache.php, packages/Webkul/Admin/tests/e2e-pw/tests/catalog/products.spec.ts, packages/Webkul/FPC/src/Replacers/FlashMessagesReplacer.php, packages/Webkul/Shop/src/Resources/views/components/flash-group/index.blade.php
https://github.com/bagisto/bagisto/issues/10840
=> fix: fixed flash message issue
